### ISSUE TITLE
Set resolution or size of ovenplayer

### ISSUE THREAD

**Issue by vitragmehta** [AirenSoft/OvenPlayer#101]
Hi,
I am very new to Onvenmediaengine and Ovenplayer. Apologies in advance if my question sounds noob.

When i call Ovennplayer on my web page; my content is 800x600 and it plays fine; however there are 2 vertical black band in the player window itself. i have gone through the documentation but was not able to find a solution to set the right size of the player window. any guidance / pointers will help

![image](https://user-images.githubusercontent.com/53759761/66117014-5fe17180-e5f1-11e9-8eec-7e0b7c4558f6.png)

**Comment by dimiden** [comment]
The black area (Letter-box) can be adjusted using CSS.

To explain more to you, if you initialize the OvenPlayer as follows:

```
<div id="player_id"></div>
```

The size of the ```#player_id``` to which the player will be placed does not match the size of the video, showing the letter-box.

Try this code at the top of your HTML page, or CSS:

```
<style>
#player_id {width: 800px; height: 600px; }
</style>
```

Where the width and height do not have to be 800/600, and if they are matched to a 4:3 ratio, it doesn't matter what size they are.

**Comment by vitragmehta** [comment]
Perfect; will test and update

Many thanks for the inputs
