### ISSUE TITLE
$(document).ready(function() { "Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by coelhocarlos** [AirenSoft/OvenPlayer#106]
in production folder
<script src="./lib/vue.min.js"></script> Uncaught SyntaxError: Invalid or unexpected token
<script src="./lib/dash.all.min.js"></script> Uncaught SyntaxError: missing ) after argument list
<script src="./lib/clipboard.min.js"></script>
<script src="./lib/jquery-1.12.4.min.js"></script>Uncaught SyntaxError: Invalid or unexpected token
<script src="./lib/popper.min.js"></script>
<script src="./lib/bootstrap.min.js"></script>Uncaught SyntaxError: Invalid or unexpected token
<script src="./ovenplayer/ovenplayer.js"></script> Uncaught SyntaxError: Invalid or unexpected token

**Comment by coelhocarlos** [comment]
in production folder 
    <script src="./lib/vue.min.js"></script>
    <script src="./lib/dash.all.min.js"></script>
    <script src="./lib/clipboard.min.js"></script>
    <script src="./lib/jquery-1.12.4.min.js"></script>
    <script src="./lib/popper.min.js"></script>
    <script src="./lib/bootstrap.min.js"></script>
    <script src="./ovenplayer/ovenplayer.js"></script>

**Comment by SangwonOh** [comment]
@coelhocarlos 

Thank you for your reporting.

At this time, it is difficult to determine which example caused the issue.

Please tell us which example file you opened.
( ex: /dist/production/index.html)

Also, please let us know which environment you ran the example in. (OvenPlayer version, os, browser, etc...)

The player version can be found in the browser debug console.

Thanks!

**Comment by coelhocarlos** [comment]
im get folder drom dist and put to other folder 
![Untitled](https://user-images.githubusercontent.com/16593059/69729072-73e2b480-1104-11ea-993b-919b9a7d16d0.png)

**Comment by coelhocarlos** [comment]
> drom
