### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by janyo1201** [AirenSoft/OvenPlayer#107]
hi 
i meet WebSocket is closed before the connection is established.   when i use domain(e.g. ws://test.example.com/app/stream)  the play around 2minutes will meet this issue , the control bar also disappeared, [https://imgur.com/a/szi4Jel](url)

**Comment by dimiden** [comment]
@janyo1201 
Which branch are you using? If you're using a master branch, it's probably an issue related to ping-pong on the WebSocket.
This issue has been resolved at dev branch and will soon be merged into the master branch.

https://github.com/AirenSoft/OvenMediaEngine/commit/fa7b05797bbff39e30e8b5157fc7a4de1f36b1a6#diff-a0889c7c54bdf9a1916e86f3a90f57e4

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
