### ISSUE TITLE
Firefox is not playing WebRtc

### ISSUE THREAD

**Issue by PlutonicCoder** [AirenSoft/OvenPlayer#111]
The issue can be reproduced in https://airensoft.github.io/OvenPlayer/docs/demo.html  when provided with webrtc video links.
Or is it related to OwenMedia engine?

![image](https://user-images.githubusercontent.com/60276274/73303310-11bd3300-41cb-11ea-9e6b-77c4afb9c3d3.png)

Thanks

**Comment by SangwonOh** [comment]
Hi @PlutonicCoder 

Could you tell us which Firefox version you are using?
And In same condition does playback using chrome works well?

**Comment by PlutonicCoder** [comment]
Hello,
         Firefox version is 72.0.2 (64-bit), also tried with 72.0.1 (64-bit), experiencing the same error. Yes, in chrome the plackback is working well.

Thanks

**Comment by SangwonOh** [comment]
@PlutonicCoder We couldn't reproduce same problem.

You can get detailed log by running OvenPlayer with Debug mode

`OvenPlayer.debug(true);` 

Could you show us detail logs?

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by IanMitchell77** [comment]
What was the fix for this?

I am seeing the video when in Chrome but I get the following error in Firefox:

code: 501
​
error: "Cannot create offer"
​message: "Connection with low-latency(TSC) server failed."
​reason: "WebSocket connection failed."
