### ISSUE TITLE
How to use this with a ReactJS Application?

### ISSUE THREAD

**Issue by emaxters** [AirenSoft/OvenPlayer#112]
Is it possible to use this in a reactjs Application, if so, can you share any documentations?

**Comment by SangwonOh** [comment]
@emaxters Unfortunately, there is no documentation available. OvenPlayer is not ES6 module that reactjs prefer. But you can still import OvenPlayer by using <script src=""></script>.

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
