### ISSUE TITLE
Switching to HLS in Safari

### ISSUE THREAD

**Issue by ievgeniilarin** [AirenSoft/OvenPlayer#114]
Starting the player with HLS source works fine. However, if the first source is WebRTC, switching to HLS doesn't work both in mobile and desktop versions of Safari.
<img width="2002" alt="Demo" src="https://user-images.githubusercontent.com/797871/75025012-12cc4200-54a3-11ea-9951-b94b0eadd34b.png">

**Comment by SangwonOh** [comment]
@ievgeniilarin 
We figured out the reason for the problem. The problem caused by Ovenplayer plays HLS stream using native function of Safari.
We are going to fix this bug ASAP.
Please stay tuned.

**Comment by SangwonOh** [comment]
@ievgeniilarin. Sorry for late respose. This issue resolved at 8c7b4a7. Please check it out with latest OvenPlayer. Thanks.
