### ISSUE TITLE
Seamless switching streams 

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenPlayer#118]
Hi,

Id like to be able to switch streams seamlessly, an approach is start receiving as soon as the player is told but only start decoding/displaying when there is enough data.

Then further we could optimise the switching algorithm so that the player switches on its own, up quality when the buffer is full and reduce quality if the buffer is nearly empty maybe.

Please discuss solutions and where I might modify the source - this is my first contribution ;)

Thanks,

Ian

**Comment by getroot** [comment]
Thanks for the great idea.
How are you trying to solve this at the player level? Our PR is always open.

**Comment by IanMitchell77** [comment]
Hi,

I haven’t looked at the code yet but I plan that when the switch happens it creates a new buffer in parallel to the old buffer and only decodes and switches display when the new buffer has enough data to decode – then the old buffer is discarded.

This will take a while but will be a much nicer user experience – the downside is that it would consume more data during the switch time.

I am an embedded software engineer, writing in C/C++ mostly so its a steep learning curve for me so any help of points are much appreciated.

I am not sure what I do now – can I now checkout a branch for this PR and hopefully get some community help?

Thanks,

Ian

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by SangwonOh** [comment]
@IanMitchell77 You can checkout master branch for PR. Thank you.

**Comment by getroot** [comment]
Please refer to the following url for pull request.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
