### ISSUE TITLE
If the player pauses, will streaming continue?

### ISSUE THREAD

**Issue by alex-jhones** [AirenSoft/OvenPlayer#119]
Hi

I found in testing that streaming continues while the player video is paused. or the browser continued to play without timeout even when minimized without closing the browser.

Is there any way to stop streaming? Because this causes depletion of data capacity on mobile devices and accelerates battery consumption when considering services.

If there are other reasons to continue streaming, I would like to know the background.

I checked the oven player API but couldn't find any related support. I would like to know how to solve this.

[chrome://webrtc-internals]
![image](https://user-images.githubusercontent.com/65345605/81967070-5b843900-9655-11ea-98eb-f72a18128420.png)

**Comment by SangwonOh** [comment]
@alex-jhones Once peer connection established, player keeps connection even if pausing video. Because OvenPlayer is not implemented to close peer connection when playback is paused.

To stop data transfering, using remove() API will be an option.

**Comment by alex-jhones** [comment]
I can't find the api on the web page. Can I get the information?
https://airensoft.gitbook.io/ovenplayer/api-reference/api

**Comment by SangwonOh** [comment]
Please refer this. Thank you.

https://github.com/AirenSoft/OvenPlayer/blob/master/docs/api.md#playerremove

**Comment by alex-jhones** [comment]
I reflected it as you told me, but it still seems that the stream continues to be delivered. However, I confirmed that it was stopped on the log. Can you tell me what the problem is?

![image](https://user-images.githubusercontent.com/65345605/82391528-7c48f600-9a7c-11ea-9e2c-26c19fbdf04a.png)

I checked it at  chrome: // webrtc-internals.

**Comment by SangwonOh** [comment]
Even if peer connection closed chrome remains tab panel a few seconds. To checking metrics graph is still running or stoped you can see stream status.

**Comment by alex-jhones** [comment]
Thank you. I confirmed that I stopped the stream. But why maintain the peer connection? If the stream is closed, shouldn't the connection be closed? I misunderstood that this is still taking the stream.

![image](https://user-images.githubusercontent.com/65345605/82396971-4e6aae00-9a8a-11ea-867a-3b157d4b797d.png)

**Comment by SangwonOh** [comment]
OvenPlayer close the peer connection. I think [chrome://webrtc-internals] maintains the peer connection even the peer connection is closed. So that gives chance to the developers  to check event logs like ice candidate status.

In our case, [chrome://webrtc-internals] remains the tab when the peer connection is closed. And then after a while the tabs are closed automatically

**Comment by SangwonOh** [comment]
We close this issue because it has not had recent activity. If you have further issues, open the issue again. Thanks. Good luck.
