### ISSUE TITLE
Can't use RTMP stream as input directly

### ISSUE THREAD

**Issue by nxtreaming** [AirenSoft/OvenPlayer#121]
Thank for this great player!

It seems that OvenPlayer fails to support RTMP source natively, although, the  [Demo](https://ovenplayer.com/docs/demo.html) shows we can select RTMP as the source.

The code:

player = OvenPlayer.create("player", {
    sources: [
  {
    "file": "rtmp://stream.example.com/app/mystream",
    "type": "rtmp"
  }
]
});

The error:

{code: 101, message: "Can not load due to unsupported media.", reason: "Can not load due to unsupported media."}

Is there any plan to support RTMP source?

Thanks.

**Comment by SangwonOh** [comment]
@nxtreaming OvenPlayer supports RTMP playback. This issue may be a browser issue.

OvenPlayer plays RTMP source using Adobe Flash. But since most modern browsers don't  allows Adobe Flash defaultly. So please make sure that your browser is allowed to use Adobe Flash. Or make it useable manually.

**Comment by nxtreaming** [comment]
I see.

I use Chrome which will totally remove Adobe Flash in Jan 2021. I try to enable Flash manually.

Will OvenPlayer support RTMP natively in future?

Thanks.

**Comment by SangwonOh** [comment]
Unfortunately there is no way to playback RTMP by standard HTML. It is hard to say that further support RTMP. Thanks.

**Comment by nxtreaming** [comment]
I see.

I confirmed RTMP playback is supported through Adobe Flash in OvenPlayer.

Thanks.

**Comment by alnux** [comment]
Could You Make it compatible with http-flv, becouse there is a nginx-rtmp-flv-module and transcose rtmp to flv and it Will be Nice if ovenplayer soport it
