### ISSUE TITLE
[Questions] Functional request

### ISSUE THREAD

**Issue by Barahten** [AirenSoft/OvenPlayer#122]
Hello!
Does this player have the following features:
1. An opportunity for manual switching of quality of HLS
2. Is it possible to install the VTT file for preview when hovering over the progress bar?

**Comment by SangwonOh** [comment]
@Barahten Hello.

OvenPlayer doesn't have functions you asked. But

1. An opportunity for manual switching of quality of HLS

This is very good suggestion. We will be planning to implement this feature.

2. Is it possible to install the VTT file for preview when hovering over the progress bar?

We are going to implement this feature very soon.

**Comment by Barahten** [comment]
I have a list of suggestions for improving your player, where and how can I provide it for you?

**Comment by SangwonOh** [comment]
@Barahten Thanks for your contribution. we made new label named `feature requests`. Please read below and make an issue for each features and label it `feature requests`.

https://github.com/AirenSoft/OvenPlayer/blob/master/CONTRIBUTING.md#feature-requests

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
