### ISSUE TITLE
Embedded Player

### ISSUE THREAD

**Issue by enigmathion** [AirenSoft/OvenPlayer#125]
Good morning, I tell you that I have a problem with OvenPlayer. I downloaded the OvenPlayer from this site and unzipped it, there are several files and folders and almost all have examples of video playback and only one with example of streaming (oem_player) but when changing the addresses it does not contact! Can someone tell me what else I should do? I only need the video frame to embed on my website!

**Comment by SangwonOh** [comment]
@enigmathion Hi. 
Can I get some informations belows?

1. What is the url of your page that you are testing like? 

2. What protocol do you use at your page? Is that a http or a https?

3. Do you see any error on Network debugging panel (Chrome developer tool)?

**Comment by enigmathion** [comment]
The application works perfect, that is not a problem, the problem I have is that I cannot find the file that I must leave with the frame to embed it on my website, only the video! As I show in the picture!
![Anotación 2020-06-09 225619](https://user-images.githubusercontent.com/42680070/84218370-a5214180-aaa4-11ea-9abb-a32173d9b6cb.png)

**Comment by SangwonOh** [comment]
Please follow the basic instruction from https://airensoft.gitbook.io/ovenplayer/

And simplest code you can write on your page is https://airensoft.gitbook.io/ovenplayer/#starter-template. This will show only player.

**Comment by enigmathion** [comment]
Great, thanks so much for your reply. But I am still having problems with the player. I was able to embed it but there is no image, it throws a network error from what I understand! Although if I enter from another site it looks perfect! I throw the links!

Player: http://lacostafm.com.ar/OvenPlayer/
Embedded Player: http://lacostafm.com.ar/

The code I am using:
<! doctype html>
<html lang = "is">
<head>
<meta charset = "utf-8">
<script src = "http://lacostafm.com.ar/OvenPlayer/dist/production/ovenplayer/ovenplayer.js"> </script>
<title> OvenPlayer For OME </title>
</head>
<body>
<div id = "player"> </div>
<script>
let player = OvenPlayer.create ("player", {
sources: [
{
"file": "ws: //64.227.100.31: 3333 / app / stream_o",
"type": "webrtc"
}
     ]
  });
       player.on ("error", function (error) {
         console.log (error);
       });
</script>
</body>
</html>

What am I missing? Thank you!

**Comment by SangwonOh** [comment]
Ok. At `Embedded Player: http://lacostafm.com.ar/`.  Please check the path of the ovenplayer is 

`<script src="http://lacostafm.com.ar/OvenPlayer/dist/production/ovenplayer/ovenplayer.js"></script>`

Additionally you don't need to import these scripts. These script is used for OvenPlayer demo page.

<link rel="stylesheet" href="docs/lib/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
<link href="docs/lib/new-age.min.css" rel="stylesheet">
<script src="docs/lib/vue.min.js"></script>
<script src="docs/lib/dash.all.min.js"></script>
<script src="docs/lib/clipboard.min.js"></script>
<script src="docs/lib/jquery-1.12.4.min.js"></script>
<script src="docs/lib/popper.min.js"></script>
<script src="docs/lib/bootstrap.min.js"></script>

**Comment by enigmathion** [comment]
Thank you very much, in the previous comment put the route, it is the same as you indicate, I copy it again to corroborate!

`<!doctype html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<script src="http://lacostafm.com.ar/OvenPlayer/dist/production/ovenplayer/ovenplayer.js">		</script>
			<title>OvenPlayer For OME</title>
	</head>
	<body>
		<div id="player"></div>
		<script>
			let player = OvenPlayer.create("player", {
		sources: [
			{
"file": "ws://64.227.100.31:3333/app/stream_o",
"type": "webrtc"
			}
    ]
 });
      player.on("error", function(error){
        console.log(error);
      });
		</script>
	</body>
</html>`

**Comment by SangwonOh** [comment]
@enigmathion Does everything go alright? Then please close this issue.

**Comment by enigmathion** [comment]
Yes, everything works fine, it seemed that inside ovenplayer.js there is a statement that points to another .js from the same folder, I still couldn't figure out which one and leave them all. Thank you very much for your help! I close this thread!
