### ISSUE TITLE
Feature request: Set Buffer in WebRTC

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenPlayer#127]
Is it possible to set 0.5 or 1 second buffering for WebRTC so it adds some delay but ensures seamless playback? I don't even know if it's possible but it would be great if there was such an option and something that's dynamic (so it can reduce and increase buffer depending on the network conditions)

**Comment by SangwonOh** [comment]
It's impossible to fully control the buffer for the WebRTC stream.

**Comment by mpisat** [comment]
Got it. Thanks.

**Comment by htliu6** [comment]
> It's impossible to control the buffer for the WebRTC stream.

@SangwonOh Execuse me! I wonder why this is impossible. Thanks!

**Comment by SangwonOh** [comment]
@htliu6 Hi. I used to think I had no control over the buffer. However, we do have some buffer control using the RTCRtpReceiver extensions.
You can set `playoutDelayHint` with the following settings in OvenPlayer.
> https://airensoft.gitbook.io/ovenplayer/initialization#webrtcconfig.playoutdelayhint

And you can test it by setting ‘Enable Playout Delay Hint’ in our demo player.
> https://demo.ovenplayer.com

**Comment by htliu6** [comment]
@SangwonOh Thanks for your kindly reply!
I have one more question, when `bufferChanged` event fired, I print the `data.buffer`, but I got `undefined`.
So, I wonder how I can read the buffer length while playing.
Thanks!
