### ISSUE TITLE
WebRTC on Firefox doesn't work with or without a TURN server

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenPlayer#128]
I'm getting this error on the console
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details

The same video plays fine on Safari and Chrome (both windows, mac os and mobile phones)

![image](https://user-images.githubusercontent.com/52810975/84615622-b5497e80-aef3-11ea-961c-98df72c31980.png)

OvenMedia is running on Docker with default ICE ports 10000-10005/udp

**Comment by mpisat** [comment]
I tested with TURN only, it said add STUN servers, so I added STUN servers to config and it still doesn't work. Is firefox incapable of receiving WebRTC streams from OME and other Media servers?

`
    <div id="player_id"></div>

    <script>

    let webrtcSources = [{type : "webrtc", file : "wss://domain.com:3334/app/stream_o", label : "1080"}];
    let player = OvenPlayer.create("player_id", {
        sources: webrtcSources, 
    loop : false,
    autoStart : true,
    mute : true,
    controls : true,
webrtcConfig: {
    iceServers: [
        {
            "urls": [
                "stun:stun.l.google.com:19302"
            ]
        },
        {
            "urls": [
                "turn:165.22.50.93:3478?transport=tcp",
                "turn:165.22.50.93:3478?transport=udp"
            ],
            "username": "myuser",
            "credential": "mypass"
        }
    ]
}
    });
      player.on("error", function(error){
        console.log(error);
      });
    </script>
`

**Comment by SangwonOh** [comment]
No. Firefox should have to work fine too. Basic playback with OME via firefox works fine on my enviroment. Can I get your WebRTC signaling adress for testing?

**Comment by mpisat** [comment]
> No. Firefox should have to work fine too. Basic playback with OME via firefox works fine on my enviroment. Can I get your WebRTC signaling adress for testing?

I suspected from double nat under Dockerproxy. 

My previous docker run command was this:
docker run -d --restart always --env OME_ICE_CANDIDATES=*:10000-10005/udp -p 1935:1935 -p 3333:3333 -p 8080:8080 -p 9000:9000/udp -p 10000-10005:10000-10005/udp airensoft/ovenmediaengine:latest

I added external IP and now it's working on Firefox

docker run -d --restart always --env OME_ICE_CANDIDATES=165.x.x.x:10000-10005/udp -p 1935:1935 -p 3333:3333 -p 8080:8080 -p 9000:9000/udp -p 10000-10005:10000-10005/udp airensoft/ovenmediaengine:latest

if I don't add --env OME_ICE_CANDIDATES=165.x.x.x:10000-10005/udp and expect it to use internal values, it doesn't work on Firefox (double nat issue due to docker?)

**Comment by SangwonOh** [comment]
@mpisat Hi. We just strengthen the connectivity with OME running on private network like a docker proxy.

updated #133 commit.
