### ISSUE TITLE
Hello, AirenSoft team.

### ISSUE THREAD

**Issue by KIM-IN-KYUM** [AirenSoft/OvenPlayer#130]
Can you let me know about autoplay .html sample?
My html text is...
    <script>
        var player = OvenPlayer.create("player", {autoStart:true},
                sources: [
                {
                        "file": "ws://0.0.0.0/app/stream_o",
                        "type": "webrtc"
                }
                ]
                },);

        hljs.initHighlightingOnLoad();
But doesn't working....
I'm beginner. Help me.

**Comment by SangwonOh** [comment]
Hi. Please try this code. Good luck.

```javascript
var player = OvenPlayer.create("player", {
    autoStart: true,
    sources: [
        {
            "file": "ws://0.0.0.0/app/stream_o",
            "type": "webrtc"
        }
    ]
});
```

**Comment by KIM-IN-KYUM** [comment]
Thanks a lot. Same problem. But Doesn't working.
I've installed brand new version.
Test in chrome web.

**Comment by SangwonOh** [comment]
Hi. Do your playback working by clicking play button? If it is, it may not auto playback because of auto playback policy of browser. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes?hl=ko

**Comment by KIM-IN-KYUM** [comment]
> Hi. Do your playback working by clicking play button? If it is, it may not auto playback because of auto playback policy of browser. https://developers.google.com/web/updates/2017/09/autoplay-policy-changes?hl=ko

Thank you.
