### ISSUE TITLE
Auto-refresh when streaming is not started...

### ISSUE THREAD

**Issue by alissimo** [AirenSoft/OvenPlayer#132]
I'm using webrtc and it works well...
Only one thing: if I go to the page with the oven player, but my friend has not started the streaming from OBS->OvenMediaEngine, the player says: "Connection with low-latency(OME) server failed." 
After that, if my friend starts streaming from OBS, shouldn't the player start to show video alone automatically? Instead I have to refresh the page (but I don't know when my friend streaming will start... so I have to refresh many times...?!? )
Is it normal?

**Comment by SangwonOh** [comment]
@alissimo HI. Instead of refreshing browser, you can periodically reload OvenPlayer until stream is provided. We are using this technique at demo.ovenplayer.com

```javascript
var ovenPlayer = null;

function loadOvenPlayer () {

    if (ovenPlayer) {

        ovenPlayer.destroy();
    }

    ovenPlayer = OvenPlayer.create({/*your_options*/});

    // Reload OvenPlayer when error occured.
    ovenPlayer.on('error', function () {

        // Wait 1 sec and relaod.
        setTimeout(function () {

            loadOvenPlayer();
        }, 1000)
    });
}

loadOvenPlayer();
```

**Comment by 0xARK** [comment]
So what is the purpose of the "autoStart" option ?

https://airensoft.gitbook.io/ovenplayer/initialization#autostart

**Comment by morbificagent** [comment]
Hi there, i am trying to implement this as my config looks like this at the moment:

![Anmerkung 2020-07-29 112843](https://user-images.githubusercontent.com/50199132/88783106-b0cce280-d18e-11ea-8e53-78e2b988e0de.png)

But as i am not good in such coding-things i missed something as i only get  this inside of the browser:

![image](https://user-images.githubusercontent.com/50199132/88783306-e376db00-d18e-11ea-86ea-5023b938d7f0.png)

Could someone assist?

**Comment by SangwonOh** [comment]
@morbificagent Hi. try `ovenPlayer.remove();` instead `ovenPlayer.destroy();`

**Comment by morbificagent** [comment]
Found it some minutes ago in the doc too ;-)

Thanks for helping

**Comment by SangwonOh** [comment]
Close the issue. Please reopen if you need more discussion.
