### ISSUE TITLE
Access to OME via Player behind Firewall

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenPlayer#139]
Hi @ all,

at the moment we are trying to use your great product in a test-environment and after some small problems it is working great now.
For Home-Users which want to view the livestream (without outgoing firewall restrrictions) everything is working. But Users which are behind a company firewall it isnt working.

Its because several ports are blocked like 3334 tcp and most of the udp-ports. So they get "no connectin to OME".
As we cant say to them "ask your it-department for reconfigure the company firewall" its not possible for them to use it.

Is there a solution for that? Some sort of Reverse-Proxy or  something like that?

**Comment by morbificagent** [comment]
OK, i was searching a little bit and it looks like im needing a turn server. So im installed coturn on the same public server as ome...

Hopefully this is the right way.
But if it is, how do i say OvenPlayer to use it?

**Comment by morbificagent** [comment]
Even if im not sure if its the right way im on i have tried to set it up:

![image](https://user-images.githubusercontent.com/50199132/88797485-b254d580-d1a3-11ea-9690-bed7f34a46e2.png)

But when i take a look at the firewall i only see blocked conectionattempts on port 3334..... Hmmmmmm.... nothing changed with this config.

Someone here who can help with this?

**Comment by SangwonOh** [comment]
@morbificagent Hi. The 3334 port is used for signaling with the OME via WebSocket connection.  The turn server is not helpful for this situation. If your network blocks port that the turn server uses, it is difficult to streaming also. 

In this case, you can change the ports that OME uses by OME configuration. How about change the OME ports to your firewall is not blocking.

Check out this documentation. https://airensoft.gitbook.io/ovenmediaengine/configuration#bind

**Comment by morbificagent** [comment]
This would be a possibility for me of course, but as our customers most are behind company firewalls too its no solution for them as they cant change or know their firewall settings.
Mostly only 80 and 443 tcp are allowed and http proxies are used.

Im not firm in the possibilities of WebRTC but as we are using some tools based on it like jitsi, spreed,...  there seems to be a way dealing with this scenario as no customer has a problem using them through their firewalls.

**Comment by SangwonOh** [comment]
@morbificagent I've researched jitsi, spreed. I think these tools are also need to be firewall configured. 
And Because of this issue is not activating long time,  this issue is going to be closed at the some days later.

We hope your project is successful.

**Comment by morbificagent** [comment]
@SangwonOh:

I have researched a little bit too and have minimized the need of configuring the firewall as "Stream-Viewer" to a minimum by:

- Changing the signaling port to 443 in OME + Player
- Setting up a TURN-Server with TLS (Port 443) and changing the Playerconfig too

So i only need 443 opened in the firewall :-)


My Player-Config looks like this now:


`
let webrtcSources = [{type : "webrtc", file : "wss://xxxxxx.xxxxx.de:443/app/live_720p-5Mbit", label : "720P-5Mbit"}, {type : "webrtc", file : "wss://xxxxxx.xxxxx.de:443/app/live_720p-8Mbit", label : "720P-8Mbit"}, {type : "webrtc", file : "wss://xxxxxx.xxxxx.de:443/app/live_720p-2Mbit", label : "720P-2Mbit"}]
`

...

    ovenPlayer = OvenPlayer.create("ovenPlayer", {
            autoStart : true,
            controls : true,
            sources: webrtcSources,
                webrtcConfig: {
                        iceServers: [
                        {
                                "urls": [
                                        "stun:turn2.xxxxx.de:3478"
                                        ]
                        },
                        {
                                "urls": [
                                        "turn:turn2.xxxxx:3478",
                                        "turns:turn2.xxxxx:443?transport=tcp"
                                        ],
                                        "username":"xxxxx",
                                        "credential":"xxxxx"
                        }
                        ]
                }

             });

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
