### ISSUE TITLE
modify player to get multi webrtc streaming.

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenPlayer#140]
modify player to get multi webrtc streaming once
Do you have any idea?
Where should I start?

**Comment by SangwonOh** [comment]
@jys923 Hi. I wonder What actually means "get multi webrtc streaming once"?

Did you mean ?
1. Get the multiple streams and plays them on one screen at the same time.
2. Get the multiple streams and plays one of them by selecting stream.

**Comment by jys923** [comment]
This is the case when one of several streams is played on one screen, and multiple streams are played simultaneously when selected.

**Comment by SangwonOh** [comment]
@jys923 Hi. How about loading multiple OvenPlayer that playbacks one angle and layouting the players as you want?

**Comment by KIM-IN-KYUM** [comment]
I think one ovenplayer make's multi video layout.
Main video and side multi other video. Click side video change  to main video.
Can do that?

**Comment by jys923** [comment]
thank's for answer
client want like this
![2020_08_18 오후 1_03 Office Lens](https://user-images.githubusercontent.com/18624102/90469304-6cac7c80-e153-11ea-9032-d9a36d8f08cc.jpg)

**Comment by jys923** [comment]
> I think one ovenplayer make's multi video layout.
> Main video and side multi other video. Click side video change to main video.
> Can do that?

i can not understand.
can you talk more detail?

**Comment by jys923** [comment]
> thank's for answer
> client want like this
> ![2020_08_18 오후 1_03 Office Lens](https://user-images.githubusercontent.com/18624102/90469304-6cac7c80-e153-11ea-9032-d9a36d8f08cc.jpg)



> @jys923 Hi. How about loading multiple OvenPlayer that playbacks one angle and layouting the players as you want?

#thank's for answer
client want like this
![2020_08_18 오후 1_03 Office Lens](https://user-images.githubusercontent.com/18624102/90469304-6cac7c80-e153-11ea-9032-d9a36d8f08cc.jpg)

**Comment by SangwonOh** [comment]
Hi. Please note that one player cannot play multiple streams at once.

**Comment by getroot** [comment]
This is obviously not the player's role. This is the role of the web application. You can make this with 4 players, or use another method.

**Comment by jys923** [comment]
> Hi. Please note that one player cannot play multiple streams at once.

I know..
So I have to modify ovenPlayer.
Direction of Approach Oven Player I ask you where to start researching.

**Comment by SangwonOh** [comment]
https://github.com/AirenSoft/OvenPlayer/blob/a9498ef8efc106d161ddc7182ba57c5ec5e903bb/src/js/api/media/Manager.js#L120 which create and manage html video elementcan be the starting point to modify the player to manage multiple video elements . But adding video elements in one OvenPlayer needs huge codes to implement.  Closing this issue. By policy, one OvenPlayer plays one stream at the same time, so we can't support any additional features you want to implement.
