### ISSUE TITLE
Change Text on connection error

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenPlayer#141]
Hi Together,

is it possible to change the text which is displayed when there is an error like:

![image](https://user-images.githubusercontent.com/50199132/89291944-b8432e80-d65b-11ea-9df6-356ab366c197.png)

This one is shown when nothing is streamed but showing an errormessage on a publishing website results in panic by the enduser ;-)

**Comment by SangwonOh** [comment]
@morbificagent Hi. You can see the whole messages that matched error code at here https://github.com/AirenSoft/OvenPlayer/blob/master/docs/api.md#systemtext

You can create new entire system language, but also overwrite the error message what you want to. This is simple code.

```javascript
var player = OvenPlayer.create("player_id", {
    sources: testSource
});

player.on('ready', function () {
    player.getConfig().systemText.api.error[302].message = 'The message what you want.';
});
```

**Comment by morbificagent** [comment]
Great, thanks this is working.

Is it possible to remove the exclamation mark symbol too as it indicates "there is an error"?

**Comment by SangwonOh** [comment]
@morbificagent Hi. How's your working going on? Sorry for the late response. You can simply delete the exclamation mark symbol by using css.

```stylesheet
i.op-con.op-warning::before {
    display: none;
}
```

**Comment by morbificagent** [comment]
@SangwonOh Hey there, its working great. at the moment i am playing with the design of the publishing website but ovenplayer and ome are working great on it :-)

Thanks for your halp and keep on rocking!

**Comment by SangwonOh** [comment]
Close the issue. Please reopen if you need more discussion.
