### ISSUE TITLE
Hardcoded DNS Server

### ISSUE THREAD

**Issue by larssorenson** [AirenSoft/OvenPlayer#142]
Hey,

It looks like the JavaScript player hard codes to use dns.google.com to resolve the backend server:

https://github.com/AirenSoft/OvenPlayer/blob/d74cd4ee5ef01fbf56413f2fd4059eac201a0af0/src/js/api/provider/html5/providers/WebRTCLoader.js#L370

As well as a hard-coded google STUN server:

https://github.com/AirenSoft/OvenPlayer/blob/d74cd4ee5ef01fbf56413f2fd4059eac201a0af0/src/js/api/provider/html5/providers/WebRTCLoader.js#L23

This makes the player unusable when users have Google sources/domains blocked.

It would be nice if this could be configured or bypassed without having to ad-hoc patch the JavaScript.

Thanks

**Comment by getroot** [comment]
Very good idea! We will update this.

**Comment by SangwonOh** [comment]
@larssorenson Hard coded google STUN server was removed. User can be able to set any STUN server if they need with player configuration.
And also dns.google.com can be bypassed with player configuration. But we've not removed DNS resolving feature using google DNS resolving service. For, OvenPlayer resolves DNS using google's service by the default and if user want to resolve DNS by their methods, bypass auto resolving and set the WebRTC connection URL with their resolved DNS.
