### ISSUE TITLE
How to clean install?

### ISSUE THREAD

**Issue by KIM-IN-KYUM** [AirenSoft/OvenPlayer#143]
I wanna remove old version and brandnew install OME.

Yum doesn't working on Centos 7.

how to remove?

**Comment by SangwonOh** [comment]
Hi. You can find out installation issues about OME on the CentOS at https://github.com/AirenSoft/OvenMediaEngine/issues?q=centos .

If you can't solve the problem, please open an issue in https://github.com/AirenSoft/OvenMediaEngine/issues with detailed explanation about your situations.

Thanks.

**Comment by KIM-IN-KYUM** [comment]
Sorry this is player issue Thank you.
