### ISSUE TITLE
About ads

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#145]
Hi, Docs ads not Say a lot,  does it can show popups every x time ??? How can i do it ir it can??? As i told You the doc not Say a lot.

Thanks and go on

**Comment by getroot** [comment]
I can't understand exactly what you want. But obviously, OvenPlayer supports VAST ads, and what you want to do with VAST. Research VAST through the following URL.

https://www.iab.com/guidelines/digital-video-ad-serving-template-vast/

**Comment by alnux** [comment]
instead of use VAST that have to be config, add a simple image pop up with a close button, how can i wiil do it??? becouse the docs just say VAST compatible

**Comment by getroot** [comment]
It is not a function of the player. You have to implement it as a function of a web page.
