### ISSUE TITLE
Update package.json and publish to NPM

### ISSUE THREAD

**Issue by banagale** [AirenSoft/OvenPlayer#148]
Thanks for this work and OME. It would be more convenient if this package was available on the npm directory.

I did a test of npm publish, and currently it fails due to:

```
npm ERR! 404  'OvenPlayer@0.9.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
```

Do you have availability to do this? 

If not, let me know and I can have a go at making the package.json changes necessary and doing a publish, then handing over ownership to your team.

**Comment by SangwonOh** [comment]
@banagale Hi. We've not tried npm packaging yet. We will have detailed research to make the OvenPlayer to the Nodejs module.
And, of course, your contributions are always welcome.

**Comment by banagale** [comment]
Okay, cool. 

I had a preliminary attempt at publishing it and was not successful. I wasn’t able to import components into React as expected. 

So I have registered the ovenplayer namespace.  I am prepared to transfer ownership of that to your team, just let me know the username(s). 

In the meantime if I can figure out necessary changes, I’ll create a PR.

**Comment by SangwonOh** [comment]
For getting information. Is the namespace you've registered  https://www.npmjs.com/package/ovenplayer ?

**Comment by banagale** [comment]
@SangwonOh yes. Happy to turn it over to you when you are ready.

**Comment by SangwonOh** [comment]
@banagale Hi. Long time no see. I am ready for to do this.

How do we transfer the package repository?

Should we delete the ovenplayer npm repository you have created and then proceed with our new registration?

**Comment by banagale** [comment]
@SangwonOh Happy to oblige.

I would delete it so you can start fresh, although it appears you can not unpublish something older than 72 hours. If it is, I am not sure it will allow the namespace to be re-occupied. If you find a process to do so and would prefer this, just point me at it.

Otherwise, I would be happy to simply make you the admin of the package. You can drop me if you like. If this works, would you please a link to your npmjs profile and I will make you admin?

**Comment by SangwonOh** [comment]
@banagale Hi. Let's try last option you've said.

https://www.npmjs.com/~airensoft

That's our npm profile.

Thank you so much your contributing.

**Comment by banagale** [comment]
@SangwonOh I've invited that name.

Really, I did nothing but squat the name. 

Thank you very much for your work on ovenplayer.

**Comment by ohsangwon777** [comment]
@banagale . Thanks

And please do the step 4 of this link. I've tested this on my private accounts. This procedure gives me access to the settings panel.

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-website

**Comment by SangwonOh** [comment]
@banagale . Thanks

And please do the step 4 of this link. I've tested this on my private accounts. This procedure gives me access to the settings panel.

https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account#transferring-a-package-from-a-user-account-to-another-user-account-on-the-website

**Comment by SangwonOh** [comment]
@banagale 

> And please do the step 4 of this link. I've tested this on my private accounts. This procedure gives me access to the settings panel.

You didn't have to do that procedure if you still want to stay as a maintainer :)

From now on I will improve the structure of OvenPlayer.

1. Enable require('ovevnplayer')
2. Dependency structure improvement
3. package.json improvement

Thanks very much.

**Comment by banagale** [comment]
No problem, I couldn't remove myself until you had accepted. I've done that step now.

I appreciate the offer to hold on to the status, and I am hoping to offer contribution. However I am at ease with releasing maintainership to your team. 

If I end up making contributions on some regular basis and it looks like I could offer help being re-elevated to maintainer then I would be open to that.

Though, as is I have my hands full right now.

There is also a good security case for me not having the ability to perform releases. I think it is best that at least from the start your trusted team has complete control of code in the package.

Again, your team has done great work with oven media engine good luck with your continued progress.
