### ISSUE TITLE
cant translate

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#151]
Hi, i get your change language script from github but i get a error on console

ovenplayer.js:2 Uncaught TypeError: Cannot read property 'api' of undefined
    at Object.t.init (ovenplayer.js:2)
    at Object.s.create (ovenplayer.js:2)
    at Object.u.create (ovenplayer.js:2)
    at player.php:14

it say as you can see, cant read api property

**Comment by SangwonOh** [comment]
@alnux Hi. Can I get some source code you've tried? Also please check all the strings you've translated are safely escaped.

**Comment by SangwonOh** [comment]
@alnux I am closing this issue due to long inactivity. If you need further discussion, please reopen. Thanks.
