### ISSUE TITLE
oven webrtc player to react player

### ISSUE THREAD

**Issue by ljg96** [AirenSoft/OvenPlayer#152]
Is there any way to create react player with this webrtc player?

https://github.com/CookPete/react-player
It is necessary for a variety of compatibility.

**Comment by SangwonOh** [comment]
@ljg96  Integrating with the react-player is a further story. Before that we are preparing to convert OvenPlayer to the React Component. And then we are hoping to you will use the React OvenPlayer. Thanks.

**Comment by llspalex** [comment]
Is there any update on the React Ovenplayer?
