### ISSUE TITLE
Synchronize the playback time

### ISSUE THREAD

**Issue by codihaus** [AirenSoft/OvenPlayer#153]
Hello,

With Oven Player, can we synchronize the playback time between the server (or the backend admin), where I will send the web socket signal every 1s to the connected client, to let them know we're at the second of 59, and the client will update accordingly?

Why I ask this since I want, at the time of 60, on every client connected, I will show a message.

But the user's connectivity might be different, the delay between each client might be +-5 seconds, maybe.

So, depending on an admin view, where the player is playing 60s, we will send a signal contains a message to the client.

Then the client's time meets the 60s, it will show the message.

Could we achieve this?

Thank you!

**Comment by SangwonOh** [comment]
@codihaus Hi. Unfortunately, The OvenPlayer does not support synchronize the playback. Thanks.

**Comment by SangwonOh** [comment]
@codihaus I am closing this issue due to long inactivity. If you need further discussion, please reopen. Thanks.
