### ISSUE TITLE
Chrome and Safari WebRTC Stereo Audio Downmix To Mono

### ISSUE THREAD

**Issue by S3-sim** [AirenSoft/OvenPlayer#155]
Hi,

During testing, we noticed that WebRTC stereo audio is being downmixed to mono within chrome and safari. Firefox is working as expected. It appears that the issue is related to this open issue (https://bugs.chromium.org/p/webrtc/issues/detail?id=8133). I believe they also outline a potential work around in the thread.

Not sure if this belongs in the player repo or the ovenmediaengine repo. Please let me know if you want me to move this issue.

**Comment by SangwonOh** [comment]
@S3-sim Hi. We are investing this issue with OvenMediaEngine team.

**Comment by SangwonOh** [comment]
Applied at 17ec265131457817d6f54a24ca05b4e0e3f81b13. Thank!!
