### ISSUE TITLE
Customize Player Question

### ISSUE THREAD

**Issue by kpdillon** [AirenSoft/OvenPlayer#157]
Hi -

I am really excited about this technology! I am using it to deliver real time live video in a school without needing VLC! This is absolutely perfect because teachers have Smartboards with an HTML5 browser.

I am using the following code in the player but when I am not sending RTMP traffic to it, the player displays the message Connection with low-latency(OME) server failed with a exclamation point in a triangle.

How might I modify this script to suppress this message in favor of a simple play button?

<script> let player = OvenPlayer.create("player", { autoStart: true, mute: false, title: "Bulldog Livestream Player (offline)", controls: true, currentProtocolOnly: true, sources: [ { host : 'ws://192.168.8.12:3333', application : 'app', stream : "stream", label : "WebRTC 1080P" } ] }); </script>

**Comment by SangwonOh** [comment]
@kpdillon Hi.

In the state of "Not sending RTMP traffic to the OME"

I wonder if you are trying to show only the play button. In that case, if users press the play button, they still can't start playback because of no input stream.

Instead of showing the play button only, How about change the message "Connection with low-latency(OME) server failed" to something like "Waiting for live streaming."

This is how to do it.
```
 let player = OvenPlayer.create("player", { autoStart: true, mute: false, title: "Bulldog Livestream Player (offline)", controls: true, currentProtocolOnly: true, sources: [ { host : 'ws://192.168.8.12:3333', application : 'app', stream : "stream", label : "WebRTC 1080P" } ] });

player.on('ready', function () {
    player.getConfig().systemText.api.error[501].message = 'Waiting for live streaming.';
});

```
Thanks.

**Comment by kpdillon** [comment]
Thank you!  This worked!  Is there a way to hide or replace the triangle graphic?

**Comment by SangwonOh** [comment]
@kpdillon Hi.

You can simply hide triangle graphic using css on your application.

```css
i.op-con.op-warning::before {
    content: '';
}
```

Or replace the graphic
```css
.op-message-box .op-message-container .op-message-icon i.op-con {
    /* set dimension */
    width: 60px;
    height: 60px;
}

i.op-con.op-warning::before {
    /* set replacement image */
    content: url('http://dev.airensoft.com/~pub/ovenplayer-web/heart-box.png');
}
```

Thanks

**Comment by natzakaria** [comment]
How do I change the text shown here with something else?
![Screenshot 2021-11-20 at 6 50 55 AM](https://user-images.githubusercontent.com/65059352/142701305-98cc12f6-179f-4835-9890-70ee10445abc.jpg)

**Comment by command-tab** [comment]
I see it in the source here:
https://github.com/AirenSoft/OvenPlayer/blob/36449468b40cf0e41eccbb6a2a1301c8e372e80a/src/js/api/constants.js#L262

**Comment by SangwonOh** [comment]
@natzakaria Hi. As shown above there is way to change text at the runtime. In your case

```javascript
var player = OvenPlayer.create('player', {
    sources: [
        {
            type: 'websocket',
            file: "ws://your_url"
        }
    ]
});

player.getConfig().systemText.api.error[511].message = 'Your message';
```

You can reference all the message codes in the source code shared by @command-tab (thanks!)

**Comment by zcolor** [comment]
> @kpdillon Hi.
> 
> In the state of "Not sending RTMP traffic to the OME"
> 
> I wonder if you are trying to show only the play button. In that case, if users press the play button, they still can't start playback because of no input stream.
> 
> Instead of showing the play button only, How about change the message "Connection with low-latency(OME) server failed" to something like "Waiting for live streaming."
> 
> This is how to do it.
> 
> ```
>  let player = OvenPlayer.create("player", { autoStart: true, mute: false, title: "Bulldog Livestream Player (offline)", controls: true, currentProtocolOnly: true, sources: [ { host : 'ws://192.168.8.12:3333', application : 'app', stream : "stream", label : "WebRTC 1080P" } ] });
> 
> player.on('ready', function () {
>     player.getConfig().systemText.api.error[501].message = 'Waiting for live streaming.';
> });
> ```
> 
> Thanks.

I want to hide the message entierly, because I'm using a custom image while nothing is playing so I left the **message = 'xx'** blank, however there's still a darker background even without any message. Can I hide that too?

**Comment by SangwonOh** [comment]
@zcolor Hi. Please try putting this simple css into your page. This css hides the messages and icons the player shows.

```css
.op-message-container {
    display: none;
}
```

**Comment by zcolor** [comment]
Thanks! That did the trick
