### ISSUE TITLE
Player is referred as "openplayer" in a couple of places

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#158]
Hi! I've noticed that the player is referred to as "openplayer" in a couple of places (for instance, [package.json](https://github.com/AirenSoft/OvenPlayer/blob/master/package.json#L5) and here in the [contributing guide ](https://github.com/AirenSoft/OvenPlayer/blob/a9498ef8efc106d161ddc7182ba57c5ec5e903bb/CONTRIBUTING.md) it says the files will be in a `openplayer` folder) and I'm wondering if this is a mistake, if so I'd be glad to submit a pull request to fix those

**Comment by SangwonOh** [comment]
@hernanrz Hi. Thank you very much for your reporting typo. We would be very grateful if you could create PR.

**Comment by hernanrz** [comment]
Thank you for your response, I've opened a pull request #159

**Comment by SangwonOh** [comment]
@hernanrz Thank you for you'r contributing 👍
