### ISSUE TITLE
Ability to set custom video poster

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#161]
Hello! Is there any way to set a custom poster for the player (basically an image that is displayed before the play button is clicked), similar to how in videojs you can do `myPlayer.poster("http://mysite.com/img/poster.jpg")`? Is that a feature that could be added eventually?

**Comment by SangwonOh** [comment]
@hernanrz Hi. You can simply add poster using `image `option.

For example
```javascript
    var playerInstance = OvenPlayer.create("player", {
        image: 'https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png',
        sources: [
            ...
        ]
    });
```
