### ISSUE TITLE
how can i put hls params??

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#162]
**hi i have the next ovenplayer file**

```
<!doctype html>
<html lang="es">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="Access-Control-Allow-Origin" content="*">
    <meta http-equiv="cache-control" content="max-age=0"/>
    <meta http-equiv="cache-control" content="no-cache"/>
    <meta http-equiv="expires" content="0"/>
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/hls.js/0.15.0-alpha.2/hls.min.js"></script>
    <script src="./libs/js/ovenp/ovenplayer.js"></script>
    <title>Tribu510 - Streamer</title>
  </head>
  <body style="margin: 0 auto;">
    <div id="player"></div>
<script>
player = OvenPlayer.create("player", {
    sources: [{
        file: "https://mydomain.com/vivo/235ebcb6eb18d3f/index.m3u8",
        type: "hls",
        framerate : 25
    }]
});

</script>

  </body>
</html>
```
how can i add hls.js params like 

**initialLiveManifestSize**
**maxBufferLength**
**maxBufferSize**

Could you help me with and example, thanks. By the way i ask this becouse my player frezze after load first segement of ts, if you know how to fix these please help me witha an example .
really really thanks

**Comment by SangwonOh** [comment]
@alnux Hi.

To set hls.js options. You can simply define the `Hls.DefaultConfig` before create OvenPlayer.

```javascript

Hls.DefaultConfig.initialLiveManifestSize = 3;

player = OvenPlayer.create("player", {
    sources: [{
        file: "https://mydomain.com/vivo/235ebcb6eb18d3f/index.m3u8",
        type: "hls"
    }]
});
```

**Comment by SangwonOh** [comment]
@alnux Hi.

We also added a function to set hls config when initializing OvenPlayer.

```javascript
var player = OvenPlayer.create("player", {
    sources: [
        {
            type: 'hls',
            file: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
        }
    ],
    hlsConfig: {
        initialLiveManifestSize: 3,
        maxBufferLength: 20,
        maxBufferSize: 60
    }
});
```

**Comment by alnux** [comment]
Thanks for it but i Saw that hls.js has some problems streaming at least is My case. What happend... Mmm .. ok after maybe 30 seconds it frezze and stay loading.  i have to reload the page to it work.. so i decided search another player without hls.js and find viblast player that works really good....and it can work with vídeo.js. i like ovenplayer but the way i changed to viblast is becouse hls.js maybe has bug

**Comment by SangwonOh** [comment]
@alnux Long time no see. Also check out the latest HLS.js. And we also added a parameter to set all settings in hls.js to the latest OvenPlayer.
- https://airensoft.gitbook.io/ovenplayer/initialization#hlsconfig

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
