### ISSUE TITLE
errors on loading player

### ISSUE THREAD

**Issue by includeamin** [AirenSoft/OvenPlayer#163]
Hi,
Loading player on Chrome faced this error
js console:
![image](https://user-images.githubusercontent.com/11836741/99704446-a6bc5000-2aad-11eb-9703-d739076c351d.png)

Player UI
![image](https://user-images.githubusercontent.com/11836741/99704562-cb182c80-2aad-11eb-830e-15d30a1e5de3.png)

any idea?
thanks.

**Comment by SangwonOh** [comment]
@includeamin Hi. What OS are you running?

Recently we found a similar issue on MacOS 11. And fixed the issue at https://github.com/AirenSoft/OvenPlayer/commit/b51a257bd7cef8a6844ab1231f14bc6b92c99e3d

How about try again using most recent OvenPlayer.

Thanks.

**Comment by includeamin** [comment]
`@includeamin Hi. What OS are you running?` : I'm using mac os big sur [11.0.1] and some of my clients have this issue on ios chrome
`How about try again using most recent OvenPlayer`: sure, I will try.
thanks

**Comment by includeamin** [comment]
the last release of OvenPlayer rep has the same issue [mac os Big Sur]
![image](https://user-images.githubusercontent.com/11836741/99783932-52a67f80-2b30-11eb-87f1-b515f525f455.png)

**Comment by includeamin** [comment]
on master branch this issue not exist anymore.
thanks
