### ISSUE TITLE
WebRTC in Opera  does not work

### ISSUE THREAD

**Issue by Alexufo** [AirenSoft/OvenPlayer#164]
Opera 72.0.3815.378
Player from http://demo.ovenplayer.com

I have a success with dash and hsl but webrtc  does not work.
![2020-11-21_08-14-58](https://user-images.githubusercontent.com/1562329/99868305-76220680-2bd2-11eb-9a54-ba4477d50a60.jpg)

I suppose should not be a problem. Opera  used chromium

**Comment by getroot** [comment]
It may not be a player issue.

Check the firewall of the server where OvenMediaEngine is installed. Or, the WebRTC URL you entered may be incorrect. What URL did you try to play with? Have you run OvenMediaEngine with default settings? If so, did you properly enter the 3333 port in the URL like this? ws://host:3333/app/stream

It may be helpful if you read the following article more closely.

https://airensoft.gitbook.io/ovenmediaengine/getting-started

**Comment by Alexufo** [comment]
I tested on Crome 84, FF 85.0a1 and latest Opera. webrtc works on all except Opera.

I share url (thanks for player settings as url get params)  between browsers. hsl,dash,webrtc works on Crome and FF. 

But in Opera I see black screen on webrtc option. (I open page in private mode to except opera plugins influence. Errors was gone, just black screen  with timeless loading)  I use default docker container.

**Comment by getroot** [comment]
I have no experience with the Opera browser.
But if you're experiencing the problem you're talking about, it's likely that Opera doesn't support h.264. What codecs does Opear support in WebRTC? Try adding and testing the vp8 encoding option in ome to clarify the problem.

**Comment by Alexufo** [comment]
Oh! I open Opera settings on WebRTC settings.

I changed "Disable unproxied UDP" to recommended. Maybe I did it in past!
![image](https://user-images.githubusercontent.com/1562329/99893368-446f7500-2c90-11eb-949e-2e66a9a8d847.png)

Now it works!
