### ISSUE TITLE
dash->webrtc no autoplay

### ISSUE THREAD

**Issue by Alexufo** [AirenSoft/OvenPlayer#165]
I test player and and found that after changing dash to web rtc source autoplay does not working. I need press play button.
But 
webrtc->dash works well.
dash->webrtc - not

**Comment by SangwonOh** [comment]
@Alexufo Hi. Thank you for contributing. We have identified this issue and will try to fix it soon.

**Comment by SangwonOh** [comment]
@Alexufo This issue resolved at 8c7b4a76818f775b2f8e9e53ab93f5b48dd737e1. Please check it out with latest OvenPlayer. Thanks.
