### ISSUE TITLE
webrtc not work on ovenplayer over safari 11.1.2

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#166]
hi there the player cant load webrtc signal over safari 11.1.2. im using your demo.ovnplayer.com and when i try to play over safari it loading for a long time without play, here a ss.
https://prnt.sc/vujne3

whit hls it play without problems

**Comment by getroot** [comment]
Plz upload your Server.xml of OvenMediaEngine, and your Encoder codec setting.

**Comment by alnux** [comment]
I'm using the example Server.xml that comes with OME. Could You haré the One that is no demo OME please

**Comment by SangwonOh** [comment]
@alnux Hi. Did you succeed in playing the webrtc? Is there any progress?

**Comment by alnux** [comment]
hi there, well i found something, to stream im using Wirecast and there is 2 options of 264codec and with 264x works normally on safari but if change it to other one H264 (i think that it is, sorry im not on my computer) does not work

**Comment by SangwonOh** [comment]
Closed because this is an issue that is out of scope for OvenPlayer.
