### ISSUE TITLE
Google Cast support (Chromecast), particularly for (low latency) WebRTC stream

### ISSUE THREAD

**Issue by julian-w** [AirenSoft/OvenPlayer#167]
Hello,

would it be possible to implement a Google Cast button, so that we can stream the video to a Chromecast device. Especially a low latency function using WebRTC would be great. I have not yet been able to find a solution to play a stream with low latency on a Chromecast.

Thank you!

Best regards,
Julian

**Comment by SangwonOh** [comment]
@julian-w Hi. We are not trying to support Chrome cast right now. We think this is a nice feature. We will discuss closely and schedule whether to support Chrome Cast.

It would be nice to use the Chrome browser's transfer function and give us feedback. (https://support.google.com/chrome/answer/3228332)

**Comment by nangavar** [comment]
I have tried with Chrome browser streaming to Chromecast and it worked fine. It adds some delay. It would be great to support Chromecast directly from the player.

Nice feature!
Matias

**Comment by Byskoven62** [comment]
Any news about Google Cast function?

**Comment by SangwonOh** [comment]
We are not planning a Chromecast implementation yet. We will close this issue and let you know if Chromecast functionality is implemented.

**Comment by basisbit** [comment]
+1 for chromecast support request.
