### ISSUE TITLE
webrtc does not work on yandex browser (chrome)

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#168]
hi, it is very strange, when i load the page with the player the webrtc does not work, below a screenshot of browser error
https://prnt.sc/w5112i

**Comment by SangwonOh** [comment]
@alnux Hi. We've tested the WebRTC stream on the yandex browser. But It seems it worked fine. Does it work in chrome browser in the same situation? Is it possible that there is a problem with the network connection between the player and OME? 
It would be helpful if you let us know more details.

**Comment by alnux** [comment]
Hi, maybe is My computer becouse i have yandex browser on Mobile device and another Mac and it works normally as You say

**Comment by kpdillon** [comment]
It doesn't load on a Mac in Big Sur in Chrome anymore.  I've tested this on a couple of computers now, it seems something has changed with Big Sir and how it runs Chrome.

**Comment by alnux** [comment]
Big Sur ???? What You want to Say???

**Comment by kpdillon** [comment]
https://www.apple.com/macos/big-sur/

**Comment by SangwonOh** [comment]
@kpdillon Hi. There was the issue OvenPlayer can not be initialized on Big Sur. It solved at b51a257bd7cef8a6844ab1231f14bc6b92c99e3d. Could you check again with latest OvenPlayer?

**Comment by SangwonOh** [comment]
Close this issue due to long inactivity. Please reopen for further discussion.
