### ISSUE TITLE
Disable contextual menú over screen player

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#170]
Hi, i was looking on Docs and i can't find how disable contextual menú ( right click) over screen player where show help. Can You help me with this please.

Really really thanks.

**Comment by SangwonOh** [comment]
@alnux Hi. It's very unfortunate, but we don't support that feature. Because that context menu is the only one place that shows 'OvenPlayer' text.  Are there any strong reasons for wanting this feature?

**Comment by alnux** [comment]
Yap, I wanted to add a link to another page that has the player and a chat

**Comment by SangwonOh** [comment]
@alnux Hi. We suggest that you'd better implement that feature using external UI. Thank you.
