### ISSUE TITLE
Play RTMP stream with VLC but not OMP

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenPlayer#171]
I have an rtsp stream, I can play it with VLC but the OvenPlayer demo says "Can not load due to playable media not found."

**Comment by getroot** [comment]
RTMP? RTSP? Please check which one.
RTSP is not supported by OMP. RTMP is a problem caused by the end of Flash support and no longer loading in the browser. You can no longer use RTMP in any web browser.

**Comment by IanMitchell77** [comment]
RTMP.

Why are RTMP files in the source?

It'd be good if the documentation says similar. The README.md says "And, it automatically plays and fallbacks using WebRTC, Low Latency HTTP (DASH), MPEG-DASH, HLS, and **RTMP**."

https://airensoft.gitbook.io/ovenplayer/#quick-start mentions RTMP.

The example at https://airensoft.gitbook.io/ovenplayer/examples/playlist mentions RTMP which is where I copied it from.

**Comment by SangwonOh** [comment]
@IanMitchell77 Thanks for reporting. Because of the RTMP is no longer supported, so we will delete about playing the RTMP from the documentation.

**Comment by getroot** [comment]
But I am still worried.
Some people using older browsers below IE 11, such as IE 9, still need RTMP. Of course, the manual needs to be accurately written about the limitations of RTMP, according to your opinion.
