### ISSUE TITLE
Dist folder has 65MB of mp4 videos

### ISSUE THREAD

**Issue by GregOriol** [AirenSoft/OvenPlayer#174]
Currently, the dist folder contains what looks like sample files (mp4, jpg, vtt, ...), and the mp4s amount to 65MB.

While those file can be useful for development/testing, they most likely have no reason to be included when someone adds ovenplayer as a node_module to their project. 65MB in node_modules is huge.

Maybe the `files` field of the package.json could be used to provide just the `dist/production/ovenplayer` folder?

**Comment by SangwonOh** [comment]
@GregOriol Hi. Yes exactly. So we are lightening the distribution at 0.10.0 version. (https://github.com/AirenSoft/OvenPlayer/tree/0.10.0-alpha/dist). And we are going to make distribution more compact at the live release 0.10.0 version of OvenPlayer. Thanks :)

**Comment by SangwonOh** [comment]
We reduced package size since OovenPlayer v0.10.0. The ovenplayer node_module size is reduced to 3MB and the official release also reduced the size.

- https://github.com/AirenSoft/OvenPlayer/releases
- https://www.npmjs.com/package/ovenplayer

Thanks for your issue.
