### ISSUE TITLE
npm package and Vue, problem when loading scripts

### ISSUE THREAD

**Issue by BlastCake** [AirenSoft/OvenPlayer#176]
Hello. I tested your player and it is very cool.
But I can't connect the player locally.
I use the npm package. After creating the player object, it tries to load the scripts, the path that it tries to load them contains "undefined". I set window. OPEN PLAYER_LOCATION but it didn't bring any result, the variable is still "undefined".
This is the path it uses to search for scripts: http://localhost:3000/undefinedovenplayer-6f0c5a5.js
What am I doing wrong?

**Comment by SangwonOh** [comment]
@BlastCake Hi. It seems there is some typo. Please try the `OPEN PLAYER_LOCATION` to `OVENPLAYER_LOCATION`. If window.OVENPLAYER_LOCATION is not correctly set, Console says 'Please set window.OVENPLAYER_LOCATION where path of OvenPlayer in your environment.' Please check it. Thanks.

**Comment by BlastCake** [comment]
I'm sorry it was a text formatting issue.
I set this variable in the script block.
Like this: window.OVENPLAYER_LOCATION = "~/node_modules/ovenplayer"
And I checked it in the browser console. It is installed correctly

**Comment by SangwonOh** [comment]
We are not familiar with the nuxt js environment, so we haven't tested it. 

Please check the `window` object in the script block is the same as https://developer.mozilla.org/en/docs/Web/API/Window.

My Unit test code is

```html
<!doctype html>
<html>
<head>
    <title>Getting Started</title>
</head>
<body>
<div id="player">
</div>
<script>
    window.OVENPLAYER_LOCATION  = '/static/node_modules/ovenplayer/dist/'
</script>
<script src="/static/dist/app.js"></script>
</body>
</html>
```
```javascript
import Hls from 'hls.js'
import OP from 'ovenplayer'

window.Hls = Hls;

let player = OP.create("player", {
    controls: true,
    autoStart: true,
    sources: [{
        type: 'hls',
        file: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
    }]
});
```

 

We have just started deploying OvenPlayer to NPM. We hope you keep paying attention.

**Comment by nooitaf** [comment]
As you are not supposed to use script tags in Vue templates and anything in the component script get's loaded after the component's imports. 

I solved it by putting the window calls inside a custom import _before_ the ovenplayer import as imports get loaded from top to bottom.

I also copied all '/dist' files into a public folder '/public/ovenplayer' because my app doesn't have a 'node_folder' client side.

```js
// /api/imports/ovenplayer_before.js
import Hls from 'hls.js'
window.Hls = Hls;
window.OVENPLAYER_LOCATION  = '/public/ovenplayer/'
```

```js
// Vue component 
import '../api/dash.all.min.js';
import '../api/ovenplayer_before.js'
import OvenPlayer from 'ovenplayer'
```

**Comment by SangwonOh** [comment]
@nooitaf Thank you for sharing your experience. It seems that OvenPlayer should be improved to make it easier to use. I'll find out what that is widely used pattern.

**Comment by KVAnton-WEB** [comment]
>  I forgot the mention, i am using nuxt js, and maybe this is the problem and it does not collect correctly.

try this (this is a snippet but I think nuxt-devs will understand), it looks like it works for me
`dist/ovenplayer.js` - located in the `static` directory. it's all from `node_modules/ovenplayer/dist/`

```
....
  head() {
    return {
      script: [
        {
          hid: 'dash',
          src:
            'https://cdnjs.cloudflare.com/ajax/libs/dashjs/3.2.0/dash.all.min.js',
        },
        {
          hid: 'ovenplayer',
          src: 'dist/ovenplayer.js',
        },
      ],
    }
  },
  mounted() {
    this.socket = this.$nuxtSocket({
      name: 'rpi-rc',
      url: this.$nuxt.$config.baseUrl,
    })
    const index = 0
    const item = this.cameras[index]
    if (item) {
      const id = 'cam_' + (index)
      this.player = window.OvenPlayer.create(id, {
        sources: item.sources,
        autoStart: true,
        mute: true,
        disableSeekUI: true,
        currentProtocolOnly: true,
        controls: false,
        expandFullScreenUI: true,
      })
      this.player.on('ready', () => {
        this.isCamReady = true
      })
      this.player.on('error', (e) => {
        console.log(id, e)
      })
    }
  },
.....
```

**Comment by BlastCake** [comment]
Thank you all very much for your advices, but this moment solved the problem a little differently. Since my entire project runs in docker-compose, I wrote a service based on the nginx image which distrib the page with player. And in the main service I connect it via an iframe.

**Comment by SangwonOh** [comment]
Please check the latest version of the OvenPlayer manual. A lot has changed regarding the npm module.

We'll close this issue and cover vuejs in another issue.

And Please register as a new issue regarding the issue of using OvenPlayer as an ES6 module.

Thanks all.
