### ISSUE TITLE
full screen on rotate iphone

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenPlayer#177]
Hi,

Other players can be configured to go fullscreen when I rotate my phone - you dont seem to have an option for this.

How can I achieve this? Similar to iosinline option...

Kind regards,

Ian

**Comment by nooitaf** [comment]
It seems to get more and more difficult to figure out if a device is rotated. Virtual keyboard can trigger the wrong resize for example. `window.orientation` seems to be deprecated in android. But there might be other ways to get that information, idk. There seems to be an experimental `screen.orientation` so a combination might work.

You could then just call `player.toggleFullScreen()` to toggle it and/or listen to `on('fullscreenChanged')` event which will return true or false depending on fullscreen state.

Here is a discussion about orientation, keep in mind the deprecation..
https://stackoverflow.com/a/58974855/977395

**Comment by SangwonOh** [comment]
@IanMitchell77 There are no plans yet to embed this feature into the player. As @nooitaf said, it would be nice to call the player's full screen API after determining the orientation of the device in the application. Thanks.

**Comment by IanMitchell77** [comment]
@SangwonOh - That would be nice but it appears that it needs a user gesture to go fullscreen, it says "Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture."

**Comment by nooitaf** [comment]
@SangwonOh hmm.. i tried a `player.toggleFullScreen()` on the demo player from the console and it goes fullscreen. 

It only shows a warning:
> Request for fullscreen was denied because Element.requestFullscreen() was not called from inside a short running user-generated event handler.

**Comment by IanMitchell77** [comment]
@nooitaf - please attach the html file.

**Comment by nooitaf** [comment]
> @nooitaf - please attach the html file.

https://ovenplayer.com/docs/demo.html

open browser console and type `player.toggleFullScreen()`

**Comment by IanMitchell77** [comment]
@nooitaf  - thanks, I didnt know that you could do that - it works on a desktop but have you tried on a mobile phone?

**Comment by nooitaf** [comment]
I would assume it would work as it's just css as in width+height 100% i think.

If you have an iphone you can connect it to your desktop and open safari. There are options in the top menu to open the console/inspector for the phone's safari to test. The same works for android with chrome iirc. This way you can use the console and see errors of the phones browser.

Or try the demo.html from the source and add a link underneith that would trigger it.

**Comment by IanMitchell77** [comment]
You'd need a MAC for the iPhone I assume...

**Comment by nooitaf** [comment]
There are virtual screen share style solutions.. for example: www.browserstack.com

**Comment by SangwonOh** [comment]
Close this issue due to long inactivity. Please reopen for further discussion.
