### ISSUE TITLE
Player audio delay. 

### ISSUE THREAD

**Issue by KIM-IN-KYUM** [AirenSoft/OvenPlayer#178]
Update ovenmediaengine 0.10.11 and player .9.0-2021020516
Steaming encoder is Ovenencoder.
Video coming under 0.7 sec But audio over 10 sec.
Not matching on player.
Befor version worked as well.
Chrome and Safari same problem.

**Comment by SangwonOh** [comment]
@KIM-IN-KYUM It is difficult to say this is issue of player. What is the result when playing with the latest player and an older version of OME?

**Comment by getroot** [comment]
This issue has been resolved in the latest OME and OvenPlayer.
