### ISSUE TITLE
Set Poster Frame?

### ISSUE THREAD

**Issue by theColourSpace** [AirenSoft/OvenPlayer#184]
I've searched the documentation, and even the code... but I can't seem to find if there is a functionality to set a poster frame... an image (jpg) that loads and displays behind the player buttons, before the video loads.

Is this a possibility?

**Comment by SangwonOh** [comment]
@theColourSpace Hi. The poster functionality is described on https://airensoft.gitbook.io/ovenplayer/initialization#playlist. The image option is poster functionality.
```javascript
// poster image example
var player = OvenPlayer.create("player", {
    image: 'https://path.to/your_video_thumbnail.jpeg',
    sources: [...]
});
```

**Comment by SangwonOh** [comment]
Close this issue due to long inactivity. Please reopen for further discussion.
