### ISSUE TITLE
Access frames

### ISSUE THREAD

**Issue by caveman444** [AirenSoft/OvenPlayer#186]
Hi i am using ffmpeg to broadcast the video from a drone(nvidia jetson nano) to oven media engine(mpegts) and distribute to clients via webrtc using oven media player.It is working fine and getting the desired latency.Now i want to access frames in client side.Is it possible to access the frames(png or jpg) in oven media player?
This is my client side code to invoke media player,

           ` var defaultSources = [{
                type: 'webrtc',
                file: 'ws://localhost:3333/app/stream_4000?transport=tcp',
                label: '720p'
            }];

            var player = OvenPlayer.create("player", {
                 autoStart: true,
                 title : "Drone",
                sources: defaultSources
            });

            player.on("ready", function(data){
            });

            player.on("error", function(error){
                console.log(error);
            });`

**Comment by getroot** [comment]
I don't know how to access the frames on the player side, but you can create and get the thumbnails in OvenMediaEngine. Please refer to the URL below.

https://airensoft.gitbook.io/ovenmediaengine/thumbnail-experiment

**Comment by caveman444** [comment]
Yes that works.Thanks a lot.
