### ISSUE TITLE
API .load() command only loads the first object of the array

### ISSUE THREAD

**Issue by gusbmello** [AirenSoft/OvenPlayer#189]
To reproduce the issue:

1. Go to https://ovenplayer.com/docs/demo.html (you should have a player with three sources)
2. Run the following commands on the browser console:
`players = window.OvenPlayer.getPlayerList()` <- Store players loaded
`sources = players[0].getSources()` <- Store the 'sources' array from the currently loaded player
`players[0].load(sources)` <- Load the stored sources into the player
3. The player should now have only one source (the first source from the array)

![image](https://user-images.githubusercontent.com/12779243/119927319-9d75d980-bf4f-11eb-982b-fa114aa25c65.png)

**Comment by SangwonOh** [comment]
@gusbmello Hello. It seems there's bug on load() function. I will check this soon.

**Comment by SangwonOh** [comment]
@gusbmello Fixed at fc427dc9812322fb289a4a8ac05be55b57614f1e

Now load API works as designed https://airensoft.gitbook.io/ovenplayer/api-reference/api#load
