### ISSUE TITLE
Firefox can't play LL-DASH videos

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenPlayer#191]
I've tested default docker image
docker run -d --restart always --env OME_ICE_CANDIDATES=do.karsiyaka.com:10000-10010/udp --env OME_SIGNALLING_PORT=3333 --env OME_TCP_RELAY_ADDRESS=do.karsiyaka.com:3478 -p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp airensoft/ovenmediaengine:latest

Broadcasting from OBS with recommended settings. Playback works fine on Edge/Chrome/Opera but not in Firefox
https://demo.ovenplayer.com/demo.html#sources=%5B%7B%22default%22%3Afalse%2C%22id%22%3A1%2C%22label%22%3A%22LLDash%22%2C%22file%22%3A%22https%3A%2F%2Fdo.karsiyaka.com%2Fapp%2Fstream%2Fmanifest_ll.mpd%22%2C%22type%22%3A%22dash%22%7D%5D&lowLatency=true&liveDelay=1

Firefox downloads files but there is no video. I've TLS reverse proxy to port 8080 and it works fine with/without TLS on other browsers.

**Comment by mpisat** [comment]
It seems Safari on MacOS also can't play them. Chrome on MacOS works fine.

**Comment by mpisat** [comment]
Somehow I'm able to play video on Safari (Mac) and Firefox (Mac) today. I've been using 1-sec latency, and still, I am but this time I'm making sure keyframes are exactly 1 seconds. Maybe that fixed the issue?

**Comment by getroot** [comment]
@mpisat Oh, of course. We recommend at least 2 seconds for latency in LL-DASH. And it is recommended that the key frame interval be at least 1 second or less.
Thanks for sharing your experience.
