### ISSUE TITLE
Quality change override?

### ISSUE THREAD

**Issue by ed96win** [AirenSoft/OvenPlayer#195]
With the ovenplayer and a DASH-based source, I can put the "adaptive" stream link and it also lets me to manually choose the quality but with HLS-based adaptive source I cannot. am I doing something wrong?

(the HLS source is not generated by OvenMediaEngine tho)

**Comment by SangwonOh** [comment]
@ed96win Hi. Currently, the adaptive quality selection UI is not implemented in HLS playback in OvenPlayer. This feature has a low priority, so it is unlikely that it will be added in the near future.
