### ISSUE TITLE
ovenplayer exits full screen if it doesn't detect webrtc video input, why?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#197]
I would like it to always stay in full screen, with or without video input

**Comment by SangwonOh** [comment]
@Mariano245 Hi. 

Have you tested on https://demo.ovenplayer.com? The demo page reinitializes the player in error situations, such as when the WebRTC Input connection is lost. Therefore, it will return to the normal screen from the full screen.
If you do not initialize in an error situation, the entire screen will be ㅏkeeped even when the WebRTC input is cut off.

**Comment by Mariano245** [comment]
I want to use the player only, for this reason, I am editing the demo.html file in the docs folder and my intention is that every time the player is restarted in an error situation, it restarts in full screen. Will this be possible? The entry will always be webrtc.

**Comment by SangwonOh** [comment]
@Mariano245
When OvenPlayer encounters an error, it can be solved by calling the load() function instead of reinitializing it.
OvenPlayer stays full screen because it doesn't restart the player.
Please try this simple code first.
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <style>
        #player {
            width: 600px;
        }
    </style>
</head>
<body>
<div id="player">

</div>
<script src="../dist/development/ovenplayer/ovenplayer.js"></script>

<script>

    var errorRetryTimer = null;

    var sources = [
        {
            type: 'webrtc',
            file: 'wss://your_streaming_url'
        }
    ];

    var player = OvenPlayer.create('player', {
        autoStart: true,
        sources: sources
    });

    player.on('error', function () {

        errorRetryTimer = setTimeout(function () {

            console.log('Retry loading');
            player.load(sources);
        }, 2000)
    });
</script>
</body>
</html>
```

**Comment by Mariano245** [comment]
it worked very well, thank you very much
