### ISSUE TITLE
Audio on loop WEBRTC

### ISSUE THREAD

**Issue by MoZyo** [AirenSoft/OvenPlayer#198]
First of all, great work! That was quick!

So, the problem is with the audio on WebRTC. I have OBS streaming to my VPS and I was testing it out with your Test Player before applying it. 
Right from the start, audio is looping, stops for a second then loops again...

Tested with hls playback and the audio is okay but the video is delayed.

Running on default, installed via docker.

**Comment by getroot** [comment]
I think this issue should be written on the OvenMediaEngine side. https://github.com/AirenSoft/OvenMediaEngine/issues

And upload the /var/ovenmediaenigne/ovenmediaengine.log file inside docker, and if you used OBS for the output, capture the encoding setting of OBS and upload it together.
