### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by DevMemberR** [AirenSoft/OvenPlayer#199]
I have deployed a simple express app running OvenPayer. OME webRTC sources are working on demo test page, and also when running app locally (ws://{host}:3333/app/stream). Once deployed I have access to play Standard video (mp4) served statically but the webRTC sources are not available.

Any ideas would be much appreciated.

OME Docker Container on GCP Compute Engine. App running in Google App Engine.

**Comment by SangwonOh** [comment]
@DevMemberR Hi.

1. Did you mean?
Can play WebRTC stream : OME Docker Container on GCP Compute Engine <-> https://demo.ovenplayer.com/
Can not play WebRTC stream : OME Docker Container on GCP Compute Engine <-> Your app running in Google App Engine

2. If your app fails to play a WebRTC stream, what console logs do you see in the developer tools?

3. Can I access to your app?

Thanks.

**Comment by DevMemberR** [comment]
Hi there,

Yes, thanks, you put it better than I did. But unfortunately it seems to not be working on https://demo.ovenplayer.com/ either now. It only works when I run the app locally.

2. The error reads - WebSocket connection failed: WebSocket is closed before the connection is established. 
<img width="493" alt="Screenshot 2021-08-14 at 03 29 55" src="https://user-images.githubusercontent.com/74425790/129431724-9efba773-88c8-4f23-9e02-76f775062469.png">

3. My repository : https://github.com/DevMemberR/ome-test

Many thanks
