### ISSUE TITLE
Group by Quality and not Source?

### ISSUE THREAD

**Issue by MoZyo** [AirenSoft/OvenPlayer#201]
How can I group LLDash sources to quality instead?

I have setup a High, Normal, Low encoding and I'd like to display them as quality of LLDash instead.
![image](https://user-images.githubusercontent.com/65864218/130614797-2d370e95-a494-48b1-be0c-3055fc6b9f6b.png)
![image](https://user-images.githubusercontent.com/65864218/130614839-b164465e-f9ee-485d-a05d-e4b57c8e0de3.png)

Currently, I have this:
```
    player = OvenPlayer.create("player",{
        image : "image.png",
        sources: [
            {
            type : "DASH",
            file :  "https://domain/app/stream/manifest_ll.mpd",
            framerate : 30,
            label: "480p"
            },
            {
            type : "DASH",
            file :  "https://domain/app/stream_normal/manifest_ll.mpd",
            framerate : 30,
            label: "360p"
            },
        ]
    });
```
Can't seem to figure it out reading the guide.

Thanks in advance.

**Comment by SangwonOh** [comment]
@MoZyo Hi.
A quality panel exists for ABR dash streams. Later, if OvenMediaEngine supports ABR, it will show multiple qualities in the quality panel using one source.
Thanks.

**Comment by Baa14453** [comment]
> @MoZyo Hi. A quality panel exists for ABR dash streams. Later, if OvenMediaEngine supports ABR, it will show multiple qualities in the quality panel using one source. Thanks.

Is this still the case? Would be good if we had a way to group qualities and sources together for a more seamless user experience. If not, a way to hide the quality selector would be good too as it only ever has one entry at the moment:
![image](https://github.com/AirenSoft/OvenPlayer/assets/9057997/4e3ca11e-3fed-4084-b184-f8e8814843db)

![image](https://github.com/AirenSoft/OvenPlayer/assets/9057997/29c32443-7b3f-4066-afab-58ba8ea9c59a)

**Comment by SangwonOh** [comment]
Now OvenMediaEngine supports ABR. https://airensoft.gitbook.io/ovenmediaengine/transcoding#adaptive-bitrate-streaming-abr
So you can make source panel display main, backup and quality panel display grouped qualities.
Also We are closing the issue due to a long period of inactivity. If further discussion is needed, please open a new issue.
