### ISSUE TITLE
WebRTC input x-google-start-bitrate hack?

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenPlayer#202]
There is a way to start WebRTC bitrate from a predefined value rather than waiting for it to slowly increase to set limit. Any idea how can I implement it to https://demo.ovenplayer.com/demo_input.html

I have the stripped down copy on my server, but I can't figure out x-google-start-bitrate part :)
This could be added to OME page if the bitrate is manually entered, it's nicer than waiting for upload speed to reach out max. bitrate.

**Comment by mpisat** [comment]
I can wait for config parameters next week or later. I have no clue where to modify tbh. I'm that bad at Javascript :)

**Comment by SangwonOh** [comment]
@mpisat Hi.

I updated OvenLivekit.js.

First of all, Please make sure you are using latest version of OveLiveKit (`https://cdn.jsdelivr.net/npm/ovenlivekit@1.0.1/dist/OvenLiveKit.min.js`) in your demo_input.html.

And modify the `startStreaming()` code where https://github.com/AirenSoft/OvenPlayer/blob/48effcf1d79321e00b02d9c42889438e4a10f002/docs/demo_input.html#L636

to 

```javascript
function startStreaming() {

    streamingStarted = true;
    streamingButton.removeClass('btn-primary').addClass('btn-danger');
    streamingButton.text('Stop Streaming');

    if (input) {

        let connectionConfig = {
            sdp: {
                appendFmtp: 'x-google-start-bitrate=1000'
            }
        };

        if (videoBitrateInput.val()) {
            connectionConfig.maxVideoBitrate = parseInt(videoBitrateInput.val());
        }

        input.startStreaming(webRtcUrlInput.val(), connectionConfig);
    }
}
```

`connectionConfig.sdp.appendFmtp` will append media format strings as we've wanted(e.g. `x-google-start-bitrate=3000;x-google-min-bitrate=3000;x-google-max-bitrate=3000`)

**Comment by mpisat** [comment]
It works great. Thank you!

I used this

```
            let connectionConfig = {
              sdp: {
                  appendFmtp: 'x-google-start-bitrate=' + parseInt(videoBitrateInput.val()) + ''
              }
            };
```
