### ISSUE TITLE
qualityChanged not triggered. 

### ISSUE THREAD

**Issue by sefacndmr01** [AirenSoft/OvenPlayer#203]
When i changed quality with [setCurrentQuality ](https://airensoft.gitbook.io/ovenplayer/api-reference/api#setcurrentquality) function, [qualityChanged ](https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-qualitychanged)event not triggered.

Type: Dash **( Single manifest with adaptation set )**
v.0.9.0-2021080212-localbuild (development build)

Manifest
![image](https://user-images.githubusercontent.com/18026221/131194230-ed43a3f8-52a7-4a67-b9d3-8e83b608c23b.png)

**Comment by SangwonOh** [comment]
@sefacndmr01 Hi. There seems to be a bug. We'll check it out soon.

**Comment by SangwonOh** [comment]
@sefacndmr01 There was typo on the documentation. Please use `qualityLevelChanged`.
https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-qualitylevelchanged

**Comment by sefacndmr01** [comment]
@SangwonOh Tank you! It works :)
