### ISSUE TITLE
HLS: iOS stucks at loading state when autoStart options is true

### ISSUE THREAD

**Issue by sefacndmr01** [AirenSoft/OvenPlayer#205]
On IOS "autoStart:true" option is stuck at loading state. When I trigger API play(), it will return "state paused".

Type: HLS
Version: v.0.9.0-2021080212-localbuild (development build)

**Comment by mpisat** [comment]
iOS doesn't like autoplay content with audio.

**Comment by sefacndmr01** [comment]
Hi @mpisat,
Thanks for reply. But I already know that. 

The user interacts with the browser before the player is initialize. So interact security is not an issue. The user changes a tab before encountering the player. I'm using Vue, the tab with the player is an async component.

**Comment by SangwonOh** [comment]
@sefacndmr01 Hi. I'll check it out. Can you provide the stream you tested?

**Comment by sefacndmr01** [comment]
@SangwonOh Hi,

Let me know when you will check it out. I'll start stream.
https://live.3dstudyo.com:5443/WebRTCAppEE/streams/250174191005111651740270/250174191005111651740270.mpd

**Comment by SangwonOh** [comment]
@sefacndmr01 OK. First I'll test it with my own OvenMediaEngine.

BTW, You gave the DASH URL. I believe the HLS playback URL will also work fine :)

**Comment by sefacndmr01** [comment]
@SangwonOh  Oh, sorry. 
https://live.3dstudyo.com:5443/LiveApp/streams/939061935302528770571544.m3u8

I'm starting right now.

**Comment by SangwonOh** [comment]
@sefacndmr01 Thanks. I could reproduce stucking. 

This seems to happen if calls play() before the player start autoplay naturally. I will fix this problem and contact you.

**Comment by sefacndmr01** [comment]
@SangwonOh 

I'm looking forward to your fix. 
Thank you for your interest.

**Comment by SangwonOh** [comment]
@sefacndmr01 Please check with OvenPlayer v0.10.2 and let me know the test results. Thanks.

**Comment by sefacndmr01** [comment]
@SangwonOh  Hey, It seems to be working fine.  Thank you so much!
