### ISSUE TITLE
autostart stay on loading

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#208]
hi, after give browser the auto load video permission, on webRtc when the ovenplayer is loaded it keep loading the  wss link until i push pause and play then show the video

version 0.10.1 on 0.9 is the same.
Thanks

**Comment by alnux** [comment]
here is a video link of issue
https://jmp.sh/J8VwFBl

**Comment by SangwonOh** [comment]
@alnux Hi. I updated the logic to start playing the stream. Please check with OvenPlayer v0.10.2
Please let me know the test results. Thanks.

**Comment by alnux** [comment]
change version. I think the problem is due to the browser's policies on the autoStart of the video does not allow this if the video has audio, on the contrary, if the audio is muted, the player works without problems.

**Comment by SangwonOh** [comment]
Please let me know if you have the same issue whether the audio is muted or not.

**Comment by SangwonOh** [comment]
Consider it resolved and close the issue. Please reopen for further discussion.
