### ISSUE TITLE
how show controls player

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenPlayer#209]
hi,
 i have a question how can i show the controls after hide them on initialization config (controls:false), becouse i hide them on load play link.
After the player state is "playing" i want to show them to be unmuted by the viewer

really really thanks

**Comment by sefacndmr01** [comment]
As a workaround you can hide and show the element of the op-ui class in the [stateChanged](https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-statechanged) event.

**Comment by bchah** [comment]
Thanks @sefacndmr01 for the workaround suggestion. The only issue with hiding op-ui is you lose the entire UI e.g. loading spinner, background image... It would be great if we could show/hide controls on an already initialized player with a method like player.showControls(true). @SangwonOh would you consider this feature request? 🥇

**Comment by SangwonOh** [comment]
I also think that it is difficult to manipulate the control area with CSS from the outside of the player. I will add player.showControls(boolean) API and patch it next week.

**Comment by SangwonOh** [comment]
A new API was added in 0.10.5 version. (https://cdn.jsdelivr.net/npm/ovenplayer@0.10.5/dist/ovenplayer.js)
A brief explanation is written here. (https://airensoft.gitbook.io/ovenplayer/api-reference/api#showcontrols)
Thanks All.
