### ISSUE TITLE
can not find hlsjs. please check the hlsjs.... in chrome, in safari work 

### ISSUE THREAD

**Issue by linkinblack** [AirenSoft/OvenPlayer#211]
HELLO 
This message show player
"can not find hlsjs. please check the hlsjs".... in chrome, 

in safari work 100%

**Comment by SangwonOh** [comment]
@linkinblack Hi. Did you load the hls.js? You need hls.js to play HLS in browsers other than Safari.

https://airensoft.gitbook.io/ovenplayer/#initialize-for-hls
```html
<!-- You need hls.js to play HLS. -->
<script src="https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js"></script>
```

**Comment by SangwonOh** [comment]
Consider it resolved and close the issue. Please reopen for further discussion.
