### ISSUE TITLE
getVersion API does not work on the latest player - the date is 16/09/2021

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenPlayer#213]
I am using https://cdn.jsdelivr.net/npm/ovenplayer@latest/dist/ovenplayer.js

After var player = OvenPlayer.create I do player.getVersion();

And I get this error:
Uncaught ReferenceError: version is not defined
    at Object.t.getVersion (Api.js:486)

**Comment by SangwonOh** [comment]
@IanMitchell77 Hi. The API seems to be broken. I will fix it and patch it. thanks for letting me know.

**Comment by SangwonOh** [comment]
@IanMitchell77.  Please check the version 0.10.5. https://cdn.jsdelivr.net/npm/ovenplayer@0.10.5/dist/ovenplayer.js Thanks

**Comment by IanMitchell77** [comment]
@SangwonOh - that works fine but if I use @latest it reports 0.10.3

**Comment by SangwonOh** [comment]
@IanMitchell77 Please try https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js

When used together with `@latest` , it seems that jsdelivr does not work well.

reference: https://www.jsdelivr.com/features

**Comment by IanMitchell77** [comment]
Yes 0.10.5 - I'll stick with that...
