### ISSUE TITLE
Hi, I would like to know if in conditions of poor internet quality or low signal, it is possible to automatically lower the bitrate to maintain a live broadcast. Is it a question to be solved by the encoder or by the server? ... I currently use rtmp to transmit and webrtc to reproduce.

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#214]

**Comment by SangwonOh** [comment]
@Mariano245 Hi.

> it is possible to automatically lower the bitrate to maintain a live broadcast.
This feature will be supported in the near future. In current situation, generate the output streams which have different bitrate in OvenMediaEngine, and then let the user to choose a lower bitrate stream in OvenPlayer when they have trouble playback live stream.

It is our plan that OvenMediaEngine implements webrtc's simulcast, hls and dash's ABR, and OvenPlayer dynamically selects and plays streams according to network conditions. Stay tuned for our progress. Thanks.

**Comment by SangwonOh** [comment]
Abr feature added.
https://airensoft.gitbook.io/ovenmediaengine/transcoding#adaptive-bitrate-streaming-abr

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
