### ISSUE TITLE
Auto mute on source change

### ISSUE THREAD

**Issue by HighK** [AirenSoft/OvenPlayer#215]
In previous versions(~0.9.0), changing to a source of the same type(webrtc, hls ...) would retain the volume or mute state you set.
And only muted when it's a different type of source.

The current version(test on 0.10.3) will auto mute when you change the source no matter what type it is.

**Comment by SangwonOh** [comment]
@HighK. We have released a new version. Please check the version 0.10.5.

**Comment by HighK** [comment]
@SangwonOh  yes, i using `mute:true` for autostart playback. OK, I'll check 0.10.5.
