### ISSUE TITLE
ovenplayer failure

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#217]
ovenplayer playing a webrtc stream, starting from an rtmp stream generated by Vmix, it starts to fail (drop and freeze frames) after an internet cut of just 5 or 10 seconds in the vmix place. playback then continues automatically but failing. If the internet cutoff is 30 seconds or more so that ovenplayer can automatically restart everything works fine once the internet returns. It seems that Ovenplayer cannot play a stream correctly after a short cut of
internet at the issuing point?

**Comment by SangwonOh** [comment]
@Mariano245 Hi.

It's hard for me to reproduce. When internet cut of just 5 or 10 seconds in the vmix place, Does the player display an error message? Or is the log written to the developer console?

Note that OvenPlayer does not automatically recover when webrtc stream playback fails. However, in our demo site or in actual use, when a player error event occurs, we reinitialize the player and try to play the stream again at the application level.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
