### ISSUE TITLE
Create OvenPlayer with custom CSS

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenPlayer#218]
Hi @SangwonOh, it is easy to change the colours of OvenPlayer by calling the raw CSS. 

However this has to be done every time a new player is created, or if the state of the player UI changes.

Can I please request a player initialization property, perhaps to give an array of custom CSS declarations? 

E.g.

    `player = OvenPlayer.create("player", {
        autoStart: true,
        mute: mute,
        controls: true,
        sources: source,
        css: [
            { target: ".op-volume-slider-value", property: "background-color", value: "#000000" },
            { target: ".op-spinner", property: "border-top", value: "4px solid #000000" },
            { target: ".op-progressbar", property: "background-color", value: "#FFFFFF" }
        ]
    });`

Thank you for your consideration 🙏🏻

In the meantime I will make a small pull request ( #219 ) to support use of a CSS variable '--op-accent-color', which is an easy way to cover the basic coloring.

**Comment by SangwonOh** [comment]
I understood what the situation was.

I have solved this problem using css and html. We have guided our customers in this way as well. Added --op-accent-color makes the css more concise :)
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OvenPlayer</title>
    <style>

        .player-container {
            width: 600px;
            --op-accent-color: red;
        }

    </style>
</head>
<body>
<div class="player-container">
    <div id="player"></div>
</div>

<script src="../dev/ovenplayer.js"></script>
<script>

    const player = OvenPlayer.create('player', {
        sources: [
            ...
        ]
    });

</script>
</body>
</html>
```

However, this is my preferred method and there will be many developers who prefer to use js.

I think your idea is cool.
