### ISSUE TITLE
WebRTC on macOS & iOS

### ISSUE THREAD

**Issue by cmaz-bob** [AirenSoft/OvenPlayer#222]
Hi,

Since few days, I can't access WebRTC streaming from my server. After searching few hours, I finally found that it's working on Windows, but not on macOS or iOS. I've try with Safari, Chrome and Firefox.
Did you have any idea of the problem?

Even from the OvenPlayer demo website, I can't access my server. But the same demo website on a PC, it's working.

Thanks in advance,
Cyril

**Comment by SangwonOh** [comment]
@cmaz-bob Hi. Recently there has been an issue with webrtc playback on the latest Apple OSes. 
https://github.com/AirenSoft/OvenMediaEngine/issues/517
https://github.com/AirenSoft/OvenMediaEngine/issues/518
Please update OvenMediaEngine to the latest version and check again. Thanks!

**Comment by cmaz-bob** [comment]
Maybe we should continue this discussion on this issue ?
https://github.com/AirenSoft/OvenMediaEngine/issues/517

**Comment by getroot** [comment]
It doesn't seem to be a problem with OME or OvenPlayer.  It seems that some browsers don't trust the root chain of the certificate you set up.  If you do a Google search on this error, you will find a lot of information.

**Comment by dimiden** [comment]
@cmaz-bob
This issue is not related to https://github.com/AirenSoft/OvenMediaEngine/issues/517.
With a very high probability, ```<ChainCertPath>``` in ```<TLS>``` may not be set, or the certificate used may not be correct.
