### ISSUE TITLE
Disable seekbar isn't working?

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenPlayer#224]
Hi,
I can't disable seekbar for Android Chrome client:
![image](https://user-images.githubusercontent.com/46460263/137950965-27ed9386-3aac-4123-b081-fad03fc26e7c.png)
This happens after player initialize, when phone is buffering HLS content.

How to disable it? I'm providing only HLS live streams.

```
disableSeekUI: false,
showSeekControl: false
```

**Comment by SangwonOh** [comment]
@fcqpl Hi. `disableSeekUI: true` means the OvenPlayer shows the seekbar but the users can't interact with it.

What do you mean by `disable search bar`? Does it behave differently only on Android?

**Comment by SangwonOh** [comment]
@fcqpl 

> Seekbar is showing for a while when player is loading HLS stream


Please check with the latest version of OvenPlayer. [Make the UI change naturally when the source changes](https://github.com/AirenSoft/OvenPlayer/commit/1cbf9d13a718853bae7724e67eaeeed06850961f) will work.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
