### ISSUE TITLE
Android OvenPlayer audio isn't switching to the bluetooth device.

### ISSUE THREAD

**Issue by streamthing** [AirenSoft/OvenPlayer#226]
Can you check on your Android Devices?

1. Play stream on phone speaker.
2. Connect to bluetooth device.
3. Audio will not switch to the bluetooth device.
4. Close browser, open, sound is playing on connected bluetooth device.

Can you fix this?

Newest Chrome from Google Play

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
