### ISSUE TITLE
Android OvenPlayer audio isn't paused after answer call

### ISSUE THREAD

**Issue by streamthing** [AirenSoft/OvenPlayer#227]
Can you check on your Android Devices?

1. Play stream on phone speaker.
2. Answer phone call.
3. Stream is still playing in background.

Can you fix this?
Newest Chrome from Google Play

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
