### ISSUE TITLE
WebRTC packet loss monitoring?

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenPlayer#229]
Hi,
I found recorverPacketLoss in code. Is it works or maybe in development?

I setup our test player, queue bandwidth to 1Mbps (stream 2,5Mbps) to OME and see `Last8 LOST PACKET AVG` log in console:
`Last8 LOST PACKET AVG  : 613.75 Current Packet LOST: 777 Total Packet Lost: 5968 (8) [538, 502, 335, 893, 819, 624, 422, 777]`
But player isn't switching to HLS source.

```
sources: webrtc, hls
webrtcConfig: {
	recorverPacketLoss: true
},
```

PS. Small typo recorver => recover

**Comment by fcqpl** [comment]
Hi,
Is something changed? I need to automatic move user from WebRTC to HLS when packet loss is detected.
Any API for read statistics with packet loss?

**Comment by SangwonOh** [comment]
Please refer this issue. https://github.com/AirenSoft/OvenPlayer/issues/261

Also We are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
