### ISSUE TITLE
iOS 15.x WebKit audio bug affecting OvenPlayer

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenPlayer#232]
There is a known WebKit issue with AudioContext where playback volume goes very low when transmitting WebRTC audio/video:

https://bugs.webkit.org/show_bug.cgi?id=230902

Have you noticed this on iOS 15? I am able to reproduce it with OvenPlayer and OvenLiveKit.

**Comment by SangwonOh** [comment]
@bchah Is this occur when running both OvenLiveKit and OvenPlayer on iOS?

**Comment by bchah** [comment]
@SangwonOh that's correct - if you are sending a media stream, something is wrong with the AudioContext for playback of any other streams on the page and the volume is very very low.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
(We are cleaning old issues and reorganizing the issues panel.)
