### ISSUE TITLE
WebRTC streaming interruption

### ISSUE THREAD

**Issue by yginuo** [AirenSoft/OvenPlayer#237]
The streaming of OvenLiveKit.js is unstable. OvenLiveKit may be automatically disconnected after about five hours of streaming

**Comment by getroot** [comment]
@yginuo 
In order for us to work together to solve the problem, you must provide more detailed information. It could be a problem with your browser or it could be a problem with your PC. Or it could be a problem with OvenMediaEngine. I don't understand what you mean by creating this type of issue. This is an open source community. This is not a customer service center.

OvenLiveKit just uses the PeerConnection provided by the web browser. There is no such thing as a restriction on 5 hours.

Where is the problem? What is your opinion?
