### ISSUE TITLE
WebRTC cannot connect again within 10 minutes after switching the network

### ISSUE THREAD

**Issue by yginuo** [AirenSoft/OvenPlayer#238]
WebRTC cannot connect again within 10 minutes after switching the network
1. Use OvenLiveKit to push streaming on PC
2. Switch to another network or re-plug the network cable
3. The WebRTC connection is disconnected, and you need to wait for 5~10 minutes before you can connect again

**Comment by SangwonOh** [comment]
@yginuo Please reopen the issue in OvenLiveKit-Web project. https://github.com/AirenSoft/OvenLiveKit-Web/issues
