### ISSUE TITLE
Player dose not recover after network problem

### ISSUE THREAD

**Issue by johnrogis8** [AirenSoft/OvenPlayer#240]
Hi,
I am using OvenMediaEngine to send rtmp stream to viewers browsers with Webrtc. But when some viewer's internet disconnected even for just a moment his player dose not recover automatically and he should reload the page.
Is there any settings or solution for this problem?
if i use this method: Low Latency: MPEG-DASH (Chunked CMAF) i will stil have this problem?

thanks

**Comment by SangwonOh** [comment]
@johnrogis8 Hi. There is no WebRTC auto-recovery feature for the player itself. However, we are considering adding an auto-recovery function for stable playback in the near future.

For Low Latency MPEG-DASH, automatic recovery is possible through dashjs used by OvenPlayer. But we'll have to test it.

**Comment by SangwonOh** [comment]
So far, if the player fails to play the stream, we've reloaded the player via the player error event listener. And we are using the same method on our demo player page. https://demo.ovenplayer.com/
```javascript
var ovenPlayer = null;

function loadOvenPlayer () {

    if (ovenPlayer) {

        ovenPlayer.remove();
        ovenPlayer = null;
    }

    ovenPlayer = OvenPlayer.create({/*your_options*/});

    // Reload OvenPlayer when error occured.
    ovenPlayer.on('error', function () {

        // Wait 1 sec and relaod.
        setTimeout(function () {

            loadOvenPlayer();
        }, 1000)
    });
}

loadOvenPlayer();
```

**Comment by SangwonOh** [comment]
Consider it resolved and close the issue. Please reopen for further discussion.
