### ISSUE TITLE
Problem with sending Stop command to the signalling server - WebRTC

### ISSUE THREAD

**Issue by mekhti** [AirenSoft/OvenPlayer#241]
We have got a problem with restarting the streaming from OvenPlayer to the OvenMediaEngine by WebRTC. Analyzing the logs shows that OvenPlayer does not send the Stop command when user click on the Disconnect button, and as a result, needs to wait for the timeout to expire (60 seconds) so that the stream ID (Stream Key) in the OvenMediaEngine is deleted. Or, we need to reload the web page, as a result of which the Stop command goes to the OvenMediaEngine (a message appears in the logs) and it becomes possible to re-stream to the OvenMediaEngine. Regarding that, the question is how to send the Stop command by pressing the Disconnect button without reloading the player's page?

**Comment by SangwonOh** [comment]
@mekhti Hi. Thanks for leaving a detailed analysis. I'm going to try to analyze this problem. Please explain a little bit more to understand the exact situation.

> OvenPlayer does not send the Stop command when user click on the Disconnect button

What do you mean by "Disconnect button"?

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
