### ISSUE TITLE
Big Play Button is not being showed 

### ISSUE THREAD

**Issue by ifamirhasan** [AirenSoft/OvenPlayer#242]
when I use js file from github or build it by myself, big play button is not being showed and player just showing loading spinner but when I use js file from cdn you provided in documents it works correctly.
I also saved js file from cdn and used locally, it was ok.
I checked console from browser, there wasn't any problem.

**Comment by SangwonOh** [comment]
@Amirhasanioox Hi. I also cloned the project from scratch and tried to build it, but the button was showing properly. There seems to be some other problem. 

When using your local build code, can you find this element in developer tools? How does it come out in your developer tools? 

Are the other button icons (such as the play button in the control bar at the bottom...) displayed normally?

![image](https://user-images.githubusercontent.com/21077319/147437519-4d20fcf9-2e80-46f8-8572-3fe95403572a.png)

**Comment by SangwonOh** [comment]
@Amirhasanioox Maybe there was a bug in the version of OvenPlayer you got from github.  And issue was fixed v0.10.14.
- https://github.com/AirenSoft/OvenPlayer/issues/243

The source code of the master branch and cdn may not always match.
Please check with the latest version of OvenPlayer. Thanks.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
