### ISSUE TITLE
OvenPlayer Down

### ISSUE THREAD

**Issue by natzakaria** [AirenSoft/OvenPlayer#243]
Are there any new updates?
My embedded player just shows this since morning - it has been working for almost 2 months flawlessly.
Kindly advise
![Screenshot 2021-12-28 at 10 50 33 AM](https://user-images.githubusercontent.com/65059352/147522660-0dcf51ed-7bc9-4064-a3d0-3aa63ef04e83.jpg)

**Comment by SangwonOh** [comment]
@natzakaria Hi. 

Please tell us your browser version and OvenPlayer version.
And are there any special logs and network issues in the developer tools?

**Comment by natzakaria** [comment]
Hi Sangwon

I tested my wss link on the demo player page it works fine.
I just want to use the code that is shown as an embedded code but since my web guy is away I may have to try myself.
Can you advise what will be the correct full code that I should use based on on the demo player page?

It is currently using this code but I replaced the IP to xxx:

<html>
<head>
<title>Page Title</title>


</head>
<body>

<script>
$(document).bind("contextmenu",function(e){
  return false;
    });
</script>

    
	<div class="player-wrapper">
    <div id="player_id"></div>
	</div>
<script src="https://nzlive.net/constants.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/dashjs@latest/dist/dash.all.debug.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>
	
	
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js"></script>

    <script>

        // Initialize OvenPlayer
        const streamx = OvenPlayer.create('player_id', {
            sources: [
            {
    "file": "wss://xxx.xxx.xxx/app/stream3?transport=tcp",
    "label": null,
    "type": "websocket"
  },
            ]
        });

streamx.getConfig().systemText.api.error[501].message = 'NZLive not active';
streamx.getConfig().systemText.api.error[511].message = 'NZLive not active';
    </script>
</body>
</body>
</html>

**Comment by natzakaria** [comment]
Thanks for replying.

Browser version - Chrome on Mac Version 96.0.4664.110 (Official Build)
(x86_64)
OME version updated 1 week ago
Player version - how do I check?

I tested the wss using the demo player website and it works perfectly fine.

If you can provide me with the full html code based on the code generated
on the Player website I will be more than happy.

The wss link is wss://ndec.ddns.net:3334/app/stream3

Merry Christmas and Happy New Year

**Comment by SangwonOh** [comment]
@natzakaria 

I found UI bug at the OvenPlayer. It's a bug that if there is no autoStart option, The player should be in Idle state but it is the loading state. This is an issue from the last version update. (The version of the player can be found in the developer console.)

In your case, setting the autoStart option to true will fix it right away.

```javascript
const streamx = OvenPlayer.create('player_id', {
    autoStart: true, // Add this
    sources: [
        {
            "file": "wss://xxx.xxx.xxx/app/stream3?transport=tcp",
            "label": null,
            "type": "websocket"
        }
    ]
});
```

However, I will fix and patch this bug as soon as possible.

**Comment by SangwonOh** [comment]
It should work fine in the new version(0.10.14).

```
<!-- Load OvenPlayer via CDN -->
<script src="https://cdn.jsdelivr.net/npm/ovenplayer@0.10.14/dist/ovenplayer.js"></script>
```

And you can see our demo player code at https://github.com/AirenSoft/OvenPlayer/blob/master/docs/demo.html. 

Thanks for reporting this issue!

**Comment by natzakaria** [comment]
Thanks for your assist

**Comment by natzakaria** [comment]
Happy New Year
