### ISSUE TITLE
Latest OvenPlayer breaks if webrtcConfig is applied in script

### ISSUE THREAD

**Issue by zygocact** [AirenSoft/OvenPlayer#244]
I have a webpage with ovenplayer embedded through https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js
It stopped working with the latest update, and in local testing, removing the webrtcConfig setting in the embed made it work again.
The symptoms is that OvenPlayer keeps trying to reload stream, and fails, and then tries to reload stream again, etc.
Older versions still work, plus I updated the OvenMediaEngine docker file to the latest version, it is still broken.
Was .webrtcConfig deprecated?

![image](https://user-images.githubusercontent.com/75622726/147837141-98b10337-57d5-4c30-9e1c-4a712e35516a.png)

**Comment by SangwonOh** [comment]
@zygocact Hi. Which webrtcConfig are you using? Could you paste your player option?

**Comment by zygocact** [comment]
These two.
I've tried many different values for attempts and timeout, and nothing short of removing the settings fixed the stream.
It attempts to reload the stream continuously, and never gets to actually play it.
I am streaming SRT from OBS to WebRTC on client side.
![image](https://user-images.githubusercontent.com/75622726/147851639-0c695f92-6f39-4cb6-bec2-7a0183991802.png)

**Comment by SangwonOh** [comment]
@zygocact In my environment, it plays normally in players v0.10.13 and v0.10.14.

What browser are you using?
Can you find anomalies in the developer tools console?
What error is the player throwing?
Can I get your full source code if possible?

**Comment by zygocact** [comment]
I am using Firefox 95. Just tested with Chrome, it seems to work fine there. It behaves as if the "webrtcConfig" config isn't even there, doesn't show the circular reload icon, etc.
On firefox, it shows the circular reload icon, but then continuously tries to reload the stream without actually playing.
The code:
```
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<body>
    <div id="player_id1" class="video_frame"></div>
    <!-- Load OvenPlayer via CDN -->
    <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>

    <script>
                const player = OvenPlayer.create("player_id1", {
                "autoStart": true,
                    "autoFallback": true,
                    "mute": false,
                    "sources": [{
                        "type": "webrtc",
                        "file": "ws://x.x.xx.xxx:3333/app/stream"
                    }],
                    "webrtcConfig": {
                        "timeoutMaxRetry": 4,
                        "connectionTimeout": 10000
                    }
                });
    </script>
</body>

```
Here's the browser logs. No errors messages, just logs. These messages repeat as the player cycles reloading the stream repeatedly. Sorry that it's not in text form. I hope this is what you meant by error logs.
![image](https://user-images.githubusercontent.com/75622726/147947654-2720f038-38a0-4470-8c2b-26875eca15fc.png)

**Comment by SangwonOh** [comment]
@zygocact Hi. I reproduced a issue. I will fix this problem very soon. Stay tuned! Thanks.

**Comment by SangwonOh** [comment]
@zygocact We fixed an issue that prevented playback in firefox when using webrtcConfig.timeoutMaxRetry . Please check with latest OvenPlayer 0.10.15 version. thank you.

You can load latest OvenPlayer by adding version at importing script.
`<script src="https://cdn.jsdelivr.net/npm/ovenplayer@0.10.15/dist/ovenplayer.js"></script>`

**Comment by zygocact** [comment]
Sorry for the late reply, my country was having a violent revolution, and I didn't have internet for a while.

I tested it out, and it works as before. Thank you for fixing the issue.
And by that I mean that webrtcConfig.timeoutMaxRetry doesn't do anything like before, instead of breaking the player 😃

I guess this can be closed now.

**Comment by SangwonOh** [comment]
For reference, `webrtcConfig.timeoutMaxRetry` works when the PeerConnection is not successfully connected within the specified time for some reason. Thanks for reporting the issue. Gook luck.
