### ISSUE TITLE
Expose OvenPlayer docs GitBook as GitHub repo

### ISSUE THREAD

**Issue by command-tab** [AirenSoft/OvenPlayer#249]
Could the OvenPlayer GitBook docs be exposed as a GitHub repo similar to how the OvenMediaEngine GitBook docs are? I have a fix to submit for the OvenPlayer docs, and it seems like it would be easier to submit a GitHub PR than to be added as an individual contributor of the OvenPlayer GitBook.

Thanks!

**Comment by SangwonOh** [comment]
@command-tab Yes. I'll configure GitHub on the OvenPlayer GitBook and let you know.

**Comment by SangwonOh** [comment]
We linked the GitBook with Git Sync. The documentations are in `./docs` directory. We look forward to everyone's contributions. thank you.

**Comment by command-tab** [comment]
Fantastic! Thank you!
