### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenPlayer#252]
I'm pulling the latest Ovebplayer from: <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>

and can't go full screen. The player on the demo page won't go full screen either. 

I noticed a change was made 3 days ago, perhaps some error there?

**Comment by fullstackdelay** [comment]
I can confirm this problem.

Going back to version 0.10.14 solves it.

**Comment by SangwonOh** [comment]
I can confirm this problem too. I'll have to check it out.

**Comment by SangwonOh** [comment]
This issue has been resolved in v0.10.16. In v0.10.15, there was a problem not only in full screen but also in other UIs. Thank you for reporting this issue.

**Comment by SangwonOh** [comment]
Consider it resolved and close the issue. Please reopen for further discussion.
