### ISSUE TITLE
Is it possible to ingest MPEG2 TS with https playback using TLS security?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenPlayer#255]

**Comment by SangwonOh** [comment]
@Mariano245 Hi. What does 'ingest MPEG2 TS' mean? Could you explain a little bit more?

Playback using TLS is possible by setting the TLS configurations in OvenMediaEngine.  A detailed explanation is here. https://airensoft.gitbook.io/ovenmediaengine/streaming/tls-encryption

**Comment by Mariano245** [comment]
I have an encoder to transmit a udp://ip:port stream.
That is I want to stream MPEG-2 TS and play HLS with https (TLS)

**Comment by SangwonOh** [comment]
@Mariano245 
MPEG-2 TS live source inputs are detailed here. 
> https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta

As noted above, TLS playback can be found here.
> https://airensoft.gitbook.io/ovenmediaengine/streaming/tls-encryption

This issue is about the OvenMediaEngine rather than the player. If you need further discussion, please discuss at https://github.com/AirenSoft/OvenMediaEngine/issues.

**Comment by Mariano245** [comment]
it's ok, thank you very much
