### ISSUE TITLE
How too use ovenplayer demo site?

### ISSUE THREAD

**Issue by pto199** [AirenSoft/OvenPlayer#257]
I setup ovenmedia engine through docker on my unraid server
I started my steam with OBS.  It is working and Ovenmedia engine logs show the connection

I goto demo.ovenplayer.com and enter ws://MYIP:3333/app/stream?transport=tcp and select add source then hit play.  It spins for a bit then stops and flashes "connection with low latency terminated unexpectedly ".  It then spins again and stops again and the cycle repeats.  This is the log from ovenmediaengine server and what it shows.

`Video Track #0: Bypass(true) Bitrate(10.00Mb) codec(1, H264) resolution(3440x1440) framerate(60.00fps) timebase(1/1000)
Audio Track #1: Bypass(true) Bitrate(160.00Kb) codec(6, AAC) samplerate(1.0K) format(s16, 16) channel(stereo, 2) timebase(1/1000)
Audio Track #2: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(s16, 16) channel(stereo, 2) timebase(1/48000)[0m
[37m[2022-01-22 16:20:47.339] I [SPRTMP-T1935:32] MediaRouter | mediarouter_stream.cpp:54 | Trying to create media route stream: name(stream) id(1037098710)[0m
[37m[2022-01-22 16:20:47.339] I [SPRTMP-T1935:32] Monitor | application_metrics.cpp:57 | Create StreamMetrics(stream/e377564b-928b-4213-b98c-b5db440ecdc7/default/#default#app/stream/o) for monitoring[0m
[37m[2022-01-22 16:20:47.339] I [SPRTMP-T1935:32] Transcoder | transcoder_stream.cpp:100 | [#default#app/stream(21)] Transcoder input stream has been started. Status : (1) Decoders, (0) Encoders[0m
[37m[2022-01-22 16:20:47.362] I [Decaac:42] Transcoder | decoder_aac.cpp:223 | [#default#app/stream(21)] input stream information: [audio] aac (LC), 48000 Hz, stereo, fltp, 117 kbps, timebase: 1/1000, frame_size: 1024[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] WebRTC Publisher | rtc_stream.cpp:279 | Unsupported codec(Audio/AAC) is being input from media track[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] WebRTC Publisher | rtc_stream.cpp:353 | WebRTC Stream has been created : stream/1037098710
Rtx(FALSE) Ulpfec(FALSE) JitterBuffer(FALSE) PlayoutDelay(FALSE min:0 max: 0)[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] Publisher | stream.cpp:181 | WebRTC Publisher Application application has started [stream(1037098710)] stream (MSID : 0)[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] HLS | hls_packetizer.cpp:152 | [#default#app/stream] HLS: Packetizer will be reset: 0[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] Publisher | stream.cpp:181 | HLS Publisher Application application has started [stream(1037098710)] stream (MSID : 0)[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] Publisher | stream.cpp:181 | DASH Publisher Application application has started [stream(1037098710)] stream (MSID : 0)[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] Publisher | stream.cpp:181 | LLDASH Publisher Application application has started [stream(1037098710)] stream (MSID : 0)[0m
[37m[2022-01-22 16:20:47.380] I [OutboundWorker:34] Publisher | stream.cpp:181 | OVTPublisher Application application has started [stream(1037098710)] stream (MSID : 0)[0m
[37m[2022-01-22 16:20:47.381] I [AW-DASH0:37] DASH | dash_packetizer.cpp:271 | [#default#app/stream] DASH: init_audio.m4s has created[0m
[37m[2022-01-22 16:20:51.556] I [AW-DASH0:37] DASH | dash_packetizer.cpp:237 | [#default#app/stream] DASH: init_video.m4s has created[0m
[37m[2022-01-22 16:20:59.883] I [AW-LLDASH0:38] LLDASH | cmaf_packetizer.cpp:765 | [0x14fe3800c070] LLDASH segment is ready to stream [#default#app/stream], segment duration: 5.000000s, count: 1[0m
[91m[2022-01-22 16:20:59.883] E [AW-LLDASH0:38] LLDASH | cmaf_packetizer.cpp:866 | [#default#app/stream] Because the jitter is too high, playback may not be possible (2022-01-23T00:20:47.380+00:00 => 2022-01-23T00:20:48.380+00:00, 1000ms)
- Elapsed: 12503ms (current: 1642897259883ms, start: 1642897247380ms)
- Jitter: 4186ms (4186ms - 0ms), correction: 0ms => 1000ms (-1000ms)
- Stream delta: 8317ms
- Video: last PTS: 12483ms, start: 4166ms, delta: 8317ms
- Audio: last PTS: 12480ms, start: 0ms, delta: 12480ms
- A-V Sync: 4163 (A: 12480, V: 8317)[0m
[91m[2022-01-22 16:21:07.412] E [AW-LLDASH0:38] LLDASH | cmaf_packetizer.cpp:866 | [#default#app/stream] Because the jitter is too high, playback may not be possible (2022-01-23T00:20:48.380+00:00 => 2022-01-23T00:20:49.380+00:00, 2000ms)
- Elapsed: 20032ms (current: 1642897267412ms, start: 1642897247380ms)
- Jitter: 3182ms (4182ms - 1000ms), correction: 1000ms => 2000ms (-1000ms)
- Stream delta: 15850ms
- Video: last PTS: 20016ms, start: 4166ms, delta: 15850ms
- Audio: last PTS: 19989ms, start: 0ms, delta: 19989ms
- A-V Sync: 4139 (A: 19989, V: 15850)[0m
[37m[2022-01-22 16:21:08.227] I [AW-DASH0:37] DASH | dash_packetizer.cpp:801 | [#default#app/stream] DASH: Segments are ready to stream, segment duration: 5.000000s, count: 3[0m
[37m[2022-01-22 16:21:16.549] I [AW-HLS0:36] HLS | hls_packetizer.cpp:496 | [#default#app/stream] HLS: Segments are ready, segment duration: 5.000000s, count: 3[0m
[91m[2022-01-22 16:21:16.549] E [AW-LLDASH0:38] LLDASH | cmaf_packetizer.cpp:866 | [#default#app/stream] Because the jitter is too high, playback may not be possible (2022-01-23T00:20:49.380+00:00 => 2022-01-23T00:20:50.380+00:00, 3000ms)
- Elapsed: 29169ms (current: 1642897276549ms, start: 1642897247380ms)
- Jitter: 2185ms (4185ms - 2000ms), correction: 2000ms => 3000ms (-1000ms)
- Stream delta: 24984ms
- Video: last PTS: 29150ms, start: 4166ms, delta: 24984ms
- Audio: last PTS: 29141ms, start: 0ms, delta: 29141ms
- A-V Sync: 4157 (A: 29141, V: 24984)[0m
[37m[2022-01-22 16:21:52.925] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:201 | New client is connected: <ClientSocket: 0x14fe70001130, #22, Connected, TCP, Nonblocking, 192.168.1.1:39723>[0m
[37m[2022-01-22 16:21:52.935] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:114 | A new session has started playing #default#app/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)[0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] WebRTC Publisher | webrtc_publisher.cpp:605 | Stop command received : #default#app/stream/100[0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:136 | A session has been stopped playing #default#app/stream on the WebRTC publisher. Concurrent Viewers[WebRTC(0)/Stream total(0)/App total(0)][0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:335 | Client is disconnected: <WebSocketClient: 0x14fe70005550, <ClientSocket: 0x14fe70001130, #22, Closed, TCP, Nonblocking, 192.168.1.1:39723>> (#default#app / stream, ufrag: local: CPLhw8, remote: e21f522d)[0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] WebRTC Publisher | webrtc_publisher.cpp:605 | Stop command received : #default#app/stream/100[0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:136 | A session has been stopped playing #default#app/stream on the WebRTC publisher. Concurrent Viewers[WebRTC(0)/Stream total(0)/App total(0)][0m
[37m[2022-01-22 16:22:08.271] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:335 | Client is disconnected: <WebSocketClient: 0x14fe70005550, <ClientSocket: 0x14fe70001130, #22, Closed, TCP, Nonblocking, 192.168.1.1:39723>> (#default#app / stream, ufrag: local: CPLhw8, remote: e21f522d)[0m
[37m[2022-01-22 16:22:13.895] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:201 | New client is connected: <ClientSocket: 0x14fe70001130, #22, Connected, TCP, Nonblocking, 192.168.1.1:51544>[0m
[37m[2022-01-22 16:22:13.903] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:114 | A new session has started playing #default#app/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)[0m
[33m[2022-01-22 16:22:44.220] W [DQICETmout:12] ICE | ice_port.cpp:400 | Client (session id: 101) has expired[0m
[37m[2022-01-22 16:22:44.220] I [DQICETmout:12] WebRTC Publisher | webrtc_publisher.cpp:671 | IcePort is disconnected. : (#default#app/stream/101) reason(5)[0m
[37m[2022-01-22 16:22:44.243] I [SPRtcSig-T3333:11] WebRTC Publisher | webrtc_publisher.cpp:605 | Stop command received : #default#app/stream/101[0m
[37m[2022-01-22 16:22:44.243] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:136 | A session has been stopped playing #default#app/stream on the WebRTC publisher. Concurrent Viewers[WebRTC(0)/Stream total(0)/App total(0)][0m
[37m[2022-01-22 16:22:44.243] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:335 | Client is disconnected: <WebSocketClient: 0x14fe70004d70, <ClientSocket: 0x14fe70001130, #22, Closed, TCP, Nonblocking, 192.168.1.1:51544>> (#default#app / stream, ufrag: local: 3pReI5, remote: 61c33cb1)[0m
[37m[2022-01-22 16:22:46.254] I [SPRtcSig-T3333:11] Signalling | rtc_signalling_server.cpp:201 | New client is connected: <ClientSocket: 0x14fe70001130, #22, Connected, TCP, Nonblocking, 192.168.1.1:20390>[0m
[37m[2022-01-22 16:22:46.263] I [SPRtcSig-T3333:11] Monitor | stream_metrics.cpp:114 | A new session has started playing #default#app/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)[0m`

**Comment by SangwonOh** [comment]
@pto199 Hi. It seems that player cannot connect to OvenMediaEngine with WebRTC. Did you open all the necessary ports when using your server and ovenmediaengine docker? Ports required by default are listed here. 
https://airensoft.gitbook.io/ovenmediaengine/getting-started#ports

**Comment by SangwonOh** [comment]
@pto199 Is there any new progress?

**Comment by NK0D1NG** [comment]
Hello there,
I saw this open issue and it seems to be stale.

But I have the same question and similar problems:
I can't get WebRTC streaming work with the public demo-player.

Logs from OME (running as docker container locally):
```
New client is connected: <ClientSocket: 0x7f903c009840, #29, Connected, TCP, Nonblocking, 172.20.0.1:48964>
ome-1  | [2022-10-22 09:41:57.301] I [SPRtcSig-T3333:10] Monitor | stream_metrics.cpp:114  | A new session has started playing #vcs#pgm/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)
ome-1  | [2022-10-22 09:42:28.152] W [DQICETmout:12] ICE | ice_port.cpp:400  | Client (session id: 111) has expired
ome-1  | [2022-10-22 09:42:28.152] I [DQICETmout:12] WebRTC Publisher | webrtc_publisher.cpp:797  | IcePort is disconnected. : (#vcs#pgm/stream/111) reason(5)
ome-1  | [2022-10-22 09:42:28.152] I [DQICETmout:12] WebRTC Publisher | webrtc_publisher.cpp:701  | Stop command received : #vcs#pgm/stream/111
ome-1  | [2022-10-22 09:42:28.168] I [DQICETmout:12] Monitor | stream_metrics.cpp:136  | A session has been stopped playing #vcs#pgm/stream on the WebRTC publisher. Concurrent Viewers[WebRTC(0)/Stream total(0)/App total(0)]
ome-1  | [2022-10-22 09:42:28.168] I [DQICETmout:12] Signalling | rtc_signalling_server.cpp:365  | Client is disconnected: HttpConnection(0x7f903c0087f0) : WebSocket <ClientSocket: 0x7f903c009840, #29, Connected, TCP, Nonblocking, 172.20.0.1:48964> TLS(Disabled) (#vcs#pgm / stream, ufrag: local: R3LAPE, remote: e16acb02)
ome-1  | [2022-10-22 09:42:30.277] I [SPRtcSig-T3333:10] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7f903c0089d0, #29, Connected, TCP, Nonblocking, 172.20.0.1:48978>
ome-1  | [2022-10-22 09:42:30.302] I [SPRtcSig-T3333:10] Monitor | stream_metrics.cpp:114  | A new session has started playing #vcs#pgm/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)
ome-1  | [2022-10-22 09:43:01.171] W [DQICETmout:12] ICE | ice_port.cpp:400  | Client (session id: 112) has expired
ome-1  | [2022-10-22 09:43:01.171] I [DQICETmout:12] WebRTC Publisher | webrtc_publisher.cpp:797  | IcePort is disconnected. : (#vcs#pgm/stream/112) reason(5)
ome-1  | [2022-10-22 09:43:01.171] I [DQICETmout:12] WebRTC Publisher | webrtc_publisher.cpp:701  | Stop command received : #vcs#pgm/stream/112
ome-1  | [2022-10-22 09:43:01.185] I [DQICETmout:12] Monitor | stream_metrics.cpp:136  | A session has been stopped playing #vcs#pgm/stream on the WebRTC publisher. Concurrent Viewers[WebRTC(0)/Stream total(0)/App total(0)]
ome-1  | [2022-10-22 09:43:01.185] I [DQICETmout:12] Signalling | rtc_signalling_server.cpp:365  | Client is disconnected: HttpConnection(0x7f90f8001890) : WebSocket <ClientSocket: 0x7f903c0089d0, #29, Connected, TCP, Nonblocking, 172.20.0.1:48978> TLS(Disabled) (#vcs#pgm / stream, ufrag: local: TUZJmo, remote: 9d093270)
ome-1  | [2022-10-22 09:43:03.276] I [SPRtcSig-T3333:10] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7f903c008cb0, #29, Connected, TCP, Nonblocking, 172.20.0.1:48992>
ome-1  | [2022-10-22 09:43:03.300] I [SPRtcSig-T3333:10] Monitor | stream_metrics.cpp:114  | A new session has started playing #vcs#pgm/stream on the WebRTC publisher. WebRTC(1)/Stream total(1)/App total(1)
```

Logs from browser network tab:
![grafik](https://user-images.githubusercontent.com/88783636/197332955-d3f303ca-16f0-4b5c-99dd-4a9db0d08894.png)

As you can see the player tries to connect over and over again but the session somehow dies. I can connect from my host to all relevant ports inside the container:
```
nc -zv localhost 3333
Connection to localhost 3333 port [tcp/*] succeeded!

nc -zv localhost 3478
Connection to localhost 3478 port [tcp/*] succeeded!

nc -zvu localhost 10000
Connection to localhost 10000 port [udp/*] succeeded!

nc -zvu localhost 10001
Connection to localhost 10001 port [udp/*] succeeded!

nc -zvu localhost 10002
Connection to localhost 10002 port [udp/*] succeeded!

# ... (until 10005 - all ports for ice candidates working)
```
So the question is: Why is it still not working?

If I look into the messages which are send between the browser and OME I see these messages:
![grafik](https://user-images.githubusercontent.com/88783636/197333244-1a30f9df-a360-4fae-82e6-e08b17393b6d.png)

The first IP-Adress is my public IP, the second IP is the IP adress of the docker container OME is running in. `localhost` or `127.0.0.1` is missing. So I think the player tries to connect to my public IP (which fails) and to the docker IP (which fails, too). Instead it should resolve to localhost (or the docker host which would also be localhost).

**Comment by getroot** [comment]
@NK0D1NG 
- OME_TCP_RELAY_ADDRESS=*:3478
- OME_ICE_CANDIDATES=*:10000-10005/udp

Try changing this environment variable to your public IP instead of *.

**Comment by NK0D1NG** [comment]
Hey @getroot 

thanks for the quick response. I will try that.

I also see this in the browser console:
WebRTC: ICE failed, add a STUN server and see about:webrtc for more details

**Comment by getroot** [comment]
@NK0D1NG 
Yes, the problem is that the packets sent by your browser cannot reach the OvenMediaEngine's IceCandidate. Also try using TCP method with TcpRelay.

**Comment by NK0D1NG** [comment]
OME_TCP_RELAY_ADDRESS=*:3478
    OME_ICE_CANDIDATES=*:10000-10005/udp

Try changing this environment variable to your public IP instead of *.

->> did not work

I tried it with a local index.html file containing
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OvenPlayer</title>
</head>

<body>
    <!-- OvenPlayer will be initialized inside this element. -->
    <div id="player_id"></div>

    <!-- Load OvenPlayer via CDN -->
    <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>

    <script>

        // Initialize OvenPlayer
        const player = OvenPlayer.create('player_id', {
            sources: [
                {
                    label: 'label_for_webrtc',
                    // Set the type to 'webrtc'
                    type: 'webrtc',
                    // Set the file to WebRTC Signaling URL with OvenMediaEngine 
                    file: 'ws://localhost:3333/pgm/stream'
                }
            ]
        });
    </script>
</body>

</html>
```

which ends in the exact same problems.

**Comment by getroot** [comment]
nc -zvu localhost 10000 , but also nc -zvu `<Public IP> `10000 ? If you want to use localhost, put OME_ICE_CANDIDATES=127.0.0.1:10000-10005/udp. However, this may work with Chrome's security policy. Chrome strictly enforces security policies when accessing localhost. I haven't tested it with localhost, so I don't know for sure. If possible, try testing with a public IP.

**Comment by NK0D1NG** [comment]
I changed
```
OME_TCP_RELAY_ADDRESS=*:3478
OME_ICE_CANDIDATES=*:10000-10005/udp
```

to all possible variations of public IP or localhost, 127.0.0.1 like:
```
    - OME_TCP_RELAY_ADDRESS=127.0.0.1:3478
    - OME_ICE_CANDIDATES=127.0.0.1:10000-10005/udp
```

which seem to affect the urls in the WebRTC messages:
![grafik](https://user-images.githubusercontent.com/88783636/197335811-9f316eda-21b9-4f18-ab17-b161285a423c.png)

But the player is still not able to connect...

**Comment by NK0D1NG** [comment]
I am working locally only so using my public IP will fail. I am testing with Firefox atm

**Comment by getroot** [comment]
I'm testing using a private IP like 192.168.0.1 instead of 127.0.0.1.

**Comment by NK0D1NG** [comment]
So you are using your local machine's IP of your private network not localhost right? So that should work for WebRTC on the same machine running OME in docker if that IP is explicitly set in the Environment?

**Comment by getroot** [comment]
no. Exactly I have another linux machine next to me. I'm not sure. I've never tried it on localhost, so I don't know the details. I think this is most likely a problem with your network settings. It would be good to test it in various ways. It seems like a good attempt to use Docker's IP.

**Comment by NK0D1NG** [comment]
Thank you @getroot 
your comment 

> I'm testing using a private IP like 192.168.0.1 instead of 127.0.0.1.

was leading me into the right direction. Somehow using my machines IP in my private network (like 192.168.x.x) in the environment for tcp relay and ice candidates did the trick. Still not sure why localhost or 127.0.0.1 is not working but it seems more like a browser security policy than a network issue to me, because I am still referencing my own machine itself :)

**Comment by NK0D1NG** [comment]
For me this issue could be closed, because using the ovenplayer demo is working properly and the original thread by @pto199 seems to be stale?

**Comment by NK0D1NG** [comment]
This seems to be the reason why it didn't work for me in a localhost environment (I used Firefox):
https://mediasoup.discourse.group/t/firefox-ice-failed-add-a-stun-server-and-see-about-webrtc-for-more-details/805

**Comment by getroot** [comment]
@NK0D1NG Thanks for sharing good information.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
