### ISSUE TITLE
Poor functioning of OvenPlayer on Windows device

### ISSUE THREAD

**Issue by LydiaTM** [AirenSoft/OvenPlayer#259]
Hi, video is choppy on windows devices. However, video looks good on linux devices (althought with some delay). 

After initialising the transmission with OBS, I run the following html file:

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OvenPlayer</title>
</head>
<body>
    
    <div id="player_id"></div>
    
    <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>
    <script>
        // Initialize OvenPlayer
        const player = OvenPlayer.create('player_id', {
            sources: [
                {
                    label: 'WebRTC 1080P',
                    // Set the type to 'webrtc'
                    type: 'webrtc',
                    // Set the file to WebRTC Signaling URL with OvenMediaEngine 
                    file: 'ws://192.168.***.***:3333/app/stream'
                }
            ]
        });
    </script>
</body>
</html>

Sorry for the inconvenience and thank you in advance.

**Comment by getroot** [comment]
Please refer to the document below.

https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#streaming-is-not-smooth

**Comment by LydiaTM** [comment]
I have not added transport variable to the url because <TcpForce> is set to true. Also, it can not be a network issue because both devices (Linux and Windows) are connected to the same network.

**Comment by getroot** [comment]
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#1.-if-you-are-using-transcoding-as-bypass-in-ovenmediaengine-and-streaming-does-not-work-in-all-play

Different browsers have different capabilities of the H264 decoder.
What OBS settings are you using?

The most obvious is to set bframes=0 in the baseline profile.

**Comment by getroot** [comment]
I realized one thing. In GITBOOK, the scroll does not automatically move to the position I want. Check out part `1. If you are using...` in the `"Streaming is not smooth"` session on that page.

**Comment by LydiaTM** [comment]
I have use following OBS settings:
![stream](https://user-images.githubusercontent.com/100129324/154953266-7429370f-a9a3-4370-af37-259fa37e1408.PNG)
![video](https://user-images.githubusercontent.com/100129324/154953268-4efe6f6c-0f40-4663-9f2e-4a536c979e8a.PNG)

**Comment by LydiaTM** [comment]
I have changed the OBS configuration as indicated in paragraph **1. If you are using..** and the issue has been solved. Thank you very much!
