### ISSUE TITLE
OvenMediaPlayer Link

### ISSUE THREAD

**Issue by natzakaria** [AirenSoft/OvenPlayer#265]
When user right clicks on the embedded stream it shows the About with a version showing up.
Clicking it takes you to github
Is there away to disable this feature
![Screenshot 2022-04-15 at 9 58 23 AM](https://user-images.githubusercontent.com/65059352/163506033-b65fa55e-1a0b-49b7-acfe-ff9a0b42ffdb.jpg)
?

**Comment by natzakaria** [comment]
is bump allowed?

**Comment by SangwonOh** [comment]
@natzakaria Hi. We do not provide the ability to disable that feature.
But if you really want to, you can hide the link using css. Thanks.

```css
.op-context-panel {
    display: none;
}
```

**Comment by natzakaria** [comment]
Thanks for the suggestion

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
