### ISSUE TITLE
Livestream LL-HLS delay on mobile 

### ISSUE THREAD

**Issue by parab-aditya** [AirenSoft/OvenPlayer#266]
When testing a LL HLS livestream on mobile browser, if there is some internet instability on broadcaster (source) side, the stream gets delayed, which is expected. But when the connection is back to normal, the steam still remains delayed and doesn't catch up to the live. 
I've included few parameters from HLS.js as well. And yet stream tends to remain lagging. You can simulate unstable internet via Clumsy on windows.

**Comment by getroot** [comment]
OvenPlayer and OvenMediaEngine doesn't support LLHLS yet, 
What server did you use for LLHLS?

**Comment by parab-aditya** [comment]
I'm using Nimble to stream LL HLS. OvenPlayer does seem to play LLHLS without any issues. The only issue is the one I  mentioned above. I have been testing it pretty thoroughly.

**Comment by getroot** [comment]
Of course, OvenPlayer uses hls.js, so the LLHLS function can work. But Oven- doesn't support LLHLS yet. It would be better to ask this to hls.js or Nimble.
