### ISSUE TITLE
Image / Poster has no effect on Audio-only Stream

### ISSUE THREAD

**Issue by genofire** [AirenSoft/OvenPlayer#268]
image should be set to
```html
<video poster="{{options.image}}" />
```

so that html5 could be set the poster on his own.

**Comment by SangwonOh** [comment]
@genofire Hi.

yes. I see what you want. OvenPlayer was creating an `img` element to display the poster. It would be better to replace this with the poster attribute of the video. We will let you know after the patch.

Thanks.

**Comment by genofire** [comment]
How long took it time? Could i speed up, by creating a PR on my own?

**Comment by SangwonOh** [comment]
@genofire Hi. This function (60dba7c6ad99229ab3f0c82f16ec1db15385b3e2) has been made in the master branch. It will be released as version 0.10.19 with a little more other patches. If you are in a hurry, please build the code of the master branch and use it.

**Comment by genofire** [comment]
Oh nice, that was fast

**Comment by SangwonOh** [comment]
@genofire Hi~!. Please check out our latest release v0.10.19. Thanks!

**Comment by genofire** [comment]
Does not work for me ;(

Switch to Audio:
https://v2-dev.media.kukoon.de/play/45da89a7-e5e0-5104-b937-6d4c2d4b6d00

Code:
https://github.com/Kukoon/media-ui/blob/5fffb798b0c9e15632b40ef6aa349c5f48b2d6cf/src/components/VideoPlayer.vue#L21

**Comment by SangwonOh** [comment]
@genofire  Oops. The poster attribute seems to be removed when playback source changes. I will check it again.

**Comment by genofire** [comment]
exact - that was what i am debug, too ;)

**Comment by SangwonOh** [comment]
@genofire Please check out with v0.10.20.

**Comment by genofire** [comment]
Looks good, thanks
