### ISSUE TITLE
Event function

### ISSUE THREAD

**Issue by Byskoven62** [AirenSoft/OvenPlayer#273]
Hello.
Sorry I bother you again: P 
But I need some help, I am not a php coder so I do not know much about this but is this feature used properly?
Or maybe there is someone who can make an example of how to use this "event" * on('stateChanged') *
```
			  player.on("stateChanged", function (playing){
			$(".player-wrapper1").show();
			$(".fadein").hide();
        });
```

**Comment by bchah** [comment]
In Javascript, it gives you an object with 'prevstate' and 'newstate' values, which you can pass into a new function e.g.

```
player.on("stateChanged", (state)=>{
if (state.prevstate == "playing" && state.newstate == "error") {
    console.log("Playback error!");
}
});
```

**Comment by Byskoven62** [comment]
@bchah  Thanks for explaining it to me :)
