### ISSUE TITLE
Delay or Latency in OvenPlayer

### ISSUE THREAD

**Issue by htliu6** [AirenSoft/OvenPlayer#275]
Execuse me! I wonder where I can collect statistics like RTC delay or latency in OvenPlayer. Thanks!

**Comment by SangwonOh** [comment]
@htliu6 We do not yet provide an interface to monitor stream status. But I think it would be a useful feature if added to the player. We will try to add monitoring function soon. The following issues can also be dealt with: https://github.com/AirenSoft/OvenPlayer/issues/274

**Comment by htliu6** [comment]
@SangwonOh Thanks for your kindly reply! What a pity, but I am willing to contribute for this feature.
