### ISSUE TITLE
Duplicate stream when viewing two (or more) streams

### ISSUE THREAD

**Issue by kage212** [AirenSoft/OvenPlayer#277]
Hello OME team, I detected when a user in the same browser tries to view two different streams they appear identical.
This issue happens at least with Chrome and Firefox when in the same browser in different tabs (not sure on private but probably not happen), another thing in Brave works perfectly.
![image](https://user-images.githubusercontent.com/100566598/172173083-c16dae91-3c25-45f3-bf66-93cb83802b20.png)

Two pictures showing every stream:
![image](https://user-images.githubusercontent.com/100566598/172149305-e6329c8d-97c8-4a16-963c-213c188addbb.png)
![image](https://user-images.githubusercontent.com/100566598/172149363-1a6b72bf-d8e0-4e23-87fb-028d1bf7b308.png)

I dont know if is a bug or not but probably.

The first thing I though was the player must have a unique id to prevent something weird between tabs but no.
this.player = OvenPlayer.create(this.uid, { sources: this.sources, waterMark, autoStart: true });

Thanks for your time.

**Comment by SangwonOh** [comment]
@kage212 Hi. I think since it's a different tab, the player's id doesn't matter. I can't reproduce. In my tests, different streams are played normally.

First please check both streams are signaling to the correct address.

![image](https://user-images.githubusercontent.com/21077319/172350794-429cd638-f067-49f3-9fd8-4a2d78853f17.png)

**Comment by kage212** [comment]
Hello,

1. First of all you need to deploy in a server OME
2. Generate two rtmp urls
3. Open two OvenPlayer demo tabs
4. Put in tab 1 the first link you made, then the second in tab 2
5. Open for example two OBS and stream one color or two different videos
6. Play stream in both tabs
7. You got a duplicate stream view

You CANT test this on localhost, because in localhost does not happen.
