### ISSUE TITLE
ios safari playing webrtc stream,when stream stopped，player state always is playing

### ISSUE THREAD

**Issue by dluobo** [AirenSoft/OvenPlayer#278]
ios safari playing webrtc stream,when stream stopped，player state always is playing.
but macos safari work well。

code：
var state = ovenPlayer.getState();

![微信图片_202206081128122](https://user-images.githubusercontent.com/3862284/172525600-cfba6d55-3d35-43f0-b7bd-7be0d310bae8.jpg)

**Comment by SangwonOh** [comment]
@dluobo Hi. What exactly is the situation when a stream is stopped? If the player does not receive a stream from OME for any reason, the player goes into error state.

**Comment by dluobo** [comment]
I manually stop obs，only ios safari player state is always playing state，other browser player state is error。
The function I am implementing：I monitor the state of the player to realize that if the camera stream is disconnected ，a few moment later reconnected, the stream can be played automatically。

**Comment by SangwonOh** [comment]
@dluobo My test bed on IOS 15.5, player state going to error. Is there a more information?

https://user-images.githubusercontent.com/21077319/173292236-eba38ee5-ad71-408e-b73e-e5abd60218b7.mov

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
