### ISSUE TITLE
Labels for ABR items

### ISSUE THREAD

**Issue by danruser** [AirenSoft/OvenPlayer#279]
Hello
How can I edit the list of options in the list when using ABR?
Like in the picture , to make them more meaningful.
![Resolutions](https://user-images.githubusercontent.com/87206215/172626750-b24941c7-7948-4302-946d-8e8f31e7a7ac.png)

Thank you

**Comment by SangwonOh** [comment]
Hello @danruser . Unfortunately, we have no plans to offer the ability to customize labels. However, you are free to fork this repository and modify the source code.

Source code
> https://github.com/AirenSoft/OvenMediaEngine/issues/777#issuecomment-1149804578

How to build OvenPlayer
> https://airensoft.gitbook.io/ovenplayer/builds

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
