### ISSUE TITLE
Error messages in Firefox: Using five or more STUN/TURN servers causes problems 

### ISSUE THREAD

**Issue by p4block** [AirenSoft/OvenPlayer#280]
On Firefox using the latest OvenPlayer the console spews these messages.

```
WebRTC: Using more than two STUN/TURN servers slows down discovery 2 [ovenplayer.js:1](https://cdn.jsdelivr.net/npm/ovenplayer@0.10.21/dist/ovenplayer.js)
WebRTC: Using five or more STUN/TURN servers causes problems [ovenplayer.js:1](https://cdn.jsdelivr.net/npm/ovenplayer@0.10.21/dist/ovenplayer.js)
```

It still seems to work and may be innocuous. 

However a few versions ago I noticed that I couldn't have more than ~3 players simultaneously on the entire browser (opening Teams/Meet in another tab would start killing streams) That behavior seems to have disappeared as I can now open upwards of 150 players in my browser for testing simultaneously.

**Comment by SangwonOh** [comment]
@p4block Thanks for the report. We will also investigate what kind of problem the above error message can cause.
