### ISSUE TITLE
player.load returns error without playlist

### ISSUE THREAD

**Issue by Nickname863** [AirenSoft/OvenPlayer#281]
When using a workflow where an instance of OvenPlayer is first created and then later on a source is provided via the "load" method.
The current version of the Oven Media player that is provided via the CDN will run into an exception, because in "WebRTCLoader.js" the object "playlistFromOme" is undefined.
![image](https://user-images.githubusercontent.com/33596703/176959175-710b8a68-4cd9-4402-afc6-9f9fda752c9e.png)

This happens as there never was a playlist provided when creating an instance of the player. This behavior doesn't seem intended as the documentation doesn't state, that providing a playlist on player creation is required.

**Comment by getroot** [comment]
Thanks for reporting the bug.
A recent update for OME's playlists seems to break backwards compatibility. This is a bug and will be fixed soon.

**Comment by SangwonOh** [comment]
@Nickname863 Hi! There was a bug in initializing qualityLevel when the load method was called.
Fixed in the latest 0.10.23 version. (https://cdn.jsdelivr.net/npm/ovenplayer@0.10.23/dist/ovenplayer.js)

Thanks for reporting!
