### ISSUE TITLE
 ABR doesn't work on safari mac/ios only chrome.

### ISSUE THREAD

**Issue by linkinblack** [AirenSoft/OvenPlayer#283]
Hello friends, I have been testing the new version that supports ABR, and it only works in chrome on MacOS but in safari both MacOS and iOS DOES NOT WORK, the abr only remains in the lowest quality. Do we have to wait for a version or do we have to make any adjustments?

Cheers

**Comment by getroot** [comment]
LLHLS ABR or WebRTC ABR?
Both ABR works fine on my iOS SAFARI.

**Comment by linkinblack** [comment]
It works for me I can see the transmission, but it does not adjust to the bandwidth, it always shows me the lowest, in mac chrome with ovenplayer it works without problems, but in safari macos/ios with ovenplayer it only shows the lowest quality available, tested on macos monterrey, ios15 and ios 16.

Cheers

**Comment by getroot** [comment]
Hmm... Are you talking about WebRTC playback or LLHLS playback? Please provide more detailed information to help us analyze the cause of the problem.

**Comment by linkinblack** [comment]
everything is in LLHLS. Thanks for your help

**Comment by linkinblack** [comment]
![Captura de Pantalla 2022-07-18 a la(s) 12 45 06](https://user-images.githubusercontent.com/12145134/179562008-c9d369eb-ec3b-4eea-9e36-ddb4439e741d.png)
![Captura de Pantalla 2022-07-18 a la(s) 12 45 47](https://user-images.githubusercontent.com/12145134/179562016-8625ff4a-1fea-47b5-9de1-5ea8fa60ba6a.png)
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="3",NAME="none",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="chunklist_3_audio_llhls.m3u8?session=33_oML10U9B"

#EXT-X-STREAM-INF:BANDWIDTH=3760000,RESOLUTION=1280x720,FRAME-RATE=30.0,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="3"
chunklist_0_video_llhls.m3u8?session=33_oML10U9B
#EXT-X-STREAM-INF:BANDWIDTH=1360000,RESOLUTION=640x360,FRAME-RATE=24.0,CODECS="avc1.42c01e,mp4a.40.2",AUDIO="3"
chunklist_1_video_llhls.m3u8?session=33_oML10U9B
#EXT-X-STREAM-INF:BANDWIDTH=672000,RESOLUTION=320x180,FRAME-RATE=24.0,CODECS="avc1.42c00d,mp4a.40.2",AUDIO="3"
chunklist_2_video_llhls.m3u8?session=33_oML10U9B

**Comment by getroot** [comment]
Maybe Apple's native player is judging your network to be slow. It's hard to analyze the problem because on my iOS it plays fine at the highest quality.

Testing with other players will help us analyze.

https://www.theoplayer.com/test-your-stream-hls-dash-hesp

After accessing the demo page above, turn on "Use your own stream" and put your URL, can you test it and share the results?

**Comment by linkinblack** [comment]
my configuration file
<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>danceparty</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.l.google.com:19302</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>

				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>3333</Port>
				
				<TLSPort>3334</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>danceparty.cl</Distribution>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
				<TLS>
					<CertPath>/etc/letsencrypt/live/streaming.danceparty.cl/fullchain.pem</CertPath>
					<KeyPath>/etc/letsencrypt/live/streaming.danceparty.cl/privkey.pem</KeyPath>
					<ChainCertPath>/etc/letsencrypt/live/streaming.danceparty.cl/fullchain.pem</ChainCertPath>
				</TLS>
			</Host>

			

			

			
			
			
			<Applications>
				<Application>
					<Name>danceparty</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>

							
							
							<Playlist>
								<Name>abr</Name>
								
								<FileName>danceparty</FileName>

								
								
								<Rendition>
									<Name>HD</Name>
									<Video>HD</Video>
									<Audio>bypass_audio</Audio>
								</Rendition>
								<Rendition>
									<Name>SD</Name>
									<Video>SD</Video>
									<Audio>bypass_audio</Audio>
								</Rendition>
								<Rendition>
									<Name>Low</Name>
									<Video>Low</Video>
									<Audio>bypass_audio</Audio>
								</Rendition>
							</Playlist>
							<Encodes>
								<Audio>
									<Name>bypass_audio</Name>
									<Bypass>true</Bypass>
								</Audio> 							
								<Video>
									<Name>HD</Name>
									<Codec>h264</Codec>
									<Bitrate>3600000</Bitrate>
									<Framerate>30</Framerate>
									<Width>1280</Width>
									<Height>720</Height>
									<Preset>faster</Preset>
								</Video>
								<Video>
									<Name>SD</Name>
									<Codec>h264</Codec>
									<Bitrate>1200000</Bitrate>
									<Framerate>24</Framerate>
									<Width>640</Width>
									<Height>360</Height>
									<Preset>faster</Preset>
								</Video>
								 <Video>
                                                                        <Name>Low</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>512000</Bitrate>
                                                                        <Framerate>24</Framerate>
                                                                        <Width>320</Width>
                                                                        <Height>180</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
							
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.5</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by gregfr** [comment]
We have just tested this problem (ios Safari) with 3 demo players and an ABR stream from OME:
- videojs shows 3 s delay
- ovenplayer shows 20 s delay
- theoplayer shows either 3 or 20 s delay (not predictable)

Regards

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
Please test with the latest player and browser, and if the problem persists, please open a new issue.
