### ISSUE TITLE
Access a player callback function that indicates that streaming has started

### ISSUE THREAD

**Issue by dprisikar** [AirenSoft/OvenPlayer#284]
Hi,

I am working on a sort of a waiting room, where listeners stay until streaming is started on the other end by the author; using OvenLiveKit for the author's input media. 

I have also noticed that a listener needs to reload a page with the player to connect to an already started streaming, should the listener has already pressed the "play" button before the streaming starts. 

How can I access a callback function that signals that the author has started streaming to the listeners who are already waiting for the streaming (i.e., they have pressed the "play" button before the author started streaming)?

Anyone's help would be very much appreciated!

**Comment by IanMitchell77** [comment]
Not a particularly nice way but the player could keep trying to play every second or so when there is an error.

**Comment by getroot** [comment]
OvenMediaEngine's AdmissionWebhooks allows you to receive events with callback urls when a stream starts/stops.

https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks

Or you could periodically poll streams for information.

https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost/application/stream

After this, it is the role of the application.

Like OvenSpace(https://space.ovenplayer.com/) (https://github.com/AirenSoft/OvenSpace), you can periodically poll your server for stream information, or, smarter, your server can push events over WebSockets to all users. Other than that, there are many ways.

**Comment by dprisikar** [comment]
@IanMitchell77 and @getroot, thank you for your inputs.

@getroot is there a simpler way to accomplish this? 

Say, there has to be some callback (not sure if it is accessible through the API, though) that makes the Play button spin, while awaiting the media source. Maybe I can poll that? 

Or, perhaps, one can access the incoming stream directly from the browser somehow?

**Comment by getroot** [comment]
> I have also noticed that a listener needs to reload a page with the player to connect to an already started streaming, should the listener has already pressed the "play" button before the streaming starts.

I don't quite understand the issue you are struggling with. OvenPlayer does not need to reload the page when starting playback. All you have to do is retry in the player. See demo.ovenplayer.com or space.ovenplayer.com.

If you thought that because of this you need to know when a stream starts, this deserves a bit more explanation.

**Comment by getroot** [comment]
Sorry but I only focus on the issues with OvenMediaEngine and OvenPlayer (that alone spends all my time), so I'll make one last comment.

Take a look at the code at demo.ovenplayer.com. demo.ovenplayer.com will automatically try to reconnect if the connection is suddenly disconnected.

**Comment by dprisikar** [comment]
@getroot of course, and thank you very much for your input. You, guys, have built an amazing product, and I hope that, perhaps, me asking questions and making comments here would help you in your further work 😊

**Comment by dprisikar** [comment]
Here is what worked for me:

```
var player = OvenPlayer.create('player_id', {
    "mute": false,
    "volume": 100,
    "sources": [{
        "type": "webrtc",
        "file": "wss://..."
    }]
});

player.on('error', (event) => {
      reloadPlayer();   
});

function reloadPlayer(){
    player.load( 
      sources = [{
        "type": "webrtc",
         "file": "wss://..."
    }] 
    );

```
