### ISSUE TITLE
Event handler on('stateChanged') is not firing up when state of the player changes

### ISSUE THREAD

**Issue by dprisikar** [AirenSoft/OvenPlayer#287]
Hi,

I am trying to catch the "error" state of the player every time an error occurs. I am using on('stateChanged') for this. 

However, on('stateChanged') does not always execute when the state of the player changes. I can verify this manually in the browser's console with player.getState()

I guess, I could time-out player.getState(), and fire it up every few second or so to monitor the player's state. But, I guess, there should be a better way, because, otherwise, why else would we need event handlers, like on('stateChanged')?

Any thoughts on what I am missing and how to make sure I catch "error" state every time it occurs?

Below is my code. When "error" state is detected, the loaded player instance is removed and a new one is built after some time. This is until there is no more "error" state. It's plain JS inside an HTML page, running this in Chrome/Safari.

```
<script>
// Start player on load
var player = "";
   // Initialize OvenPlayer
    player = OvenPlayer.create('player_id', {
    "autoStart": true,
    "mute": false,
    "volume": 100,
    "sources": [{
        "type": "webrtc",
        "file": "wss://demo..."
    }]
});

// Handling player's "error" state
player.on('stateChanged', (event) => {
    console.log(event.newstate);
    if (event.newstate == "error"){
      restartPlayer();   
    } 
});

function restartPlayer(){
  console.log("restart");
  var playerState = player.getState();
    console.log("state => " + playerState);
  if (playerState == "error") {
    player.remove();
    player = OvenPlayer.create('player_id', {
    "autoStart": true,
    "mute": false,
    "volume": 100,
    "sources": [{
        "type": "webrtc",
        "file": "wss://demo..."
    }]
}); 
 restartTimeout = setTimeout(function() {restartPlayer()}, 60000);
  } 
 }
</script>
```

Any help is highly appreciated!

**Comment by SangwonOh** [comment]
@dprisikar Hi. The error handler will work fine.
```javascript
player.on('error', (event) => {
    restartPlayer();   
});
```

**Comment by dprisikar** [comment]
@SangwonOh, thank you for your reply and your suggestion.

I have tried that, but, unfortunately, the error handler does not detect a new error either. 

To be a bit more clear, it works on the first player load (detects the "error" state fine). But after the player is started ("playing" or "idle" state), and an error occurs (the player state goes to "error" again), neither of these two execute:

```
player.on('stateChanged', (event) => {
    if (event.newstate == "error"){
      restartPlayer();   
    } 
});
```
 or 

```
player.on('error', (event) => {
    restartPlayer();   
});
```

**Comment by IanMitchell77** [comment]
the error event is not documented at https://airensoft.gitbook.io/ovenplayer/api-reference/events I notice @SangwonOh

**Comment by SangwonOh** [comment]
@dprisikar Add `player = null //<--- insert` works fine?
In addition, in what condition are you encountering an error?
```
function restartPlayer(){
  console.log("restart");
  var playerState = player.getState();
    console.log("state => " + playerState);
  if (playerState == "error") {
    player.remove();
    player = null //<--- insert
    player = OvenPlayer.create('player_id', {
    "autoStart": true,
    "mute": false,
    "volume": 100,
    "sources": [{
        "type": "webrtc",
        "file": "wss://demo..."
    }]
}); 
```

[IanMitchell77](https://github.com/IanMitchell77) Oh manual must be updated! Thanks.

**Comment by IanMitchell77** [comment]
@dprisikar - in restartPlayer why remove and then make a new player? try just calling the load API with just the details of the stream...

**Comment by dprisikar** [comment]
@IanMitchell77 , thanks for your suggestion! It does sound like a great idea, and I am already trying it.

One particular new issue that arises from this implementation is that as soon as the new player.load() takes place, the player goes in the earlier state, which is "idle", and executes the piece of code that is specified for the "idle" state. However, in a few millisecond, an error occurs (setting the state to "error"), and the player.load() function is fired again. 

I have tried to setting up an if condition for the state == "idle", then wait for a callback from the player with player.on("ready", ...), and executing another player.getState() to check if the state is still == "idle", and only if this condition is met execute the code for "idle". 

However, the function inside player.on("ready",...) is never executed, and I can't think of any other callback function that would allow me to verify if state=="idle" is persistent, and no immediate error would follow. 

Hope, it makes sense 😀

**Comment by dprisikar** [comment]
Here is the code:

```
<script>
// Start player on load
var player = "";
   // Initialize OvenPlayer
    player = OvenPlayer.create('player_id', {
    "autoStart": true,
    "mute": false,
    "volume": 100,
    "sources": [{
        "type": "webrtc",
        "file": "wss://demo..."
    }]
});

// Handling player's "error" state
player.on('stateChanged', (event) => {
    console.log(event.newstate);
    if (event.newstate == "error"){
      restartPlayer();   
    } 
});

function restartPlayer(){
  var playerState = player.getState();
  if (playerState == "error") {
    player.load( 
      sources = [{
        "type": "webrtc",
         "file": "wss://demo..."
    }] 
    );
}); 
 restartTimeout = setTimeout(function() {restartPlayer()}, 60000);
  } 

} else if (playerState == "playing" ){
// Execute code for "playing"

} else if (playerState == "idle" ){

//  --> HERE IS THE CALLBACK:
    player.on('ready', () => {  
    console.log("idle state ready!!!" );
// Execute code for "idle"  <-- and THIS is what I want to avoid, executing if "idle" is NOT persistent (immediate "error")   
 }
    });
  } else {
// Execute code for any other state
  }
 }
 }
</script>

```

**Comment by dprisikar** [comment]
Finally, solved this by adding a timed-out function that reloads the player if the "idle" condition persists for 5 seconds. The 5 seconds seems to be the sweet spot for the "idle" persistence check, and the player reloads in 5 seconds as well.

Here is how the code looks:

```
var timeoutIdle = null; 
var timeouts = [];

function reloadPlayer(){
var playerState = player.getState();
  if (playerState == "error" || playerState == "loading") {
    player.load( 
      sources = [{
        "type": "webrtc",
         "file": "wss://..."
    }] 
    );
} else if (playerState == "idle" ) {
   timeoutIdle = setTimeout(handleIdle, 5000);
  } 
 }
    timeouts.push(restartTimeout = setTimeout(function() {reloadPlayer()}, 5000));
  } else if (playerState == "idle" ) { 
   timeoutIdle = setTimeout(handleIdle, 5000);
  } 
 }

function handleIdle(){
  var idleState = player.getState();
      if (idleState == "idle"){
        for (var i = 0; i < timeouts.length; i++) {
        clearTimeout(timeouts[i]);
        }
        timeouts = [];
        } 
        clearTimeout(timeoutIdle);
        timeoutIdle = null;
      }
```
