### ISSUE TITLE
Qualities selection not display on ios 

### ISSUE THREAD

**Issue by scar63** [AirenSoft/OvenPlayer#292]
Hello, 

The qualities selection not display on iphone with safari browser (cf capture)
![Sans titre](https://user-images.githubusercontent.com/43566192/179781027-749634d5-24bf-4937-9538-6bf342c317c7.png)

**Comment by SangwonOh** [comment]
@scar63 Hi. We can't control the quality when playing native HLS in iOS safari.

PS. Your settings UI looks weird. Please check if an error is occurring somewhere.

**Comment by scar63** [comment]
Hello @SangwonOh, thank you for your response.
Ok, I didn't know that you couldn't control the quality on ios...
For the UI settings, I'm the one who hid the source element, because it doesn't make sense to have two inputs (source and quality) for my replays (my sources are 720 and 480 so in the end these are the qualities)

Another thing, I find it a shame not to have kept the poster for the player (ThumbnailTemplate function) and to have replaced it with frame from the retransmission. Isn't it possible to add an option to keep it?

**Comment by SangwonOh** [comment]
@scar63 Hi.
You can use this initialization option. https://airensoft.gitbook.io/ovenplayer/initialization#image

**Comment by scar63** [comment]
@SangwonOh Hi,

Yes I already use this option, but when I set the autostart option to true, the image option does not work and it is a live frame that is displayed...

In the previous version (0.10.12) the behavior was different. 
With the autostart option set to true, the image still displayed (cf ThumbnailTemplate function) ...

**Comment by xavis** [comment]
Hi!

Any news about this issue? I'm reproducing it in 

_macOS Big Sur 11.6.5_
_Safari 15.4_

**Comment by SangwonOh** [comment]
Still can't control quality. However, the UI broken was fixed(89991e73fa8fb2aa4203e57b9875f0b240e78782).

**Comment by SangwonOh** [comment]
We are planning to develop a UI and api interface that can display ABR naturally in iOS Safari. We will let you know when the feature implementation is complete.

**Comment by scar63** [comment]
@SangwonOh Hi, 

Thank you for this information, this feature could be interesting.

On the other hand, do you think you can correct the bug (perhaps intentional?) of the preview image which does not remain displayed as soon as a flow is detected?

For example with the image option defined, I have the following behavior =>

If no stream is sent to the player, the defined image is displayed.
If a stream is detected, the first image is displayed.

If I refer to the documentation this doesn't seem to be the normal behavior => https://airensoft.gitbook.io/ovenplayer/initialization#image

To fix this, I made the following change to the ThumbnailTemplate function in Ovenplayer.js:

`
Thumbnail template: function (e, t) {
                                     return '<div class="op-thumbnail-container"><div class="op-thumbnail-wrapper">' +
                                         "".concat(t.image ? '<img src="'.concat(t.image, '">'): "") +
                                         "".concat(t.title ? '<div class="op-thumbnail-header">'.concat(t.title, "</div>") : "") +
                                         "</div></div>";
                              },
`
