### ISSUE TITLE
Installing in React results in "TypeError: Cannot read properties of null (reading 'id')"

### ISSUE THREAD

**Issue by dprisikar** [AirenSoft/OvenPlayer#294]
Hi,

I have just installed the player in React using NPM (package.json dependencies look okay). 

Added OvenPlayer with ```import OvenPlayer from "ovenplayer";``` to a page with other components. 

Then, inside a function, defined a constant like this ("stream" variable is a "wss://..." url defined earlier):
 ```
const player = OvenPlayer.create("player_id", {
    mute: false,
    volume: 100,
    sources: [
      {
        type: "webrtc",
        file: stream,
      },
    ],
  });
```
Eventually, rendered the player in a ```<div>``` with an id, like so:
```
return (
 <div className="player-wrapper">
     <div id="player_id"></div>
  </div>
   ...
);
```

After compiling, I keep receiving the same error:
```
Uncaught TypeError: Cannot read properties of null (reading 'id')
    at Ar (ovenplayer.js:6624:1)
    at ir.create (ovenplayer.js:6669:1)
   ...
```

I have gone through pretty much all of the resources and all of the issues discussed here, but can't seem to find the answer on how to fix this. 

These two seem to be somehow relevant, but I still struggle with making use of them:
https://github.com/AirenSoft/OvenPlayer/issues/245
https://github.com/AirenSoft/OvenPlayer/issues/248

Any help would be very much appreciated!

**Comment by dprisikar** [comment]
![image](https://user-images.githubusercontent.com/101226750/180837371-e9aa6181-9ed4-454e-af93-b463a0dda3c2.png)

**Comment by SangwonOh** [comment]
@dprisikar Hi. It looks like player initialization was executed before `<div id="player_id"></div>` was created in your react app lifecycle. Before initializing the player, make sure that the DIV element already exists.
```
const div = document.getElementById("player_id") // <- please check this div is null
const player = OvenPlayer.create("player_id", {
   mute: false,
   volume: 100,
   sources: [
     {
       type: "webrtc",
       file: stream,
     },
   ],
 });```

**Comment by dprisikar** [comment]
@SangwonOh, thanks for the tip! It helped.

It looks like I managed to solve this with a combination of `useState` and `useEffect`, where the player is rendered after the initial mount.
