### ISSUE TITLE
help: Opening ports on connection

### ISSUE THREAD

**Issue by albeliakov** [AirenSoft/OvenPlayer#301]
Hello! Thanks for the player.

If a client opens multiple connections to OME, will those connections always be on different ports?

**Comment by Quisi** [comment]
Hi there, i don't really get your question.. ? ASAIK one connection blocks one port, however you can stream to multiple endpoints like /app/stream /app/hello /app/albeliakov etc all over your "might be" rtmp 1935 or whatever... for streaming to, the port may be the same, difference is the streaming key... or am i missing out something?

**Comment by albeliakov** [comment]
@Quisi If a client opens multiple connections to the same stream, will the connections always be connected on different ports?

I want to track when the client closes the connection. Can I do this by the port number of the connection being closed?

**Comment by Quisi** [comment]
My network-knowlege is not that deep, but, you (player A) basically connect to a stream, and establish the connection via a random port something about 50000-65535 whatever is free on your client (player A). another player (player B) on the same machine connects to the same address with a different "free" port (50k-65535 even might be under 50k idk).
So YES, every stream has its own (client)-port, but reading the status by port is the wrong way to go in my oppinion. 
You can handle this by either handling client-events (like clicking on a stop-button) or ask the server (stream) if a connection has been closed/is alive...
Other opinions are welcome :)
