### ISSUE TITLE
Help: changing sources on the fly

### ISSUE THREAD

**Issue by vtu-dog** [AirenSoft/OvenPlayer#303]
Hello,
I'd like to change OvenPlayer's list of sources (and refresh it) programmatically. Is it possible with the current API?

**Comment by SangwonOh** [comment]
You can use this api https://airensoft.gitbook.io/ovenplayer/api-reference/api#load

Also we are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
