### ISSUE TITLE
Can't have multiple LL-HLS players in one page

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#305]
If we try to start to ll-hls players, for different sources, they all eventually play the same video, or, frames from one play in the other and vice versa.

I took a look at the code and it seems that ovenplayer creates one global instance of hls.js, which might be causing this problem.  I'm not very familiar with hls.js so that's just a guess.

**Comment by getroot** [comment]
Duplicate issue with https://github.com/AirenSoft/OvenMediaEngine/issues/860

**Comment by getroot** [comment]
Oh you're the author of https://github.com/AirenSoft/OvenMediaEngine/issues/860. Could you please check the master branch to see if the issue is resolved?

**Comment by hernanrz** [comment]
Yep I'm pulling the latest docker image to test now, I'll let you know the results!

**Comment by getroot** [comment]
Since it hasn't been released yet, you should use airensoft/ovenmediaengine:dev .
