### ISSUE TITLE
ColourSpace/gamma tagging

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenPlayer#310]
I’ve recently started using an iPad Pro for my streams. I do color work and send out an iPad Pro to the client who uses it to watch the stream. The 12’9 iPad now has a reference mode which sets it to sRGB color space, however it also sets it to sRGB gamma which unlike gamma 2.2 has a linear portion their the bottom, this results in the shadow detail of my stream being lifted thus making the iPad unusable . 

Therefore I have two questions: 

AnYone know of a WebRTC Player App for the iPad that could open OME streams?

and

is there a way add Colorspace/Gamma Tag Tom the Player so the iPad knows from which colorpace/gamma to convert from?

**Comment by zcolor** [comment]
Hi,

sorry, completely forgot to reply. My issue is that the iPad Pro has a reference mode, which is great for my purposes as I need my clients to have colour accuracy when watching a stream.

However, the iPad defaults to sRGB gamma instead of gamma 2.4 when using a web browser, which is troublesome as it is not the correct gamma for video. 
That's why I wondered if there was a way to add a Colourspace/gamma tag to the stream or to the play/webpage so that the iPad detects it and applies the correct reference mode.

**Comment by SangwonOh** [comment]
@zcolor Hi. Welcome back. I did some of research but couldn't find any information about gamma control of WebRTC stream. This topic might be a good idea to talk about in the WebRTC community.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
