### ISSUE TITLE
webRTC Lag in Video playback?

### ISSUE THREAD

**Issue by qwerty13** [AirenSoft/OvenPlayer#312]
Hi,
I am running OME on docker on ubuntu on a VMWare with 2x4 CPU, 8 gig RAM and a bridged Network adapter (that identify itself as a GB Ethernet), I have totally 16 gig RAM and a core-i7 6700HQ CPU I think be enough for test...

After installing, I run obs live streaming successfully, then I use OvenPlayer to playback. on my system (that runs VMWare too) playback is not bad, latency is about ~2s and video playback is seamless but framerate is about ~10fps. On other PCs and Mobiles (specially low-ends) story is different, audio is good, latency is about ~4s but video playback is some random frames in every several seconds :/

What's the problem?
(Another question, is any windows native webRTC player or at least API to make it?)

**Comment by getroot** [comment]
Check out the FAQ to see if there is anything that might solve your problem. Usually, when testing in local, latency of less than 1 second is normal.

https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#streaming-is-not-smooth

And it's a good idea to post this issue to the OvenMediaEngine repo.
