### ISSUE TITLE
OvenPlayer on webserver 404

### ISSUE THREAD

**Issue by jacob-gold** [AirenSoft/OvenPlayer#315]
Hi,

I'm trying to run OvenPlayer on an Ubuntu 20.04 server but after following the steps here: https://airensoft.gitbook.io/ovenplayer/examples/runs-on-webserver
I'm getting a 404 from nginx. Is there some obvious step that I'm missing? I cloned OvenPlayer to /usr/share/nginx/html

I have version 1.18.0 of nginx installed

**Comment by SangwonOh** [comment]
@jacob-gold Hi. Please try `http://YOUR_IP/OvenPlayer/demo/demo.html`.  Our gitbook document may out of date.

**Comment by jacob-gold** [comment]
Unfortunately that didn't seem to fix it. I've also tried to delete the OvenPlayer folder from /usr/share/nginx/html and reclone it with no luck.

**Comment by walter8729** [comment]
hello, im using trafex, a dockerized nginx - its still work fine for about 2 years. https://hub.docker.com/r/trafex/alpine-nginx-php7/

**Comment by SangwonOh** [comment]
How about using our new quick start pack https://airensoft.gitbook.io/ovenmediaengine/quick-start

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
