### ISSUE TITLE
WebRTC Processing video

### ISSUE THREAD

**Issue by luca-cesari** [AirenSoft/OvenPlayer#316]
Hi, 
I need to process video from a camera using the implemented WebRTC from in OvenMediaEngine. I am processing the video with opencv in python but I don't know how to connect to the server and take the video because it seems to be incompatible. Is there any recommendation to do that? Thanks!

**Comment by gregfr** [comment]
If it's a Oven Media Engine related issue, please go to: https://github.com/AirenSoft/OvenMediaEngine/issues

This is the Oven Player repository (I made the mistake not so long ago :) )
