### ISSUE TITLE
OvenPlayer Autoplay not working with audio

### ISSUE THREAD

**Issue by Sanjeewa248** [AirenSoft/OvenPlayer#317]
When I try to autoplay a video with sounds, it's not working. Please help me to Autoplay a video with audio.

**Comment by walter8729** [comment]
is because browser policy, read documentation, https://airensoft.gitbook.io/ovenplayer/initialization#autostart

**Comment by Sanjeewa248** [comment]
> is because browser policy, read documentation, https://airensoft.gitbook.io/ovenplayer/initialization#autostart

Do you have any idea to bypass this?

**Comment by gregfr** [comment]
It's on purpose by the browser's developers, it's not by-passable (or if it is, it's a bug and shouldn't be used).

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
