### ISSUE TITLE
iOS native player

### ISSUE THREAD

**Issue by AlienJust** [AirenSoft/OvenPlayer#318]
How to get native player for iOS app development?

**Comment by gregfr** [comment]
You probably should consult Apple's documentation on writing a native player, if it's your goal.

**Comment by command-tab** [comment]
One possibility: You can provide your OME instance’s HLS stream URLs to the native iOS video player components.

**Comment by AlienJust** [comment]
> You probably should consult Apple's documentation on writing a native player, if it's your goal.

I mean I thought there is already some implementation :-)
I read about it at the ovenmediaplayer website (https://www.ovenmediaengine.com/ovenplayer) in features list.
![features](https://user-images.githubusercontent.com/739189/211654948-6a56dc7b-ede3-4437-8035-c312fe478953.png)

**Comment by getroot** [comment]
@AlienJust Native Player is not open source. It is available to our partners under special agreements.

**Comment by mooncatventures-group** [comment]
So following you Advice we have been trying to implement a Native IOS Player, this is a big ask from especially our bigger clients.

Accoring to you if  we follow your protocol here

The Signaling Protocol is as follows.
https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#signalling-protocol

This can be easily implemented by looking at our OvenPlayer or performance testing tool.

` func getOffer() throws -> SignalMessage {
        guard let socket = socket else {
            throw SignalingError.notConnected
        }
        
        try socket.write(message: SignalMessage(command: "request_offer").marshal())
        
        guard let offerMsg = try socket.read() else {
            throw SignalingError.offerMessageNotFound
        }
        
        let offer = try JSONDecoder().decode(SignalMessage.self, from: offerMsg)
        
        guard offer.sdp.type != 0 else {
            throw SignalingError.invalidOfferMessage
        }
        
        return offer
    }

From reviewing both OvenPlayer and The test player we have determined that we should call  getoffer after the websocket connects with the following code in the attached Swift signalingClient we get a sucessful connection to the websocket but when we send getOffer we just get a Ping back on the Websocket connection

Can you give us some insight into what we are doing wrong, if we succeed in developing a client we will share our ressearch `

**Comment by mooncatventures-group** [comment]
attached is our signaling client 
[SignalingClientswift.txt](https://github.com/AirenSoft/OvenPlayer/files/13261800/SignalingClientswift.txt)

**Comment by mooncatventures-group** [comment]
Here is our signaling Client 
[SignalingClient.txt](https://github.com/AirenSoft/OvenPlayer/files/13261814/SignalingClient.txt)

**Comment by mooncatventures-group** [comment]
this is our getOffer message 
  write(message: "{command: 'request_offer'}")

This is the equivalent command in your OvenPlayer
<!DOCTYPE html>

sendMessage(ws, {
--
command: "request_offer"
});

**Comment by SangwonOh** [comment]
@mooncatventures-group  Thanks for many useful information!

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
