### ISSUE TITLE
rtmp publish failed

### ISSUE THREAD

**Issue by lystormenvoy** [AirenSoft/OvenPlayer#320]
I compile the latest source code on CentOS7, and try to publish a stream to server via rtmp.
But the publisher publish failed after seconds.
There is the log:
[ovenmediaengine.log](https://github.com/AirenSoft/OvenPlayer/files/10214889/ovenmediaengine.log)

My application name is set to 'hls'.

**Comment by gregfr** [comment]
If it's a Oven Media Engine related issue, please go to: https://github.com/AirenSoft/OvenMediaEngine/issues

This is the Oven Player repository (I made the mistake not so long ago :) )
