### ISSUE TITLE
How do I correctly import OvenPlayer?

### ISSUE THREAD

**Issue by KentC93** [AirenSoft/OvenPlayer#322]
`import OvenPlayer from "ovenplayer";`
Throws: 

> Uncaught SyntaxError: The requested module 'ovenplayer.js' does not provide an export named 'default'

`import { OvenPlayer } from "ovenplayer";`
Throws:

> Uncaught SyntaxError: The requested module 'ovenplayer.js' does not provide an export named 'OvenPlayer'

`import * as OvenPlayer from "ovenplayer";`
Throws:

> Uncaught TypeError: OvenPlayer.create is not a function

It attaches itself to the window object nicely and works without using an import, however I'd still like to use it within a module.
I'm not using any build tools / bundlers. What have I missed?

**Comment by command-tab** [comment]
I had success a while ago using the non-destructured import (your first example): https://github.com/AirenSoft/OvenPlayer/issues/245#issuecomment-1007886613 If that doesn’t work now, perhaps the module is broken? I’ll give it a shot this evening and see if I can reproduce your issue.

**Comment by command-tab** [comment]
`import OvenPlayer from 'ovenplayer'` is working for me with version 0.10.23. I can import it, call `OvenPlayer.create(...)` and see it render on the page.

**Comment by command-tab** [comment]
Oh, but I am using a bundler. That’s probably the difference.

**Comment by SangwonOh** [comment]
@command-tab  Thanks for help.
There may be differences depending on whether you use a bundler or not.
We plan to make OvenPlayer completely modular.
We will close this issue for now and let you know once the plan is in place.
