### ISSUE TITLE
Is it possible to use a CDN with LLHLS ?

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenPlayer#323]
Greetings

I'm used to stream regular HLS through an http CDN, is it possible to do that with OME LLHLS? I've tried to configure the CDN , when sending a request I receive what seems to be a correct answer, but when trying to "play" the URL in http://demo.ovenplayer.com I see "Invalid session key" in the server's log...

Thanks in advance

Regards

**Comment by SangwonOh** [comment]
@gregfr Hi. This doesn't seem to be a player issue. Please close this issue and submit a new issue at https://github.com/AirenSoft/OvenMediaEngine/issues
