### ISSUE TITLE
Question: Does Oven Player support extracting SEI frame from videos?

### ISSUE THREAD

**Issue by jlongo-encora** [AirenSoft/OvenPlayer#326]
I need to watch videos encoded in h264 with SEI (Supplemental Enhancement Information) data. I'd like to know if Oven Player supports extracting SEI message from videos.

**Comment by SangwonOh** [comment]
@jlongo-encora Hi. Unfortunately Oven Player does not support extracting SEI message from videos. Thanks!

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
