### ISSUE TITLE
Understanding "AUTO" rendition

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenPlayer#327]
Greetings
I'm trying to understand how `AUTO` rendition is selected ; I have several renditions in my streams:

![image](https://user-images.githubusercontent.com/361582/211205549-814f2be8-f211-4df7-9e7f-185e396c28dc.png)

but only the lowest is used when AUTO is checked. Widening the video doesn't help (currently it's 1100px).

How does it work?

Thanks in advance

Regards

**Comment by getroot** [comment]
Is it LLHLS or WebRTC?
LLHLS is selected by players after comprehensively evaluating their bandwidth and resolution. It depends on hls.js.
In WebRTC, the player measures the bandwidth and informs the server, and the server sends the corresponding stream to the player.

**Comment by gregfr** [comment]
Thanks for your answer.
It's LLHLS. Do you know if/where this is documented in hls.js?
Thanks
Regards

**Comment by getroot** [comment]
As far as I know, there is probably no documentation that explicitly explains what you want. I think it would be better for you to ask the hls.js community.

Bandwidth estimation is a very difficult problem. You can understand a bit more about this by looking at the recent PR for hls.js.
https://github.com/video-dev/hls.js/pull/4825

**Comment by gregfr** [comment]
Thanks a lot!
