### ISSUE TITLE
Keeping it "live"

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenPlayer#329]
Greetings
When the player is "in synch with live", there is a red bullet in the controls, and when the player is late, the bullet is white and the user can click to "catch up".
Is there a way to keep it "in synch", ie when the play is started, do as the user clicked "live streaming"?

Thanks in advance

Regards

**Comment by SangwonOh** [comment]
Hi @gregfr .

We are using a code `player.seek(Number.MAX_SAFE_INTEGER);`  for syncing with live. So you can combine that with Player Event. https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-statechanged

**Comment by gregfr** [comment]
Thanks for the tip :D
