### ISSUE TITLE
"focus&click" bug on Chrome

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenPlayer#330]
Greetings
I've noticed a curious bug on Chrome (mine is 108.0.5359.94). When the windows is unselected, and the user click the control bar, the control bar disappear and reappear, and the click is handled as if the control bar is hidden, therefore stopping the video.
(BTW is it possible to disable that click-to-pause behavior)?
It works ok on Firefox.

OvenPlayer 0.10.25

Regards

**Comment by SangwonOh** [comment]
@gregfr Sorry. I could not reproduce this issue (chrome v109). Is this still causing at latest browser?

**Comment by gregfr** [comment]
Thanks for your answer. Yes the issue is still in Chrome 110:

![click](https://user-images.githubusercontent.com/361582/219866102-903af813-81b7-4b6b-854b-df9cd718f13a.gif)
_(here it's a single click on the mute icon as the window is unfocused)_


It works if the window is focused:

![click2](https://user-images.githubusercontent.com/361582/219866308-5920f9fd-069a-4eb7-8c3f-b6bf1ca63fdb.gif)
_(here it's a single click on the mute icon but the window is focused)_

**Comment by gregfr** [comment]
After more testing, it seems it's another new bug in Chrome in Linux, I can't reproduce it in win10, so I guess it's not really a problem (except for me personally).
