### ISSUE TITLE
One audio file for different sources

### ISSUE THREAD

**Issue by ArturLinnik** [AirenSoft/OvenPlayer#331]
I want to be able have **3 different videos** on in the OvenPlayer and a **fourth source** with the **audio**, which is the same for the 3 videos.

Those 3 videos are VODs with HLS and the fourth would be another HLS only with the audio which I want to "run in the background" in order to share the same audio for all the videos.

Is that possible with the current code of the OvenPlayer? If not, how could I achieve something like that without modifying so much the source code of the OvenPlayer?

**Comment by SangwonOh** [comment]
@ArturLinnik Hi. This is not possible with the current OvenPlayer. And unfortunately, it seems difficult to implement this with a simple source code modification.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
