### ISSUE TITLE
Event to get currently playing time on livestream.

### ISSUE THREAD

**Issue by vsuperator** [AirenSoft/OvenPlayer#332]
Hey! 
I need to get a time that currently playing for livestream, I can't find such event.
I see that ovenplayer has setTimecodeMode to show the time on a video stream, but I need to have access to this time from the code. Is there any way?

**Comment by SangwonOh** [comment]
@vsuperator Please try this player event listener. https://airensoft.gitbook.io/ovenplayer/api-reference/events#on-time.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
