### ISSUE TITLE
Missing folder in git repository

### ISSUE THREAD

**Issue by arturas1987** [AirenSoft/OvenPlayer#334]
Hello, https://airensoft.gitbook.io/ovenmediaengine/getting-started site mentions file in https://github.com/AirenSoft/OvenMediaEngine/archive/0.15.1.tar.gz but this file and archive folder does not exist. Where can I get it, or else, someone should update the documentation.

**Comment by getroot** [comment]
Oh there was a typo in the documentation.

Download from https://github.com/AirenSoft/OvenMediaEngine/archive/v0.15.1.tar.gz link. I also updated the docs.

(And here is the OvenPlayer repo, not OvenMediaEngine.)
