### ISSUE TITLE
Programmatically control HLS quality selection

### ISSUE THREAD

**Issue by jwoertink** [AirenSoft/OvenPlayer#338]
Is there a way to control the HLS quality selection programmatically? For example, I have a live stream going which offers 480, 720, and 1080, but I only want to show the 1080 option and have it usable based on some condition. (e.g. paid featured, or whatever)

**Comment by getroot** [comment]
It would be the best way to create and service multiple playlists in OvenMediaEngine.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
