### ISSUE TITLE
Ovenplay reactjs component

### ISSUE THREAD

**Issue by bakirrayan** [AirenSoft/OvenPlayer#343]
Hey everyone,
is there a way to use ovenplay with reactjs ??

**Comment by E3FxGaming** [comment]
Using Next.js (which provides functionality on top of React) this works for me:

1) install ovenplayer with  `npm i ovenplayer`

2) The `VideoPlayer.tsx` file:

```tsx
'use client'
import { useEffect } from 'react';

export default function VideoPlayer() {
    useEffect(() => {
        import('ovenplayer').then(OvenPlayer => {
            OvenPlayer.create('player_id', {
                sources: [
                    {
                        label: 'label_for_video',
                        // Set the type to 'mp4', 'webm' or etc
                        type: 'mp4',
                        file: 'https://download.samplelib.com/mp4/sample-5s.mp4'
                    }
                ]
            });
        })
    })

    return <div id="player_id"></div>;
}
```

I had to put `'use client'` at the top of the file to stop Next.js from trying to render the component on the server (=> the ovenplayer import makes use of the `window` object which doesn't exist on the server side).

The React `useEffect` hook is used for initializing the player after the div is inserted into the DOM.

If you use a different system on top of React you may have to find a different way to enforce client-side rendering. `useEffect` is standard React functionality.

3) The VideoPlayer is used like any other React component - import it with something like

```tsx
import VideoPlayer from './VideoPlayer';
```

and then simply use `<VideoPlayer />`

**Comment by shiblijamal10** [comment]
@E3FxGaming nice...

**Comment by SangwonOh** [comment]
Thanks you all.

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
