### ISSUE TITLE
Format MPEG-TS and 265 codec

### ISSUE THREAD

**Issue by dunkan** [AirenSoft/OvenPlayer#344]
Will you add the ability to play videos in format MPEG-TS with 265 codec?

**Comment by SangwonOh** [comment]
Hi @dunkan OvenPlayer is based on HTML <video> element. The codecs can be played are developed by browser vendors. So not the OvenPlayer area. Thanks for contributing.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
