### ISSUE TITLE
Player error when running as iOS in Firefox DevTools

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#345]
While testing our website for iPhones on windows desktop, i came across this error where ovenplayer crashes if one selects any iOS device in the responsive design dev tools in firefox

Note that the player works fine in an actual iOS device, the error happens in firefox devtools

Attached screenshot of the error:

![image](https://user-images.githubusercontent.com/13426225/232178879-93ce006e-b4c0-4e10-8ad2-b2f1cb388180.png)

**Comment by SangwonOh** [comment]
@hernanrz Hello. The firefox ios emulation mode is providing a strange `navigator.appVersion`. Since the player must be loaded, we will make an exception for that situation. Thanks!

**Comment by SangwonOh** [comment]
Fixed at 87c30230a856cf379f6f6032855d58b88f83a074
