### ISSUE TITLE
Question about fatal errors

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#347]
According to the docs, hls.js can throw fatal or non fatal errors, my question is: Do the non-fatal errors also trigger an "error" state change event in the player?

**Comment by SangwonOh** [comment]
@hernanrz Hi. Thanks for reading our documents. For the non-fatal hls errors the OvenPlayer do not trigger the error state.

https://github.com/AirenSoft/OvenPlayer/blob/73531ffdcd9baf363710ce7d44acd5bfebdc4944/src/js/api/provider/html5/providers/Hls.js#L192

**Comment by hernanrz** [comment]
Thanks! We are seeing many errors with ovenplayer, playing a HLS stream created by nginx-rtmp, videojs on the other hand doesn't throw errors at all with the same stream... I don't know how to capture the details of the errors, any tips on how to debug these errors would be appreciated

**Comment by hernanrz** [comment]
Thanks! We are seeing many errors with ovenplayer, playing a HLS stream created by nginx-rtmp, videojs on the other hand doesn't throw errors at all with the same stream... I don't know how to capture the details of the errors, any tips on how to debug these errors would be appreciated

**Comment by SangwonOh** [comment]
@hernanrz You can hook the hls instance and add error event listener.

```js
    ovenPlayer.on('hlsPrepared', function (hls) {
        console.log(hls);
        hls.on(Hls.Events.ERROR, function (event, data) {
            // This is error data HLS.js throws
            console.log(data);
        });
    });
```

**Comment by hernanrz** [comment]
Thank you, I'll try this
