### ISSUE TITLE
How to get a MediaStream that video can play based on webrtc

### ISSUE THREAD

**Issue by zw12579** [AirenSoft/OvenPlayer#35]
Hello:
    I don't want to create a video DomElement, I want to get the video playable stream directly to achieve the panorama.
    Below is my demo and code.
![image](https://user-images.githubusercontent.com/33717789/53870326-fdad9780-4034-11e9-8716-cd60afbdf14e.png)

![image](https://user-images.githubusercontent.com/33717789/53870490-49f8d780-4035-11e9-9023-1fdd030face7.png)

**Comment by underdoggg** [comment]
You can use the video tag's stream after capturing it with MediaStream, as follows: 
Did this answer help?

**Comment by zw12579** [comment]
No, you understand what I mean wrong. I want to capture the stream for panoramic rendering before creating the video tag. However, I have implemented the functionality I want by modifying your source code. Thank you very much for your reply！

**Comment by underdoggg** [comment]
Thank you very much! Good luck.
