### ISSUE TITLE
Don't show new source until it's loaded

### ISSUE THREAD

**Issue by ArturLinnik** [AirenSoft/OvenPlayer#351]
I have added 2 new buttons to the OvenPlayer which do the exact same function as setSource(), but instead of choosing it from the settings button it changes to the next source.

This is because I need to play 3 videos which are the 3 cameras that where recording a school class at the same time and the user should be able to change to the camera he wants to see at that moment.

The problem is that when changing the source there is a loading time whose duration depends on the internet connection of the user, so when the internet connection is not so good it worsens the user's experience.

My idea is when the user clicks to change to another camera, instead of showing him a black screen, show him the video he was watching until the selected one is loaded. How can I achieve this?

Also... is there an easy way to start caching all the 3 videos from the beginning? That would probably solve this issue too.

Thanks!

**Comment by bchah** [comment]
I would load three instances of OvenPlayer and keep them positioned on top of each other, changing which player is visible (and if applicable, the mute state) based on the user clicking your buttons.

**Comment by ArturLinnik** [comment]
> I would load three instances of OvenPlayer

Yes, this is what we were doing before just using 3 sources because of all the problems of desynchronization and error handling and also the bandwidth.

**Comment by SangwonOh** [comment]
It is not possible to eliminate momentary non-playing states. I think it would be a good idea to display an indicator to the user while loading a new source.

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
