### ISSUE TITLE
Player background image goes black when stream stops

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenPlayer#352]
Hi @SangwonOh - OvenPlayer goes to a black background (or whatever you set _background-color_ as in the player container) when the stream stops, even if it is initialized with a background image. Would it be possible to go back to the background image when the stream stops instead?

Video example: https://user-images.githubusercontent.com/33604674/236021782-895a6abb-02a4-4ccd-bac4-47bb17e8fe9d.mp4

I started on a workaround for this but it feels like a feature improvement that would make OvenPlayer better for everybody. Hopefully you agree 😀

**Comment by SangwonOh** [comment]
@bchah Hi! I fixed the Video element to correctly redisplay the poster image when the playback fails. Please check v0.10.28! Thanks.

**Comment by bchah** [comment]
@SangwonOh Thank you! This is a good improvement 👍🏻 If you have time, can you also implement the same behaviour when calling player.load(source) ? Right now if the source is not live when this method is called, it exhibits the same behaviour of the disappearing background.

**Comment by bchah** [comment]
Fixed in 0bdfcf7 !!

🥇🥇🥇🥇🥇🥇

**Comment by SangwonOh** [comment]
@bchah Hi!. Thanks for testing!💯 And also released to v0.10.29! Thanks again!
