### ISSUE TITLE
Live stream DVR not working when target latency is set

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenPlayer#360]
If you set options to manage playback latency, then DVR doesn't work as expected when a user clicks on the bar, it instantly goes back to the rightmost part of the bar.

You can see this behavior on the demo page https://demo.ovenplayer.com/#%7B%22playerOption%22%3A%7B%22autoStart%22%3Atrue%2C%22autoFallback%22%3Atrue%2C%22mute%22%3Atrue%2C%22sources%22%3A%5B%7B%22type%22%3A%22ll-hls%22%2C%22file%22%3A%22https%3A%2F%2Fllhls-demo.ovenmediaengine.com%2Fapp%2Fstream%2Fllhls.m3u8%22%7D%5D%2C%22hlsConfig%22%3A%7B%22liveSyncDuration%22%3A1.5%2C%22liveMaxLatencyDuration%22%3A3%2C%22maxLiveSyncPlaybackRate%22%3A1.5%7D%7D%2C%22demoOption%22%3A%7B%22autoReload%22%3Atrue%2C%22autoReloadInterval%22%3A2000%7D%7D

**Comment by SangwonOh** [comment]
If target latency is set, hls.js will always try to set playback time to (latest - target latency). I think we need to check how it can be applied together when it is a DVR.

**Comment by SangwonOh** [comment]
It looks like I can dynamically change the target latency setting.

**Comment by SangwonOh** [comment]
pached at 5b7b7b4
