### ISSUE TITLE
360 streaming playback

### ISSUE THREAD

**Issue by brahimfarhat** [AirenSoft/OvenPlayer#364]
Hi, I'm currently running a application for 360 live streaming using ovenmediaengine and ovenplayer. The pipeline is working fine, however, at the player side I'm enable to immerse into the 360 degree scene. Is it possible to do so using the Ovenplayer js as it can be done when using A-frame or Threejs? 

Thank you!

**Comment by SangwonOh** [comment]
@brahimfarhat I'm sorry but OvenPlayer can't used like you said. Not in the plans yet. Thanks.

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please open a new issue.
