### ISSUE TITLE
Is it possible to set the playback rate for m3u8 video?

### ISSUE THREAD

**Issue by Jamong435** [AirenSoft/OvenPlayer#366]
I checked that I can adjust the playback rate of mp4 videos, is it impossible to do m3u8 videos?

thanks

**Comment by SangwonOh** [comment]
@Jamong435 Yes. Same as mp4 video!

**Comment by Jamong435** [comment]
`this.playerOption = {
                    "autoStart": autoStart,
                    "autoFallback": autoFallback,
                    "playbackRate" : playbackRate,
                    "image" : thumbnail,
                    "mute": mute,
                    "sources": [
                        {
                        "type":sourcesType,
                        "file": sourcesFile
                        }
                    ],
                    "hlsConfig": {
                        "liveSyncDuration": liveSyncDuration,
                        "liveMaxLatencyDuration": liveMaxLatencyDuration,
                        "maxLiveSyncPlaybackRate": maxLiveSyncPlaybackRate
                    },
                    "secondfile" : secondfile,
                };`


When you do the same code above, mp4 works and m3u8 doesn't work...
thanks

**Comment by hernanrz** [comment]
Looks like enabling the settings to manage latency (`hlsConfig`) overrides `playbackRate`, if you don't set those options, `playbackRate` works as expected with hls streams
