### ISSUE TITLE
[Feature Request] Allow seek with double tap

### ISSUE THREAD

**Issue by razethion** [AirenSoft/OvenPlayer#371]
Many web players allow (typically mobile) users to double tap the left/right of the screen to seek. Having dedicated buttons is nice, but can be hard to hit on small players. This is something a user is requesting from our site, and would be nice to have.

**Comment by naanlizard** [comment]
I was just thinking about this

I'd suggest something like the old Apollo (for reddit) app's UI, where you can put your finger on the video and slide either direction to seek. It was very slick

**Comment by dygy** [comment]
@razethion you can close the issue since @hernanrz did your feature

**Comment by SangwonOh** [comment]
Thanks again @hernanrz for implementing this feature.

We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
