### ISSUE TITLE
Feature Request: WHEP Support

### ISSUE THREAD

**Issue by sefacndmr01** [AirenSoft/OvenPlayer#375]
Do you have any plans to add WHEP support to your roadmap, or would you consider such an addition?

[WebRTC-HTTP Egress Protocol (WHEP)](https://www.ietf.org/id/draft-murillo-whep-02.html)

**Comment by SangwonOh** [comment]
Hi @sefacndmr01 Please look at this comment.
https://github.com/AirenSoft/OvenMediaEngine/issues/990#issuecomment-1375839211

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
