### ISSUE TITLE
Destroy when media not fully loaded race condition

### ISSUE THREAD

**Issue by mj1618** [AirenSoft/OvenPlayer#391]
I'm using react with Ovenplayer as a component that creates a player and then destroys it. I notice that sometimes the destroy() can hit an issue and I think this is an easy fix.

This issue is here in Ovenplayer;
https://github.com/AirenSoft/OvenPlayer/blob/master/src/js/api/media/Manager.js#L68

And basically if the media hasn't fully loaded this can throw an error since videoElement is still: ""

I recommend adding a check for this, and continue properly destroying the player even if not fully loaded.

Would you be happy if I submit a PR?

**Comment by SangwonOh** [comment]
Thanks for contributing. Merged and will be released soon!

**Comment by SangwonOh** [comment]
Thanks again @mj1618 I was very happy for your pull!
Released since  v0.10.32.
