### ISSUE TITLE
Error Initializing HLS but only in Chrome--and the demo site works

### ISSUE THREAD

**Issue by krisdahl** [AirenSoft/OvenPlayer#395]
I'm serving up an LLHS stream via Oven Media Engine.

I can get the llhs .m3u8 to play in Safari, but in Chrome I get a "Error Initializing HLS".

The odd thing is if I copy and paste the HLS .m3u8 URL into [ovenplayer demo](https://demo.ovenplayer.com/) it loads in Chrome AND Safari--even with the same exact player initialization settings.

Any ideas why that may be happening?

**Comment by SangwonOh** [comment]
@krisdahl Hi. Did you import hls.js?
`<script src="https://cdn.jsdelivr.net/npm/hls.js@latest/dist/hls.min.js"></script>`
https://airensoft.gitbook.io/ovenplayer/#initialize-for-hls

**Comment by zguig52** [comment]
This discussion helped me to make it work #333

**Comment by krisdahl** [comment]
Dang, I feel like an idiot, that was the problem. And makes sense that Safari has native HLS support.

Okay thanks guys!
