### ISSUE TITLE
PIP mode (Picture in Picture)

### ISSUE THREAD

**Issue by zguig52** [AirenSoft/OvenPlayer#396]
Hi,
As the right click is showing OvenPlayer infos, I cannot find a way to allow PIP mode through OvenPlayer (to allow keeping the video in foreground while navigating).
Is it something available through options or customizations? On the roadmap? Not possible?

**Comment by SangwonOh** [comment]
We are closing the issue due to a long period of inactivity.
If further discussion is needed, please reopen the issue.
