### ISSUE TITLE
OvenPlayer as an ES6 module ERROR HLS 

### ISSUE THREAD

**Issue by zdimaz** [AirenSoft/OvenPlayer#402]
Alternatively, you can use OvenPlayer as an ES6 module as follows:
import OvenPlayer from 'ovenplayer';

// Initialize OvenPlayer
const player = OvenPlayer.create('player_id', options)

ERROR HLS !!!!

**Comment by SangwonOh** [comment]
Close vie duplicated issue with (https://github.com/AirenSoft/OvenPlayer/issues/401)
