### ISSUE TITLE
Unable to ear sound on windows browser

### ISSUE THREAD

**Issue by ee91137** [AirenSoft/OvenPlayer#405]
Dear Sir,
I'm unable to ear sound in windows browser ... chrome, firefox, edge...
but on mobile works well...
Nuno

**Comment by SangwonOh** [comment]
Surround works in our test environment. This may be a very special situation, so please provide us with a testing environment and reopen the issue. Thank you.

**Comment by ee91137** [comment]
Hi,

In my case send of video is made by macos computer ...
Reception/browser is Windows7 32bit Firefox/chrome or edge.
I suspect the sound is sent from macos machine with a codec windows7 32bit not have.

In my previous minimac 2014 the sound could be heard well.

Thanks

**Comment by ee91137** [comment]
Please inform me of the codec used for sound transmission so I can try install on windows7 32bit
