### ISSUE TITLE
websocket connection issue

### ISSUE THREAD

**Issue by rishabh8783** [AirenSoft/OvenPlayer#412]
main.js?v=01082022:1 WebSocket connection to 'wss://rtmp.onespy.com:8001/live/3799820240202y5W3p3ez.flv?sign=1706864186-5baa781c305bb473f2c7c351a3f60653' failed: 

main.js?v=01082022:1 [IOController] > Loader error, code = undefined, msg = undefined
[TransmuxingController] > IOException: type = Exception, code = undefined, msg = undefined
main.js?v=01082022:1 Uncaught TypeError: Cannot read properties of null (reading 'flushStashedSamples')

I got this issue for live audio and live video streaming and not have any idea how to solve this anybody have any idea ?

**Comment by SangwonOh** [comment]
Looking at the log, it seems to be an issue that has nothing to do with Oven Player. A detailed explanation of the situation is needed.
If a more detailed explanation is possible, please create a new issue with an explanation.
