### ISSUE TITLE
restore WebRTC stream connection with OvenMediaEngine server

### ISSUE THREAD

**Issue by sys-dev-me** [AirenSoft/OvenPlayer#443]
I am using OvenMediaEngine (OME) as a media router for restreamers. Occasionally, clients disconnect and reconnect after 1 to 3 minutes. I haven't found a way to configure automatic reconnection to the stream after a disconnection.

**Comment by sys-dev-me** [comment]
Topology:
Camera (RTSP) -> Client (jetson/ffmpeg/MPEG-TS) -> restreaming -> SRT -> OME Server (OvenPlayer)

Issue:
When the client loses internet connection, ffmpeg drops the connection and restores it in 5-10 seconds (or sometimes longer, up to 1-2 minutes). The OME server is able to restore the stream after the reconnection, but the OvenPlayer does not resume playing the stream automatically. Manual intervention is required to restart the playback.

**Comment by sys-dev-me** [comment]
Can be closed? realized with event checking

`        this.#player.on('play', () => {
            if (this.#player.getState() !== 'error') {
                if (this.stateCheckInterval) {
                    clearInterval(this.stateCheckInterval);
                    this.stateCheckInterval = null;
                    console.log("Stream is playing, stopping state checks.");
                }
            }
        });

        this.#player.on('error', (error) => {
            console.log("Error playing detection.");
            if (!this.stateCheckInterval) {
                this.stateCheckInterval = setInterval(() => this.checkStreamStatus(), 3000);
            }
        });

        this.#initTabs();
    }

    checkStreamStatus() {
        this.#player.play();
        setTimeout(() => {
            console.log ( "Stop tries for playing" );
            if (this.#player.getState() !== 'error') {
            } else { 
                this.#player.stop();
                }
        }, 3000);
    }

    getPlayingStatus() {
        const state = this.#player.getState();
        return state !== 'error';
    }

`

**Comment by getroot** [comment]
thank you for sharing good experience
