### ISSUE TITLE
Switch Protocol

### ISSUE THREAD

**Issue by JehoenHan** [AirenSoft/OvenPlayer#5]
Does the OvenPlayer provide a method to switch from WebRTC to HLS or MPEG-DASH automatically or manually when the network environment is bad?

**Comment by underdoggg** [comment]
It is automatically switched if you input sources for multiple protocols when you initialize the player.
like this 
let player = OvenPlayer.create("elementID", {
        sources: [
            {type: "webrtc", file: "xxx", label: "WEBRTC LIVE"},
            {type: "mpd", file: "xxx", label: "DASH LIVE"},
            {type: "rtmp", file: "xxx", label: "RTMP LIVE"}
            ]
    });
Was my answer helpful to you?

**Comment by underdoggg** [comment]
@JehoenHan 
Can I close this issue?
