### ISSUE TITLE
Switching between 2 WebRTC streams

### ISSUE THREAD

**Issue by valkoivanov** [AirenSoft/OvenPlayer#57]
Hello,

I'm wondering if/what I'm doing wrong when trying to switch between 2 webrtc streams 

With only one source  (live_o or live2_o) webrtc stream is playing nicely on demo page -> screen 1
  
![screen1](https://user-images.githubusercontent.com/46536048/57452253-00fb1480-726c-11e9-895f-db5b120da344.png)

Modifiying sources to include both webrtc streams, first stream is playing ok -> screen2

![screen2](https://user-images.githubusercontent.com/46536048/57452254-00fb1480-726c-11e9-8041-01c2d0991690.png)

Switching from first to second stream -> screen 3

![screen3](https://user-images.githubusercontent.com/46536048/57452257-0193ab00-726c-11e9-88eb-c0e87ce875a0.png)

Second stream begins to play, but there are some errors - > screen 4

![screen4](https://user-images.githubusercontent.com/46536048/57452258-0193ab00-726c-11e9-80cc-1ee7d21a5ce5.png)

Switching back to first stream -> screen 5

![screen5](https://user-images.githubusercontent.com/46536048/57452259-0193ab00-726c-11e9-90e3-b9ed662d3775.png)

Got more websocket errors -> screen 6
![screen6](https://user-images.githubusercontent.com/46536048/57452260-022c4180-726c-11e9-9150-a0f7f16e1d2b.png)

Added console screen with server when started and server configuration file

![server](https://user-images.githubusercontent.com/46536048/57454328-39512180-7271-11e9-932c-afc8355f27cf.png)
![config1](https://user-images.githubusercontent.com/46536048/57454334-3bb37b80-7271-11e9-9abb-6845a8b65967.png)
![config2](https://user-images.githubusercontent.com/46536048/57454499-abc20180-7271-11e9-8fab-7628cac0d7d9.png)

Kind Regards,

Valko

**Comment by underdoggg** [comment]
@valkoivanov 
It appears that an error occurs when the webrtc source is switched.
Thank you very much for your interest in our product.

**Comment by underdoggg** [comment]
@valkoivanov 
Perhaps I've cleared the issue. 
Would you please check the last version?

**Comment by valkoivanov** [comment]
Thank you,  I'will check and let you know..

**Comment by valkoivanov** [comment]
Hi,

The new fix works on all browsers I tested it (Firefox, Chrome and Opera ) except MS Edge -> screens

![screen_edge1](https://user-images.githubusercontent.com/46536048/57531930-49d1cc80-7343-11e9-96ac-523b99e65a8f.png)
![screen_edge2](https://user-images.githubusercontent.com/46536048/57531931-49d1cc80-7343-11e9-958f-e8185ae2c9b2.png)


Also when Edge is running it generates a lot of warnings in server console

![server_msedge](https://user-images.githubusercontent.com/46536048/57532051-93bab280-7343-11e9-803c-e1ad517e3dcb.png)


Also last question: is it possible to hide loading screen when streams are switched?
A workaround I found is with 2 overlapping players showing/hiding them but it doesn't seem very good or efficient way ...

**Comment by underdoggg** [comment]
Hi. @valkoivanov 
Thank you for your tests.
I've cleared the Edge browser switching issue.

And 
I don't have nice idea for to hide loading screen. 
But I introduce my bad idea.

First, I updated button state when sources switching. Button doesn't showing when sources is switching. (check the last version.)
Next, You can hide loading spinner. Please type your html. 
like this : 
`  
<style  type="text/css">
        .ovp-ellipsis div{
            background-color: transparent !important;
        }
</style>
`

It is not perfect, but it can reduce a lot of strange look.

Thank you.

**Comment by valkoivanov** [comment]
Thank you, I will close the issue
