### ISSUE TITLE
playbox was not displayed

### ISSUE THREAD

**Issue by yoyomule** [AirenSoft/OvenPlayer#6]
Hello, when I tested the ovenplayer demo, I found that the playbox was not displayed(firefox,chrom..), and didn't give the user any hints. It seems to be because there is no flash installed. But the ovenplayer is an html5 player. Is there something wrong with it?
![qq 20181219175413](https://user-images.githubusercontent.com/10000818/50212902-25d31600-03b7-11e9-88e1-936c4a934398.png)

**Comment by underdoggg** [comment]
@yoyomule 
Thank you very much for your interest in our product. 
I checked the screenshot you sent. 
However, there is not enough information to solve this problem. 
Please consider the following methods:
1. Access to https://airensoft.github.io/OvenPlayer/docs/index.html 
2. Press F12 and then capture developer console window 
3. Show me your capture.
Thank you.

**Comment by yoyomule** [comment]
Thank you, it has been solved, the local deployment is no problem.

**Comment by underdoggg** [comment]
In the demo page it seems sometimes fail to load the latest player sources in the main repository. 
I believe so. I updated the latest sources to the demo repository. 
Thank you.
