### ISSUE TITLE
support 4k video streaming

### ISSUE THREAD

**Issue by yoyomule** [AirenSoft/OvenPlayer#75]
Hi，can ovenplayer support 4k video streaming? Need OVM synchronization support?

**Comment by underdoggg** [comment]
Hi! yoyomule. 
Thank you very much for your interest in our player. 
Could you please tell me what is OVM and what do you want to do with the ovenplayer correctly?

**Comment by yoyomule** [comment]
Sorry, I made a mistake, not OVM, it is OvenMediaEngine (OME). I want to play 4K resolution 360VR (panoramic) video in the ovenplayer after streaming webrtc via rtmp.

**Comment by underdoggg** [comment]
@yoyomule 
I got it.
OME have no special restrictions on resolution.
However, 4k video is affected by User's hardware or network spec.
And currently the player does not support VR. lol

**Comment by yoyomule** [comment]
If we want to support VR, how should we transform ovplayer? Maybe we can try it ourselves.

**Comment by underdoggg** [comment]
@yoyomule 
I think there are two ways.
1. run externally without affecting the player source.
2. build your modified player source code.

Of course I have never experienced both. sorry(lol)

**1. run externally without affecting the player source.**

https://threejs.org/examples/#webgl_video_panorama_equirectangular
`<script src="path_yout_lib">three.js</script>`

`var player = OvenPlayer.create("player",{
                    sources : {file : "https://pchen66.github.io/Panolens/examples/asset/textures/video/ClashofClans.mp4", type : "mp4"}
                });`

![스크린샷 2019-06-17 오후 2 53 49](https://user-images.githubusercontent.com/21077205/59581396-bf357780-910f-11e9-897c-5d04e34db855.png)

**2. build your modified player source code.**

download player source. 

![ovenplayer_0 9](https://user-images.githubusercontent.com/21077205/59581527-2ce1a380-9110-11e9-8e25-99b63aab00e4.png)

And you can add provider. 
src/api/provider/html5/providers/Vr360.js 

Maybe you can try build. 
https://github.com/AirenSoft/OvenPlayer/blob/0.9/CONTRIBUTING.md 

It will be a hard journey...

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
