### ISSUE TITLE
Error when setting OvenPlayer.debug(false)

### ISSUE THREAD

**Issue by valkoivanov** [AirenSoft/OvenPlayer#81]
Hello,

Getting message "OvenPlayerConsole is not defined" when setting debug mode to false.

Screen ->
![screen](https://user-images.githubusercontent.com/46536048/59979339-4f335f80-95ef-11e9-8a69-cc230f7f7f84.png)

Regards

**Comment by underdoggg** [comment]
@valkoivanov 

Thank you for your good issue.

Best Regards
