### ISSUE TITLE
autoStrat option doesn't

### ISSUE THREAD

**Issue by dariogomez** [AirenSoft/OvenPlayer#89]
i'm using the OMEPlayer to reproduce my streaming.
The option autoStrat doesn't work and don't start playing.
My code is:

`
 player = OvenPlayer.create("player", {
    			autoStart : true,
            	mute : true,
                sources:[omeURL]
            });
`

**Comment by underdoggg** [comment]
Hi. @dariogomez 

I solved it. 
Please check ee8b2c3

Thank you for your good issue.

**Comment by SangwonOh** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
