### ISSUE TITLE
restart streaming when connection server fail

### ISSUE THREAD

**Issue by dariogomez** [AirenSoft/OvenPlayer#90]
Hi,
Do you have any mechanism to restart the streaming when connection server fail?
The screen shows that error.

<img width="490" alt="Screen Shot 2019-07-13 at 12 18 02 AM" src="https://user-images.githubusercontent.com/1337123/61166460-232b4000-a504-11e9-8d86-06b0c493420d.png">

Thanks in advance!

**Comment by underdoggg** [comment]
Hi. @dariogomez 

Could you please try this? 

`player.on("error", function (error) {
                console.log(error);
                if(error.code > 500){
                    setTimeout(function(){
                        player.load({sources : omeURL});
                    },5000);
                }
            });`

**Comment by SangwonOh** [comment]
@dariogomez And We also updated that showing play button when error occurred. So you can reconnect stream by clicking play button.
